#!/usr/bin/env node
/**
 * Summarise the atomic requirement register (audit/requirements/*.csv) into the tables the
 * delivery register cites: rows per volume by implementation, verification, release and phase
 * origin; rows per delivery package; and the reconciliation of every historical family seed
 * (V<nn>-F<nnn>, from the owner's register of 2026-09-09) to the atomic rows that fall under it.
 * Read-only over the CSVs; writes audit/SUMMARY.md and audit/summary.json. No completion
 * percentage is computed anywhere: counts are counts.
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, 'requirements');
const HEADER = 'id,volume,chapter,page,clause,family_seed,capability_area,impl_status,verif_status,release_status,phase_origin,package,evidence,remaining_work,notes';
const HEADER2 = HEADER + ',source_ref,evidence_scope';

function parseCsv(text) {
  const rows = []; let row = []; let field = ''; let q = false;
  for (let i = 0; i < text.length; i += 1) {
    const ch = text[i];
    if (q) {
      if (ch === '"') { if (text[i + 1] === '"') { field += '"'; i += 1; } else q = false; }
      else field += ch;
    } else if (ch === '"') q = true;
    else if (ch === ',') { row.push(field); field = ''; }
    else if (ch === '\n') { row.push(field); rows.push(row); row = []; field = ''; }
    else if (ch === '\r') { /* ignore */ }
    else field += ch;
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row); }
  return rows;
}

const all = [];
const problems = [];
for (const f of readdirSync(dir).filter((x) => x.endsWith('.csv')).sort()) {
  const rows = parseCsv(readFileSync(join(dir, f), 'utf8'));
  const head = rows.shift();
  if (head.join(',') !== HEADER && head.join(',') !== HEADER2) problems.push(`${f}: header differs: ${head.join(',')}`);
  const cols = head;
  for (const r of rows) {
    if (r.length === 1 && r[0].trim() === '') continue;
    if (r.length !== cols.length) { problems.push(`${f}: row with ${r.length} fields: ${r[0]}`); continue; }
    const o = Object.fromEntries(cols.map((c, i) => [c, r[i].trim()]));
    o.file = f; all.push(o);
  }
}

const count = (items, key) => { const m = new Map(); for (const i of items) { const k = i[key] || '(empty)'; m.set(k, (m.get(k) ?? 0) + 1); } return [...m.entries()].sort((a, b) => (a[0] < b[0] ? -1 : 1)); };
const volumes = [...new Set(all.map((r) => r.volume))].sort((a, b) => Number(a.slice(1)) - Number(b.slice(1)));
const md = [];
md.push('# Atomic requirement register — summary (generated by audit/summarise.mjs)');
md.push('');
md.push(`Rows: ${all.length} across ${volumes.length} volumes. Counts, not percentages. Generated ${new Date().toISOString()}.`);
if (problems.length > 0) { md.push(''); md.push('## CSV problems'); for (const p of problems) md.push(`- ${p}`); }
md.push('');
md.push('## By volume');
md.push('');
md.push('| Volume | Rows | missing | partial | implemented | not-applicable (impl) | verified (passed:*) | unverified | branch-only | merged | phase7 | omission | phase0–6 |');
md.push('|---|---|---|---|---|---|---|---|---|---|---|---|---|');
const n = (items, key, val) => items.filter((r) => r[key] === val).length;
const nPrefix = (items, key, pre) => items.filter((r) => r[key].startsWith(pre)).length;
const phase06 = (items) => items.filter((r) => /^phase[0-6]$/.test(r.phase_origin)).length;
for (const v of volumes) {
  const rs = all.filter((r) => r.volume === v);
  md.push(`| ${v} | ${rs.length} | ${n(rs, 'impl_status', 'missing')} | ${n(rs, 'impl_status', 'partial')} | ${n(rs, 'impl_status', 'implemented')} | ${n(rs, 'impl_status', 'not-applicable')} | ${nPrefix(rs, 'verif_status', 'passed')} | ${n(rs, 'verif_status', 'unverified')} | ${n(rs, 'release_status', 'branch-only')} | ${n(rs, 'release_status', 'merged')} | ${n(rs, 'phase_origin', 'phase7')} | ${n(rs, 'phase_origin', 'omission')} | ${phase06(rs)} |`);
}
const rsAll = all;
md.push(`| **all** | ${rsAll.length} | ${n(rsAll, 'impl_status', 'missing')} | ${n(rsAll, 'impl_status', 'partial')} | ${n(rsAll, 'impl_status', 'implemented')} | ${n(rsAll, 'impl_status', 'not-applicable')} | ${nPrefix(rsAll, 'verif_status', 'passed')} | ${n(rsAll, 'verif_status', 'unverified')} | ${n(rsAll, 'release_status', 'branch-only')} | ${n(rsAll, 'release_status', 'merged')} | ${n(rsAll, 'phase_origin', 'phase7')} | ${n(rsAll, 'phase_origin', 'omission')} | ${phase06(rsAll)} |`);
md.push('');
md.push('## By delivery package (open rows only: missing or partial, or implemented but unverified)');
md.push('');
md.push('| Package | open rows | missing | partial | implemented-unverified | volumes |');
md.push('|---|---|---|---|---|---|');
const open = all.filter((r) => r.impl_status === 'missing' || r.impl_status === 'partial' || (r.impl_status === 'implemented' && r.verif_status === 'unverified'));
for (const [pkg, c] of count(open, 'package')) {
  const rs = open.filter((r) => (r.package || '(empty)') === pkg);
  md.push(`| ${pkg} | ${c} | ${n(rs, 'impl_status', 'missing')} | ${n(rs, 'impl_status', 'partial')} | ${rs.filter((r) => r.impl_status === 'implemented').length} | ${[...new Set(rs.map((r) => r.volume))].sort().join(' ')} |`);
}
md.push('');
md.push('## By capability area (open rows)');
md.push('');
md.push('| Area | open | missing | partial |');
md.push('|---|---|---|---|');
for (const [a, c] of count(open, 'capability_area')) { const rs = open.filter((r) => (r.capability_area || '(empty)') === a); md.push(`| ${a} | ${c} | ${n(rs, 'impl_status', 'missing')} | ${n(rs, 'impl_status', 'partial')} |`); }
md.push('');
md.push('## Historical family seeds → atomic rows');
md.push('');
md.push('Each of the 220 families of the owner\'s register (`audit/The_Eye_Full_Product_Delivery_Register_2026-09-09.md`) with the atomic rows mapped to it. A family with no rows is listed so it is not lost.');
md.push('');
md.push('| Family | rows | missing | partial | implemented | unverified |');
md.push('|---|---|---|---|---|---|');
const famText = readFileSync(join(here, 'The_Eye_Full_Product_Delivery_Register_2026-09-09.md'), 'utf8');
const families = [...famText.matchAll(/^#### (V\d\d-F\d{3}) /gm)].map((m) => m[1]);
const byFam = new Map();
for (const r of all) { if (r.family_seed) byFam.set(r.family_seed, [...(byFam.get(r.family_seed) ?? []), r]); }
let unmapped = 0;
for (const f of families) {
  const rs = byFam.get(f) ?? [];
  if (rs.length === 0) unmapped += 1;
  md.push(`| ${f} | ${rs.length} | ${n(rs, 'impl_status', 'missing')} | ${n(rs, 'impl_status', 'partial')} | ${n(rs, 'impl_status', 'implemented')} | ${n(rs, 'verif_status', 'unverified')} |`);
}
const unknownFams = [...byFam.keys()].filter((f) => !families.includes(f));
md.push('');
md.push(`Families with no atomic row yet: ${unmapped} of ${families.length}. Family seeds used by rows but absent from the owner's register: ${unknownFams.length === 0 ? 'none' : unknownFams.join(', ')}.`);
writeFileSync(join(here, 'SUMMARY.md'), md.join('\n') + '\n');
writeFileSync(join(here, 'summary.json'), JSON.stringify({ rows: all.length, volumes: Object.fromEntries(volumes.map((v) => [v, all.filter((r) => r.volume === v).length])), impl: Object.fromEntries(count(all, 'impl_status')), verif: Object.fromEntries(count(all, 'verif_status')), release: Object.fromEntries(count(all, 'release_status')), phase: Object.fromEntries(count(all, 'phase_origin')), packages: Object.fromEntries(count(open, 'package')), families: families.length, familiesWithoutRows: unmapped, problems }, null, 2) + '\n');
console.log(`rows ${all.length}; open ${open.length}; families ${families.length}, without rows ${unmapped}; problems ${problems.length}`);
