#!/usr/bin/env node
/** Counts over audit/acceptance-units/*.csv: units by status, mandatory units open by package, rows covered. Appends to audit/SUMMARY.md a section "Acceptance units". Counts only. */
import { existsSync, readdirSync, readFileSync, writeFileSync, appendFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const here = dirname(fileURLToPath(import.meta.url));
const dir = join(here, 'acceptance-units');
function parseCsv(text) { const rows = []; let row = []; let f = ''; let q = false; for (let i = 0; i < text.length; i += 1) { const ch = text[i]; if (q) { if (ch === '"') { if (text[i + 1] === '"') { f += '"'; i += 1; } else q = false; } else f += ch; } else if (ch === '"') q = true; else if (ch === ',') { row.push(f); f = ''; } else if (ch === '\n') { row.push(f); rows.push(row); row = []; f = ''; } else if (ch === '\r') {} else f += ch; } if (f.length > 0 || row.length > 0) { row.push(f); rows.push(row); } return rows; }
const HEADER = 'unit_id,statement,condition,source_rows,primary_source,capability_area,mandatory,profiles,evidence_class,status,package,evidence,remaining_work,notes';
const units = []; const problems = [];
if (existsSync(dir)) for (const f of readdirSync(dir).filter((x) => x.endsWith('.csv')).sort()) {
  const rows = parseCsv(readFileSync(join(dir, f), 'utf8')); const head = rows.shift();
  if (head.join(',') !== HEADER) problems.push(`${f}: header differs`);
  for (const r of rows) { if (r.length === 1 && r[0].trim() === '') continue; if (r.length !== head.length) { problems.push(`${f}: bad row ${r[0]}`); continue; } const o = Object.fromEntries(head.map((c, i) => [c, (r[i] ?? '').trim()])); o.file = f; units.push(o); }
}
const count = (items, key) => { const m = new Map(); for (const i of items) { const k = i[key] || '(empty)'; m.set(k, (m.get(k) ?? 0) + 1); } return [...m.entries()].sort(); };
const covered = new Set(); for (const u of units) for (const s of u.source_rows.split(/;\s*/)) if (s.trim()) covered.add(s.trim());
const reqDir = join(here, 'requirements'); let totalRows = 0; const rowIds = new Set();
for (const f of readdirSync(reqDir).filter((x) => x.endsWith('.csv'))) { const rows = parseCsv(readFileSync(join(reqDir, f), 'utf8')); const head = rows.shift(); for (const r of rows) { if (r.length !== head.length) continue; totalRows += 1; rowIds.add(`${r[1]}:${r[0]}`); } }
const coveredKnown = [...covered].filter((c) => rowIds.has(c)).length;
const mandatoryOpen = units.filter((u) => u.mandatory === 'yes' && !u.status.startsWith('verified') && u.status !== 'not-applicable');
const md = [];
md.push(''); md.push('## Acceptance units (from audit/acceptance-units, generated by audit/summarise-units.mjs)'); md.push('');
md.push(`Units: ${units.length}. Source rows referenced: ${covered.size} (${coveredKnown} resolve to register rows of ${totalRows}). Mandatory units not yet verified for every applicable profile: ${mandatoryOpen.length}. Problems: ${problems.length}${problems.length ? ' — ' + problems.join('; ') : ''}.`);
md.push(''); md.push('| Status | units |'); md.push('|---|---|'); for (const [k, v] of count(units, 'status')) md.push(`| ${k} | ${v} |`);
md.push(''); md.push('| Package | open mandatory units |'); md.push('|---|---|'); for (const [k, v] of count(mandatoryOpen, 'package')) md.push(`| ${k} | ${v} |`);
md.push(''); md.push('| Profiles | units |'); md.push('|---|---|'); for (const [k, v] of count(units, 'profiles')) md.push(`| ${k} | ${v} |`);
const summary = join(here, 'SUMMARY.md');
let s = readFileSync(summary, 'utf8'); const idx = s.indexOf('\n## Acceptance units'); if (idx >= 0) s = s.slice(0, idx); writeFileSync(summary, s.replace(/\s+$/, '') + '\n' + md.join('\n') + '\n');
console.log(`units ${units.length}; rows covered ${coveredKnown}/${totalRows}; mandatory open ${mandatoryOpen.length}; problems ${problems.length}`);
