packages:
  - apps/*
  - packages/*
onlyBuiltDependencies:
  - argon2
  - sharp
minimumReleaseAgeExclude:
  - dependency-cruiser@18.1.1
  - jose@6.2.8
allowBuilds:
  argon2: true
  msgpackr-extract: true
  sharp: true
