/**
 * CP-6 B90 browser walk (part M; F-P7-F-10; V7 ch44; DAT-SV-04) — THE CERTIFIED SEMANTIC LAYER through the real interface on the gate's
 * fresh database (the hosted form of e2e/phase6-b90-metrics.demo.spec.ts, which reads the demonstration and is not run by this gate):
 *
 *   the SOURCE (SYNTHETIC): a Strategy Graph measure "Corridor exposure (EUR at risk)" in EUR with three readings 40 days apart — each
 *   observation names an EVIDENCE object, so the gate walks the product's own path to one (an upload contract, one CSV record uploaded);
 *   two products of kind metric registered by the steward for the owner; the steward DECLARES the exposure metric over
 *   measure_observations at grain month (aggregation last, filtered on the measure) and a "(draft)" variant under a different aggregation —
 *   through the routes →
 *   /graph/data/metrics — THE OWNER CERTIFIES from the page (an expiry within 366 days; the certification SIGNED with the executive key the
 *   API holds): the state CERTIFIED, the certification line with its signer, its expiry and the key, the certifications ledger with the
 *   canonical MET object version →
 *   THE SERVE PANEL (an analyst): the analyst view serves the certified metric — the grain, the standing, the definition version and digest,
 *   the SOURCE REVISION over its rows with the freshness, the three values per month in EUR →
 *   THE ACCESS-MODE RULE (the executive): the executive view of the uncertified draft is REFUSED — the server's refusal rendered as such —
 *   and the analyst view serves it MARKED; the executive view of the certified metric is served.
 *
 * HONEST LIMITS (what this gate does not reach): the EXPIRY SWEEP (the tick step metric-certification, order 65: the attention item to the
 * owner) — the tick runs under the scheduler, off in this gate's API, and on demand only in the test runtime; the definition change with
 * its diff and withdrawal, the reproducibility fault and the recalculation's withdrawal, the certification conflict and the health score
 * model are the harness's (apps/api/test/int/phase6-metrics-b90.test.ts) and the demonstration walk's. The readings' instants are the
 * runner's clock (the gate has no database instant; the B36 walks' precedent), 90 / 50 / 10 days back — never two in one month.
 *
 * The seeding is the API's, in the Phase 1 idiom (the B36 gates walk's upload path): this suite makes its own tenant, ONE domain and five
 * DOMAIN principals with a per-run password — the data steward, the owner (a strategy owner), the executive, an analyst, the collection
 * manager (approves and activates the upload contract, uploads the record). Every figure is SYNTHETIC. The signing key is
 * EYE_EXECUTIVE_SIGNING_KEY_DEMO, generated by playwright.config.ts and bound in the API's process; the key id on screen is the server's.
 * The selectors are the page's own (apps/web/app/graph/data/metrics/page.tsx): the combobox "Metric", the labels "metric state",
 * "definition line", "certification line", "serving standing", "source revision", "serve refusal"; #expiry, "Certify v1 (sign)",
 * "Withdraw certification"; the radios "Executive view …" / "Analyst view …", "Serve"; the table "served values"; the list "certifications".
 */
import { createHash } from 'node:crypto';
import { expect, test, type Page } from '@playwright/test';

const API = 'http://localhost:3401';

function required(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`${name} must be provided (generated .eye-local/env or caller environment)`);
  return v;
}
const BOOTSTRAP_PW = required('EYE_TEST_BOOTSTRAP_PASSWORD');
const ADMIN_PW = required('EYE_TEST_ADMIN_PASSWORD');
/** One per-run password for the principals this suite creates; it lives in the worker's memory only. */
const PW = `Mt90!${crypto.randomUUID()}`;
const run = Date.now().toString(36);
const DAY = 86_400_000;
const daysAgo = (d: number) => new Date(Date.now() - d * DAY).toISOString();

function jcs(v: unknown): string {
  if (v === null) return 'null';
  if (typeof v === 'boolean' || typeof v === 'number') return JSON.stringify(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(jcs).join(',')}]`;
  const o = v as Record<string, unknown>;
  return `{${Object.keys(o).filter((k) => o[k] !== undefined).sort()
    .map((k) => `${JSON.stringify(k)}:${jcs(o[k])}`).join(',')}}`;
}
const digest = (v: unknown) => createHash('sha256').update(jcs(v ?? {}), 'utf8').digest('hex');

async function api(path: string, over: Record<string, unknown>, payload: unknown = {}, token?: string): Promise<{ status: number; body: Record<string, unknown> }> {
  const envelope = {
    message_id: crypto.randomUUID(),
    scope: 'PLATFORM', tenant_id: null, domain_id: null,
    principal_id: 'anonymous', purpose_id: 'executive',
    action: 'x', side_effect_class: 'reversible', consequence_class: 'C2',
    object_type: 'MET', object_id: null, schema_version: 'v1',
    issued_at: new Date().toISOString(), clock_quality: 'trusted',
    correlation_id: crypto.randomUUID(), trace_id: 'e2e-b90m',
    ...over,
    payload_digest: digest(payload),
  };
  const res = await fetch(API + path, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...(token !== undefined ? { authorization: `Bearer ${token}` } : {}) },
    body: JSON.stringify({ envelope, payload }),
  });
  return { status: res.status, body: (await res.json()) as Record<string, unknown> };
}
async function loginApi(username: string, password: string) {
  return api('/v1/auth/login', { action: 'identity.session.create', object_type: 'SES', purpose_id: 'authentication' }, { username, password });
}
async function uiLogin(page: Page, username: string, password: string): Promise<void> {
  await page.goto('/login');
  await page.getByLabel('Username').fill(username);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.waitForURL(/\/admin/);
}

interface Ctx { token: string; principalId: string; username: string }
type Row = Record<string, unknown>;
let admin: Ctx; let steward: Ctx; let owner: Ctx; let executive: Ctx; let analyst: Ctx; let collector: Ctx;
let T = ''; let D = ''; let EVD = ''; let OBJ = ''; let MSR = ''; let P_EUR = ''; let P_DRAFT = '';
const KEY_EUR = 'corridor-' + 'exposure-eur';
const KEY_DRAFT = 'corridor-' + 'exposure-eur-draft';
const TITLE_EUR = `Corridor exposure (EUR at risk) (e2e ${run}, SYNTHETIC)`;
const TITLE_DRAFT = `Corridor exposure (EUR at risk) — draft (e2e ${run})`;
const CSV = 'strait,exposure_eur\nBab el-Mandeb Strait,550000\n';

async function person(login: string, roleCode: string): Promise<Ctx> {
  const p = await api(`/v1/tenants/${T}/principals`,
    { action: 'identity.principal.create', scope: 'TENANT', tenant_id: T, object_type: 'PRN', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
    { kind: 'human', displayName: login, loginName: login, password: PW, roleCode, domainId: D }, admin.token);
  expect(p.status, `${login} (${roleCode}) created`).toBe(201);
  const l = await loginApi(login, PW);
  expect(l.status, `${login} signed in`).toBe(201);
  return { token: (l.body as { tokens: { accessToken: string } }).tokens.accessToken, principalId: (l.body as { principalId: string }).principalId, username: login };
}
/** A governed act of this suite's seeding, in the domain, as one of its people. */
const as = (who: Ctx, path: string, action: string, objectType: string, objectId: string | null, payload: unknown, purpose = 'executive') =>
  api(`/v1/tenants/${T}/domains/${D}${path}`, { action, scope: 'DOMAIN', tenant_id: T, domain_id: D, object_type: objectType, object_id: objectId, principal_id: `principal:${who.principalId}`, purpose_id: purpose }, payload, who.token);
const ok = (r: { status: number; body: Record<string, unknown> }, what: string, status = 201) => { expect(r.status, `${what}: ${JSON.stringify(r.body).slice(0, 400)}`).toBe(status); return r.body; };
/** The platform administrator acting in the domain (copied from the B36 gates walk). */
const DOMAIN_ADMIN = (over: Record<string, unknown>) => ({ scope: 'DOMAIN', tenant_id: T, domain_id: D, principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration', ...over });

/**
 * Copied from the B36 gates walk (which copied the memory walk, the retention walk, the B16 harness's uploadContract — the browser gate
 * cannot import a test helper of apps/api): an upload connector under replay, synthetic data, rights CONFIRMED, ceiling INTERNAL, CSV.
 */
function uploadContract(sourceKey: string): Record<string, unknown> {
  return {
    source_key: sourceKey,
    name: 'E2E uploaded records (SYNTHETIC)',
    publisher: 'E2E plant (synthetic)',
    authority_class: 'authoritative',
    connector_kind: 'upload',
    acquisition_mode: 'replay',
    data_origin: 'synthetic',
    identity: { source_identity: sourceKey, publisher_identity: 'e2e (synthetic entity; does not exist)', endpoints: [], scheme_allowlist: ['https'],
                cadence_seconds: 86_400, jitter_seconds: 0, collection_window: null },
    authority_and_rights: {
      owner: 'observation.operations', steward: 'e2e', authority: 'Internal records (synthetic)', legal_basis: 'Internal synthetic data created for the browser gate',
      rights_state: 'confirmed', licence: 'internal', permitted_use: ['internal analysis'], robots_policy: 'not applicable', purposes: ['observation'],
      classification_ceiling: 'internal', residency: 'EU', retention: '24 months', deletion_obligation: 'none',
    },
    security_and_operations: {
      credential_ref: null,
      authentication_method: 'operator upload under an authenticated session',
      authenticity_method: {
        transport_endpoint: 'not applicable — no transport was performed by this system',
        byte_integrity: 'SHA-256 digest verified pre-store, post-store and on every read',
        source_origin: 'operator attestation only',
        content_authenticity: 'not applicable — the records are synthetic and marked as such at object level',
      },
      budgets: { max_requests_per_run: 25, max_bytes_per_run: 33_554_432, max_concurrency: 1, timeout_ms: 60_000, max_retries: 0 },
      expected_schema: { media_types: ['text/csv'], required_fields: [], drift_tolerance: 0, max_bytes: 16_777_216 },
      freshness_expectation: { threshold_seconds: 604_800, expected_interval: 'weekly' },
      coverage_expectations: {
        universe_version: 'v1', denominator_derivation: 'one upload set per reporting period', expected_items_per_window: null,
        not_applicable_dimensions: ['latency', 'correction_lag', 'authenticity'],
        not_applicable_reason: 'the records are synthetic internal data supplied by an operator: there is no publisher to lag behind, no corrections channel, and no external origin to authenticate',
      },
      correction_channel: 'a corrected upload supplied by the operator',
      replay_set: 'e2e-uploads',
    },
    lifecycle: { contract_version: 1, effective_from: '2024-01-01T00:00:00Z', effective_to: null },
  };
}

/** THE EVIDENCE a measure observation names (0089: a claim or an evidence object) — the product's own path: the upload contract registered, approved and activated, one CSV record uploaded. */
async function seedEvidence(): Promise<void> {
  const X = `/v1/tenants/${T}/domains/${D}`;
  const IN = (who: Ctx, over: Record<string, unknown>) => ({ scope: 'DOMAIN', tenant_id: T, domain_id: D, principal_id: `principal:${who.principalId}`, ...over });
  const sourceKey = `e2e-b90-metrics-uploads-${run}`;
  const reg = ok(await api(`${X}/observation/sources/register`, DOMAIN_ADMIN({ action: 'observation.source.register', object_type: 'SRC', purpose_id: 'observation' }), { contract: uploadContract(sourceKey) }, admin.token), 'the upload contract registered');
  const sourceId = (reg as { source: { sourceId: string } }).source.sourceId;
  ok(await api(`${X}/observation/sources/${sourceId}/approve`, IN(collector, { action: 'observation.source.approve', object_type: 'SRC', object_id: sourceId, purpose_id: 'observation' }),
    { contractVersion: 1, decision: 'approve', reason: 'the e2e upload contract reviewed' }, collector.token), 'the upload contract approved');
  ok(await api(`${X}/observation/sources/${sourceId}/transition`, IN(collector, { action: 'observation.source.transition', object_type: 'SRC', object_id: sourceId, purpose_id: 'observation' }),
    { contractVersion: 1, target: 'active', reason: 'the e2e upload contract: active' }, collector.token), 'the upload contract active');
  ok(await api(`${X}/observation/agents/register`, DOMAIN_ADMIN({ action: 'observation.agent.register', object_type: 'AGT', purpose_id: 'observation' }), { sourceId, connector: 'upload', ownerPrincipalId: collector.principalId }, admin.token), 'the upload agent registered');
  const up = ok(await api(`${X}/observation/upload`, IN(collector, { action: 'observation.run.trigger', object_type: 'RUN', purpose_id: 'observation' }),
    { sourceId, contractVersion: 1, files: [{ filename: 'e2e-b90-metrics.csv', mediaType: 'text/csv', base64: Buffer.from(CSV, 'utf8').toString('base64'), documentTime: '2024-01-14T00:00:00Z' }] }, collector.token), 'the record uploaded');
  expect((up as { run: { state: string; admitted: number } }).run, 'the upload run').toMatchObject({ state: 'finished', admitted: 1 });
  const ev = ok(await api(`${X}/observation/evidence/list`, IN(collector, { action: 'observation.read.evidence', object_type: 'EVD', side_effect_class: 'none', purpose_id: 'observation' }), { sourceId, limit: 5 }, collector.token), 'the evidence listed');
  const evd = (ev as { evidence: Array<{ object_id: string }> }).evidence[0];
  expect(evd, 'one admitted record').toBeDefined();
  EVD = evd!.object_id;
}

/* ───────────────────────── the page's own selectors ───────────────────────── */
const short8 = (id: string) => `${id.slice(0, 8)}…`;
/** A datetime-local value (the browser's zone) for an instant d days ahead — what the page turns into the ISO instant the port takes. */
function localDaysAhead(d: number): string {
  const t = new Date(Date.now() + d * DAY);
  const p = (n: number) => String(n).padStart(2, '0');
  return `${t.getFullYear()}-${p(t.getMonth() + 1)}-${p(t.getDate())}T${p(t.getHours())}:${p(t.getMinutes())}`;
}
async function openMetric(page: Page, title: string): Promise<void> {
  await page.goto('/graph/data/metrics');
  await expect(page.getByRole('heading', { name: 'Semantic metrics', level: 1 })).toBeVisible();
  // a wrapping <label> includes its option text: select by role; selectOption takes the option's exact label, read from the option itself
  const select = page.getByRole('combobox', { name: 'Metric', exact: true });
  const label = await select.locator('option').filter({ hasText: title }).first().textContent();
  await select.selectOption({ label: label ?? '' });
  await expect(page.getByRole('heading', { name: title, level: 2 })).toBeVisible();
}
async function serve(page: Page, view: 'executive' | 'analyst'): Promise<void> {
  await page.getByRole('radio', { name: view === 'executive' ? /^Executive view/ : /^Analyst view/ }).check();
  await page.getByRole('button', { name: 'Serve', exact: true }).click();
}

test.describe.configure({ mode: 'serial' });

test.describe('CP-6 B90 — the certified semantic layer: the owner certifies from the page (signed), the analyst view serves the values with grain and source revision, the executive view refuses the uncertified draft', () => {
  test.beforeAll(async () => {
    // Rotation-aware admin sign-in (ADR-P0-17).
    let al = await loginApi('platform-admin', ADMIN_PW);
    if (al.status !== 201 || (al.body as { rotationRequired?: boolean }).rotationRequired === true) {
      const boot = await loginApi('platform-admin', BOOTSTRAP_PW);
      expect(boot.status).toBe(201);
      const bt = (boot.body as { tokens: { accessToken: string }; principalId: string });
      if ((boot.body as { rotationRequired?: boolean }).rotationRequired === true) {
        const rot = await api('/v1/auth/rotate', { action: 'identity.credential.rotate', object_type: 'CRD', principal_id: `principal:${bt.principalId}`, purpose_id: 'authentication' },
          { currentPassword: BOOTSTRAP_PW, newPassword: ADMIN_PW }, bt.tokens.accessToken);
        expect(rot.status).toBe(201);
      }
      al = await loginApi('platform-admin', ADMIN_PW);
    }
    expect(al.status).toBe(201);
    admin = { token: (al.body as { tokens: { accessToken: string } }).tokens.accessToken, principalId: (al.body as { principalId: string }).principalId, username: 'platform-admin' };
    const t = await api('/v1/platform/tenants', { action: 'tenancy.tenant.create', object_type: 'TEN', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
      { name: `E2E B90 Metrics ${run}`, residencyProfile: 'EU' }, admin.token);
    expect(t.status).toBe(201);
    T = (t.body as { tenant: { id: string } }).tenant.id;
    const d = await api(`/v1/tenants/${T}/domains`, { action: 'tenancy.domain.create', scope: 'TENANT', tenant_id: T, object_type: 'CID', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
      { name: `B90 Metrics ${run}` }, admin.token);
    expect(d.status).toBe(201);
    D = (d.body as { domain: { id: string } }).domain.id;
    // FIVE people: the data steward (registers the products, declares the models), the owner (a strategy owner: the measure and its readings; certifies), the executive
    // (the executive view), an analyst (the analyst view), the collection manager (the upload path to the evidence the readings name).
    steward = await person(`m90-steward-${run}`, 'data_steward');
    owner = await person(`m90-owner-${run}`, 'strategy_owner');
    executive = await person(`m90-exec-${run}`, 'executive');
    analyst = await person(`m90-analyst-${run}`, 'domain_analyst');
    collector = await person(`m90-collector-${run}`, 'collection_manager');
    await seedEvidence();
    // THE SOURCE (SYNTHETIC): the objective and its measure in EUR on a SYNTHETIC entity reference; three readings 40 days apart, each naming the evidence
    const declare = async (objectType: string, title: string) => {
      const r = ok(await as(owner, '/graph/strategy/declare', 'graph.strategy.declare', objectType, null,
        { objectType, title, statement: `${title} (e2e, SYNTHETIC)`, status: 'active', restsOn: [{ kind: 'entity', id: crypto.randomUUID(), rationale: 'SYNTHETIC entity reference (the browser gate seeds no graph)' }] }, 'graph'), `${objectType} declared`);
      return (r as { strategy: { objectId: string } }).strategy.objectId;
    };
    OBJ = await declare('OBJ', `Keep the corridor exposure under the hedge (e2e ${run})`);
    MSR = await declare('MSR', `Corridor exposure (EUR at risk) (e2e ${run})`);
    ok(await as(owner, `/graph/strategy/measures/${MSR}/define`, 'graph.measure.define', 'MSR', MSR,
      { objectiveId: OBJ, unit: 'EUR', direction: 'lower_better', targetValue: 500000, targetDate: '2027-06-30', freshnessDays: 60 }, 'graph'), 'the measure defined');
    for (const [value, ago] of [[420000, 90], [610000, 50], [550000, 10]] as Array<[number, number]>) {
      ok(await as(owner, `/graph/strategy/measures/${MSR}/observe`, 'graph.measure.observe', 'MSR', MSR, { value, observedAt: daysAgo(ago), source: { kind: 'evidence', id: EVD } }, 'graph'), `the reading ${value} observed`);
    }
    // THE PRODUCTS of kind metric (the prelude's registry) and THE DECLARATIVE DEFINITIONS (the steward's act): the exposure metric at grain month, the draft under avg
    const register = async (key: string, title: string, purpose: string) => {
      const r = ok(await as(steward, '/products/register', 'products.product.register', 'DPR', null, { key, title, kind: 'metric', purpose, ownerPrincipalId: owner.principalId }), `${key} registered`);
      return String((r as { product: { product_id: string } }).product.product_id);
    };
    P_EUR = await register(KEY_EUR, TITLE_EUR, 'the certified corridor exposure metric served to the executive view (e2e, SYNTHETIC)');
    P_DRAFT = await register(KEY_DRAFT, TITLE_DRAFT, 'an analyst draft of the exposure metric, never certified (e2e, SYNTHETIC)');
    const definition = (over: Row = {}): Row => ({ measure: 'measure_observations', unit: 'EUR', aggregation: 'last', grain: 'month', dimensions: ['measure_id', 'objective_id'], filters: { measure_id: MSR }, effectiveFrom: daysAgo(100), ...over });
    const m = ok(await as(steward, `/products/metrics/${P_EUR}/define`, 'products.metric.declare', 'MET', P_EUR, definition()), 'the exposure metric declared');
    expect((m as { metric: Row }).metric).toMatchObject({ state: 'declared', version: 1, grain: 'month', aggregation: 'last', owner_principal_id: owner.principalId });
    const dr = ok(await as(steward, `/products/metrics/${P_DRAFT}/define`, 'products.metric.declare', 'MET', P_DRAFT, definition({ aggregation: 'avg', title: TITLE_DRAFT })), 'the draft declared');
    expect((dr as { metric: Row }).metric).toMatchObject({ state: 'declared', aggregation: 'avg' });
  });

  test('1. the owner certifies from the page — CERTIFIED; the certification line names its signer, its expiry and the key (SIGNED, the server\'s word); the ledger\'s MET object version', async ({ page }) => {
    await uiLogin(page, owner.username, PW);
    await openMetric(page, TITLE_EUR);
    await expect(page.getByLabel('metric state')).toHaveText('○ declared — uncertified: the analyst view serves it marked, the executive view refuses it');
    await expect(page.getByLabel('definition line')).toContainText(`measure_observations · grain month · last · unit EUR · dimensions measure_id, objective_id · filters {"measure_id":"${MSR}"}`);
    await expect(page.getByLabel('certification line')).toHaveText('not certified');
    await expect(page.getByText(`${short8(owner.principalId)} (you)`)).toBeVisible();
    await expect(page.getByText('Never certified.')).toBeVisible();
    // the owner's act: the expiry within 366 days gates the button (a courtesy check; the port decides)
    const certify = page.getByRole('button', { name: 'Certify v1 (sign)' });
    await expect(certify).toBeDisabled();
    await page.locator('#expiry').fill(localDaysAhead(90));
    await expect(certify).toBeEnabled();
    await certify.click();
    await expect(page.getByLabel('metric state')).toHaveText('● certified — served in the executive view until its expiry');
    const line = page.getByLabel('certification line');
    await expect(line).toContainText(`certified by ${short8(owner.principalId)} at`);
    await expect(line).toContainText(/until \d{4}-\d{2}-\d{2}T/);
    await expect(line).toContainText(new RegExp(`signed by ${short8(owner.principalId)} \\(ed25519:[0-9a-f]{16}\\) at`));
    await expect(line).not.toContainText('UNSIGNED');
    await expect(page.getByText('v1 — digest', { exact: false }).first()).toBeVisible();
    await expect(page.getByText('· certified v1')).toBeVisible();
    const certs = page.getByRole('list', { name: 'certifications' });
    await expect(certs).toContainText('v1 · MET object v1 ·');
    await expect(certs).toContainText(`certified by ${short8(owner.principalId)}`);
    await expect(page.getByRole('button', { name: 'Certify v1 (sign)' })).toBeDisabled();
    await expect(page.getByRole('button', { name: 'Withdraw certification' })).toBeVisible();
    await expect(page.getByText(/committed — POL/).first()).toBeVisible();
  });

  test('2. the serve panel (an analyst): the analyst view serves the certified metric — the grain, the standing, the definition version, the SOURCE REVISION over its rows, the three values per month in EUR', async ({ page }) => {
    await uiLogin(page, analyst.username, PW);
    await openMetric(page, TITLE_EUR);
    // no owner's acts, no definition form for an analyst
    await expect(page.getByRole('button', { name: /^Certify v/ })).toHaveCount(0);
    await expect(page.getByRole('heading', { name: /^Define a model/ })).toHaveCount(0);
    await expect(page.getByRole('combobox', { name: /^Grain/ })).toHaveValue('month');
    await serve(page, 'analyst');
    await expect(page.getByRole('heading', { name: /^Served — analyst view · grain month · as of /, level: 3 })).toBeVisible();
    await expect(page.getByLabel('serving standing')).toContainText('● certified');
    await expect(page.getByText(/^v1 · digest [0-9a-f]{16}… · measure_observations · last · unit EUR · effective from/)).toBeVisible();
    await expect(page.getByLabel('source revision')).toHaveText(/^graph\.measure_observations: [0-9a-f]{64} over 3 row\(s\) · freshness \d+ s$/);
    await expect(page.getByText(/^active · until .* · last valid v1$/)).toBeVisible();
    const values = page.getByRole('table', { name: 'served values' });
    await expect(values.getByRole('columnheader', { name: 'Grain key (month)' })).toBeVisible();
    await expect(values.getByRole('columnheader', { name: 'Value (EUR)' })).toBeVisible();
    await expect(values.getByRole('row').filter({ hasText: /^\d{4}-\d{2}/ })).toHaveCount(3);
    for (const v of ['420000 EUR', '610000 EUR', '550000 EUR']) await expect(values.getByRole('cell', { name: v, exact: true })).toBeVisible();
    // the serving is recorded on the model's ledger
    await expect(page.getByRole('list', { name: 'servings' })).toContainText('analyst · grain month');
    await expect(page.getByRole('list', { name: 'servings' })).toContainText('v1 · certified · revision');
  });

  test('3. the access-mode rule (the executive): the executive view of the uncertified draft is REFUSED — the server\'s refusal rendered as such; the analyst view serves it MARKED; the certified metric is served in the executive view', async ({ page }) => {
    await uiLogin(page, executive.username, PW);
    await openMetric(page, TITLE_DRAFT);
    await expect(page.getByLabel('metric state')).toHaveText('○ declared — uncertified: the analyst view serves it marked, the executive view refuses it');
    await expect(page.getByLabel('definition line')).toContainText('measure_observations · grain month · avg · unit EUR');
    await expect(page.getByLabel('certification line')).toHaveText('not certified');
    await serve(page, 'executive');
    const refusal = page.getByLabel('serve refusal');
    await expect(refusal).toBeVisible();
    await expect(refusal).toContainText('Refused by the server:');
    await expect(refusal).toContainText(`metric rejected (certification): metric ${KEY_DRAFT} is declared — the executive view serves certified metrics only (dashboards are access modes); the analyst view serves it marked uncertified`);
    await expect(page.getByRole('heading', { name: /^Served — / })).toHaveCount(0);
    // the analyst view serves the draft MARKED — the values under its own aggregation (avg), no certification
    await serve(page, 'analyst');
    await expect(page.getByLabel('serve refusal')).toHaveCount(0);
    await expect(page.getByRole('heading', { name: /^Served — analyst view · grain month/, level: 3 })).toBeVisible();
    await expect(page.getByLabel('serving standing')).toContainText('○ UNCERTIFIED — marked · UNCERTIFIED (declared) — served in the analyst view only');
    await expect(page.getByText(/^v1 · digest [0-9a-f]{16}… · measure_observations · avg · unit EUR/)).toBeVisible();
    await expect(page.getByLabel('source revision')).toContainText(/^graph\.measure_observations: [0-9a-f]{64} over 3 row\(s\)/);
    await expect(page.getByText('none', { exact: true })).toBeVisible();
    // THE CERTIFIED METRIC in the executive view: served, its standing certified
    await openMetric(page, TITLE_EUR);
    await serve(page, 'executive');
    await expect(page.getByRole('heading', { name: /^Served — executive view · grain month/, level: 3 })).toBeVisible();
    await expect(page.getByLabel('serving standing')).toContainText('● certified');
    await expect(page.getByLabel('source revision')).toContainText(/over 3 row\(s\)/);
    await expect(page.getByRole('table', { name: 'served values' }).getByRole('cell', { name: '550000 EUR', exact: true })).toBeVisible();
    await expect(page.getByText(/committed — POL/).first()).toBeVisible();
  });
});
