/**
 * CP-6 B36 browser walk (part S; STAGES.csv B36 conditions (e) and (h)) — THE SCORE AND THE STRATEGY GRAPH COMPLETED through the real
 * interface on the gate's fresh database (the hosted form of e2e/phase6-b36-strategy.demo.spec.ts, which reads the demonstration and is not
 * run by this gate):
 *
 *   (h) /decisions/health — a second executive APPROVES the exception the executive requested (a recorded object, in force from the
 *   approval); the measure's OWNER restates its reading (the API: the owner-correction route) and the next current snapshot moves the
 *   dimension favourably → the change carries the OWNER-EDIT FLAG; the executive opens the page: the ACTIVE CONTEXT named, the input
 *   contract with each component's OWNER and the edit history, the flagged change, the exception APPROVED — in force and NAMED on the
 *   snapshot, then ACCEPTS the snapshot on the digest previewed → the approval line and its Ed25519 SIGNATURE (the key, the digest it binds,
 *   the bound action) as the server records them.
 *   (e) /graph/strategy/alignment — the planning lead reads the gap matrix (the objective set, its capability built and resourced) and the
 *   authority acts in force; the executive REVOKES the allocation from the page → "✕ REVOKED at … by …" on the act and, AT ONCE, the gap
 *   view's "no allocation approved by a human authority resources an initiative"; the "Detections raised by the schedule" list reads its
 *   honest empty state — the attention tick has raised none: the tick runs under the scheduler, off in this gate's API, and on demand only
 *   in the test runtime (the routed stale-measure detection is the harness's, apps/api/test/int/phase6-strategy-b36.test.ts S6, and the
 *   demonstration walk's).
 *
 * The seeding is the API's, in the Phase 1 idiom: this suite makes its own tenant, ONE domain and five DOMAIN principals with a per-run
 * password. The strategy objects rest on SYNTHETIC entity references (the gate seeds no graph); the measure is never observed (an observation
 * names a claim or evidence object the gate does not seed) — the owner's restatements are what the score reads, said on the page. The
 * refusals, GraphChanged on strategy changes, the lapsed act and the plan links are the harness's. The signing key is
 * EYE_EXECUTIVE_SIGNING_KEY_DEMO, generated by playwright.config.ts and bound in the API's process.
 *
 * The selectors are the pages' own (apps/web/app/decisions/health/page.tsx, apps/web/app/graph/strategy/alignment/page.tsx): the paragraph
 * "the active context"; the region "the health input contract"; "OWNER-EDIT FLAG"; the list "health exceptions" with #exn-<id> and "Approve
 * the exception"; the heading "The executive's acceptance of this snapshot", "approvals and signatures", #appr-note, "Accept and sign";
 * the alignment page's "Gap matrix" table, the section `acts-h` ("Authority acts and their revocation", #rv-<act>, "Revoke <kind>"), the
 * heading "Detections raised by the schedule".
 */
import { createHash } from 'node:crypto';
import { expect, test, type Locator, type Page } from '@playwright/test';

const API = 'http://localhost:3401';

function required(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`${name} must be provided (generated .eye-local/env or caller environment)`);
  return v;
}
const BOOTSTRAP_PW = required('EYE_TEST_BOOTSTRAP_PASSWORD');
const ADMIN_PW = required('EYE_TEST_ADMIN_PASSWORD');
/** One per-run password for the principals this suite creates; it lives in the worker's memory only. */
const PW = `St36!${crypto.randomUUID()}`;
const run = Date.now().toString(36);
const DAY = 86_400_000;
const inDays = (d: number) => new Date(Date.now() + d * DAY).toISOString();

function jcs(v: unknown): string {
  if (v === null) return 'null';
  if (typeof v === 'boolean' || typeof v === 'number') return JSON.stringify(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(jcs).join(',')}]`;
  const o = v as Record<string, unknown>;
  return `{${Object.keys(o).filter((k) => o[k] !== undefined).sort()
    .map((k) => `${JSON.stringify(k)}:${jcs(o[k])}`).join(',')}}`;
}
const digest = (v: unknown) => createHash('sha256').update(jcs(v ?? {}), 'utf8').digest('hex');

async function api(path: string, over: Record<string, unknown>, payload: unknown = {}, token?: string): Promise<{ status: number; body: Record<string, unknown> }> {
  const envelope = {
    message_id: crypto.randomUUID(),
    scope: 'PLATFORM', tenant_id: null, domain_id: null,
    principal_id: 'anonymous', purpose_id: 'graph',
    action: 'x', side_effect_class: 'reversible', consequence_class: 'C2',
    object_type: 'OBJ', object_id: null, schema_version: 'v1',
    issued_at: new Date().toISOString(), clock_quality: 'trusted',
    correlation_id: crypto.randomUUID(), trace_id: 'e2e-b36s',
    ...over,
    payload_digest: digest(payload),
  };
  const res = await fetch(API + path, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...(token !== undefined ? { authorization: `Bearer ${token}` } : {}) },
    body: JSON.stringify({ envelope, payload }),
  });
  return { status: res.status, body: (await res.json()) as Record<string, unknown> };
}
async function loginApi(username: string, password: string) {
  return api('/v1/auth/login', { action: 'identity.session.create', object_type: 'SES', purpose_id: 'authentication' }, { username, password });
}
async function uiLogin(page: Page, username: string, password: string): Promise<void> {
  await page.goto('/login');
  await page.getByLabel('Username').fill(username);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.waitForURL(/\/admin/);
}

interface Ctx { token: string; principalId: string; username: string }
type Row = Record<string, unknown>;
let admin: Ctx; let lead: Ctx; let executive: Ctx; let exec2: Ctx; let dadmin: Ctx; let analyst: Ctx;
let T = ''; let D = '';
let OBJ = ''; let CAP = ''; let INI = ''; let RSC = ''; let MSR = ''; let RES = '';
let RES_ACT = ''; let EXCEPTION = '';
const OBJ_TITLE = `On-time delivery 95% (e2e ${run})`;
const CAP_TITLE = `Regensburg assembly (e2e ${run})`;
const MSR_TITLE = `On-time delivery rate (e2e ${run})`;

async function person(login: string, roleCode: string): Promise<Ctx> {
  const p = await api(`/v1/tenants/${T}/principals`,
    { action: 'identity.principal.create', scope: 'TENANT', tenant_id: T, object_type: 'PRN', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
    { kind: 'human', displayName: login, loginName: login, password: PW, roleCode, domainId: D }, admin.token);
  expect(p.status, `${login} (${roleCode}) created`).toBe(201);
  const l = await loginApi(login, PW);
  expect(l.status, `${login} signed in`).toBe(201);
  return { token: (l.body as { tokens: { accessToken: string } }).tokens.accessToken, principalId: (l.body as { principalId: string }).principalId, username: login };
}
/** A governed act of this suite's seeding, in the domain, as one of its people. */
const as = (who: Ctx, path: string, action: string, objectType: string, objectId: string | null, payload: unknown, purpose = 'graph', over: Record<string, unknown> = {}) =>
  api(`/v1/tenants/${T}/domains/${D}${path}`, { action, scope: 'DOMAIN', tenant_id: T, domain_id: D, object_type: objectType, object_id: objectId, principal_id: `principal:${who.principalId}`, purpose_id: purpose, ...over }, payload, who.token);
const ok = (r: { status: number; body: Record<string, unknown> }, what: string, status = 201) => { expect(r.status, `${what}: ${JSON.stringify(r.body).slice(0, 400)}`).toBe(status); return r.body; };
const read = (who: Ctx, path: string, action: string, objectType: string, objectId: string | null, payload: unknown, purpose: string) =>
  as(who, path, action, objectType, objectId, payload, purpose, { side_effect_class: 'none', consequence_class: 'C1' });
const approveAll = (subjectDigest: string): Row => ({ subjectDigest, decision: 'approve', rationale: 'approved by the executive for the plan (e2e)', expiresAt: inDays(180) });
/** THE MODEL (SYNTHETIC; the B36 strategy harness's): one dimension over the objective; the measure and the four new classes; the window 2 days. */
const MODEL = (): Row => ({
  min_coverage: 0.3, change_points: 3, min_confidence: 0.5, owner_edit_window_days: 2,
  dimensions: [{ key: 'delivery', label: 'Delivery performance', weight: 1, objective_ids: [OBJ], bands: [{ key: 'healthy', min: 95 }, { key: 'watch', min: 70 }, { key: 'critical', min: 0 }] }],
  components: [
    { key: 'on_time', label: 'On-time delivery rate (SYNTHETIC)', dimension: 'delivery', input_kind: 'measure', input_id: MSR, weight: 0.5, direction: 'higher_better', normalisation: { worst: 50, best: 100 }, stale_after_days: 7 },
    { key: 'capability_cov', label: 'Capability coverage', dimension: 'delivery', input_kind: 'capability', input_id: OBJ, weight: 0.2, direction: 'higher_better', normalisation: { worst: 0, best: 100 }, stale_after_days: 365 },
    { key: 'quality', label: 'Input quality', dimension: 'delivery', input_kind: 'quality', input_id: OBJ, weight: 0.2, direction: 'higher_better', normalisation: { worst: 0, best: 100 }, stale_after_days: 365 },
    { key: 'execution', label: 'Commitments delivered', dimension: 'delivery', input_kind: 'execution', input_id: OBJ, weight: 0.05, direction: 'higher_better', normalisation: { worst: 0, best: 100 }, stale_after_days: 365 },
    { key: 'outcomes', label: 'Outcomes met', dimension: 'delivery', input_kind: 'outcome', input_id: OBJ, weight: 0.05, direction: 'higher_better', normalisation: { worst: 0, best: 100 }, stale_after_days: 365 },
  ],
});
const compute = async () => ok(await as(analyst, '/executive/health/compute', 'executive.health.compute', 'HSS', null, {}, 'executive'), 'the score computed');
const restate = async (value: number, reason: string) => ok(await as(lead, '/executive/health/inputs/set', 'executive.health.input.set', 'HSD', null, { component_key: 'on_time', value, reason }, 'executive'), `the owner restates ${value}`);

/* ───────────────────────── the pages' own selectors ───────────────────────── */
const section = (page: Page, id: string): Locator => page.locator(`section[aria-labelledby="${id}"]`);
const short8 = (id: string) => `${id.slice(0, 8)}…`;
async function openHealth(page: Page): Promise<void> {
  await page.goto('/decisions/health');
  await expect(page.getByRole('heading', { name: 'Strategic health', level: 1 })).toBeVisible();
}
async function openAlignment(page: Page): Promise<void> {
  await page.goto('/graph/strategy/alignment');
  await expect(page.getByRole('heading', { name: 'Strategy alignment', level: 1 })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Gap matrix' })).toBeVisible();
}
/** The gap row of the objective × capability of the scene. */
const gapRow = (page: Page): Locator => page.getByRole('row').filter({ has: page.getByRole('cell', { name: `${OBJ_TITLE} · set`, exact: true }) });

test.describe.configure({ mode: 'serial' });

test.describe('CP-6 B36 — the score and the Strategy Graph completed: /decisions/health (the owner, the flagged edit, the exception, the signed acceptance) and /graph/strategy/alignment (a revoked act seen at once)', () => {
  test.beforeAll(async () => {
    // Rotation-aware admin sign-in (ADR-P0-17).
    let al = await loginApi('platform-admin', ADMIN_PW);
    if (al.status !== 201 || (al.body as { rotationRequired?: boolean }).rotationRequired === true) {
      const boot = await loginApi('platform-admin', BOOTSTRAP_PW);
      expect(boot.status).toBe(201);
      const bt = (boot.body as { tokens: { accessToken: string }; principalId: string });
      if ((boot.body as { rotationRequired?: boolean }).rotationRequired === true) {
        const rot = await api('/v1/auth/rotate', { action: 'identity.credential.rotate', object_type: 'CRD', principal_id: `principal:${bt.principalId}`, purpose_id: 'authentication' },
          { currentPassword: BOOTSTRAP_PW, newPassword: ADMIN_PW }, bt.tokens.accessToken);
        expect(rot.status).toBe(201);
      }
      al = await loginApi('platform-admin', ADMIN_PW);
    }
    expect(al.status).toBe(201);
    admin = { token: (al.body as { tokens: { accessToken: string } }).tokens.accessToken, principalId: (al.body as { principalId: string }).principalId, username: 'platform-admin' };
    const t = await api('/v1/platform/tenants', { action: 'tenancy.tenant.create', object_type: 'TEN', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
      { name: `E2E B36 Strategy ${run}`, residencyProfile: 'EU' }, admin.token);
    expect(t.status).toBe(201);
    T = (t.body as { tenant: { id: string } }).tenant.id;
    const d = await api(`/v1/tenants/${T}/domains`, { action: 'tenancy.domain.create', scope: 'TENANT', tenant_id: T, object_type: 'CID', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
      { name: `B36 Strategy ${run}` }, admin.token);
    expect(d.status).toBe(201);
    D = (d.body as { domain: { id: string } }).domain.id;
    // FIVE people: the planning lead (declares the scene, owns the measure), the executive (the authority acts, the definition, the exception
    // request, the signed acceptance), a second executive (approves the exception: never the requester), the domain administrator (approves
    // the definition: two people), an analyst (computes the score).
    lead = await person(`s36-lead-${run}`, 'strategy_owner');
    executive = await person(`s36-exec-${run}`, 'executive');
    exec2 = await person(`s36-exec2-${run}`, 'executive');
    dadmin = await person(`s36-dadmin-${run}`, 'domain_admin');
    analyst = await person(`s36-analyst-${run}`, 'domain_analyst');
    // THE SCENE (the harness's S0): the objective, its capability built by an initiative and resourced, its measure — on SYNTHETIC entity references.
    const declare = async (objectType: string, title: string) => {
      const r = ok(await as(lead, '/graph/strategy/declare', 'graph.strategy.declare', objectType, null,
        { objectType, title, statement: `${title} (e2e, SYNTHETIC)`, status: 'active', restsOn: [{ kind: 'entity', id: crypto.randomUUID(), rationale: 'SYNTHETIC entity reference (the browser gate seeds no graph)' }] }), `${objectType} declared`);
      return (r as { strategy: { objectId: string } }).strategy.objectId;
    };
    OBJ = await declare('OBJ', OBJ_TITLE);
    CAP = await declare('CAP', CAP_TITLE);
    INI = await declare('INI', `Dual-sourcing initiative (e2e ${run})`);
    RSC = await declare('RSC', `Bearings procurement budget (e2e ${run})`);
    MSR = await declare('MSR', MSR_TITLE);
    const align = async (kind: string, from: string, to: string) => {
      const r = ok(await as(lead, '/graph/strategy/alignments/declare', 'graph.alignment.declare', 'ALN', null,
        { kind, from, to, strength: 'strong', rationale: `the ${kind} alignment of the scene (e2e)` }), `${kind} declared`);
      return (r as { alignment: { alignment_id: string; digest: string } }).alignment;
    };
    await align('supports', OBJ, CAP);
    await align('builds', INI, CAP);
    const res = await align('resources', RSC, INI);
    RES = res.alignment_id;
    const m = ok(await as(lead, `/graph/strategy/measures/${MSR}/define`, 'graph.measure.define', 'MSR', MSR,
      { objectiveId: OBJ, unit: 'percent', direction: 'higher_better', targetValue: 95, targetDate: '2027-03-31', freshnessDays: 7 }), 'the measure defined');
    const msrDigest = (m as { measure: { definition_digest: string } }).measure.definition_digest;
    // THE HUMAN AUTHORITY (PR-37-003): the objective set on the digest read from the gap view, the measure approved, the allocation approved.
    const gaps = ok(await read(executive, '/graph/strategy/gaps', 'graph.strategy.alignment.read', 'OBJ', null, {}, 'graph'), 'the gap view read', 200);
    const row = ((gaps as { gaps: { rows: Array<{ objective_id: string; objective_subject: { digest: string } }> } }).gaps.rows).find((r) => r.objective_id === OBJ);
    expect(row, 'the objective has a gap row').toBeDefined();
    ok(await as(executive, `/graph/strategy/${OBJ}/authority`, 'graph.strategy.authority.act', 'OBJ', OBJ, { actKind: 'set_objective', ...approveAll(row!.objective_subject.digest) }), 'the objective set');
    ok(await as(executive, `/graph/strategy/measures/${MSR}/approve`, 'graph.strategy.authority.act', 'MSR', MSR, approveAll(msrDigest)), 'the measure approved');
    const alloc = ok(await as(executive, `/graph/strategy/${RES}/authority`, 'graph.strategy.authority.act', 'ALN', RES, { actKind: 'allocate_resource', ...approveAll(res.digest) }), 'the allocation approved');
    RES_ACT = (alloc as { act: { act_id: string } }).act.act_id;
    // THE DEFINITION — two people: proposed by the executive, approved by the administrator; the first snapshot; the exception REQUESTED by the executive.
    const p = ok(await as(executive, '/executive/health/definitions/propose', 'executive.health.definition.propose', 'HSD', null,
      { model: MODEL(), reason: 'the delivery model with the four new classes (e2e, SYNTHETIC)' }, 'executive'), 'the definition proposed');
    const defId = (p as { definition: { definition_id: string } }).definition.definition_id;
    ok(await as(dadmin, `/executive/health/definitions/${defId}/approve`, 'executive.health.definition.approve', 'HSD', defId, { note: 'reviewed with the supply chain lead (e2e)' }, 'executive'), 'the definition approved');
    await compute();
    const x = ok(await as(executive, '/executive/health/exceptions/request', 'executive.health.exception.request', 'HSX', null,
      { component_key: 'execution', kind: 'exclude', reason: 'no commitment item rests on the objective yet — the execution class is not measurable this quarter (e2e)', expires_at: inDays(30) }, 'executive'), 'the exception requested');
    EXCEPTION = (x as { exception: { exception_id: string } }).exception.exception_id;
  });

  test('1. exceptions as recorded objects: a second executive approves the exception the executive requested — APPROVED, in force', async ({ page }) => {
    await uiLogin(page, exec2.username, PW);
    await openHealth(page);
    const list = page.getByRole('list', { name: 'health exceptions' });
    const item = list.locator('li').filter({ hasText: 'execution excluded' });
    await expect(item).toContainText('execution excluded · requested — no effect until approved');
    await expect(item).toContainText(`requested by ${short8(executive.principalId)}`);
    await page.locator(`#exn-${EXCEPTION}`).fill('agreed: execution is excepted until the first commitment item (e2e)');
    await item.getByRole('button', { name: 'Approve the exception' }).click();
    await expect(item).toContainText('execution excluded · APPROVED — in force · until');
    await expect(item).toContainText(`approved by ${short8(exec2.principalId)}: agreed: execution is excepted until the first commitment item (e2e)`);
    await expect(item.getByRole('button', { name: 'Approve the exception' })).toHaveCount(0);
    // THE OWNER-CORRECTION ROUTE (the API: only the input's owner restates): down, then up — the favourable change carries the flag (the next test reads it)
    await compute();
    await restate(60, 'the late shipments counted again after the reclassification (e2e)');
    await compute();
    await restate(96, 'the Q3 on-time figure restated after the late shipments were reclassified (e2e)');
    await compute();
  });

  test('2. /decisions/health: the active context, the component\'s owner and the edit history, the OWNER-EDIT FLAG on the favourable change, the exception named, the snapshot accepted and SIGNED', async ({ page }) => {
    await uiLogin(page, executive.username, PW);
    await openHealth(page);
    // THE ACTIVE CONTEXT named (none set: the default, stated)
    await expect(page.getByLabel('the active context')).toContainText('Active context: no context set — the whole domain, horizon 90d');
    // THE INPUT CONTRACT: each component's OWNER derived from its input's own object; the measure's owner and the two edits; the owner's statement is what the score reads
    await expect(page.getByRole('heading', { name: 'The input contract — owners and edit history' })).toBeVisible();
    const contract = page.getByRole('region', { name: 'the health input contract' });
    const onTime = contract.getByRole('row').filter({ hasText: 'on_time' });
    await expect(onTime).toContainText(`owner ${short8(lead.principalId)} (the owner of MSR "${MSR_TITLE}") · 2 edit(s), last 60 → 96 (the owner's statement is what the score reads)`);
    await expect(onTime).toContainText('owner-stated');
    await expect(onTime).toContainText(`${short8(lead.principalId)} 60 → 96 at`);
    await expect(contract.getByRole('row').filter({ hasText: 'capability_cov' })).toContainText(`owner ${short8(lead.principalId)}`);
    await expect(page.getByLabel('the owner-edit analysis')).toContainText(`Owner edits: 2 in all, 1 flagged — ${short8(lead.principalId)} 2 edit(s), 1 flagged (on_time).`);
    // THE ANTI-GAMING MEASURE on the current snapshot's change: the favourable move carries the OWNER-EDIT FLAG (shown; it gates nothing)
    await expect(page.getByRole('heading', { name: 'Score changes raised by this snapshot' })).toBeVisible();
    await expect(page.getByText('OWNER-EDIT FLAG').first()).toBeVisible();
    await expect(page.getByText(/1 owner edit\(s\) inside the policy window before this favourable change \(counted against the owner; gating nothing\)/).first()).toBeVisible();
    // THE EXCEPTION in force, named on the snapshot
    await expect(page.getByRole('list', { name: 'health exceptions' })).toContainText('execution excluded · APPROVED — in force');
    await expect(page.getByLabel('exceptions in force')).toContainText('execution exclude (until');
    // THE SIGNED ACCEPTANCE: the digest previewed, the consequence, then the acceptance recorded and signed beyond the audit chain
    await expect(page.getByRole('heading', { name: "The executive's acceptance of this snapshot" })).toBeVisible();
    await expect(page.getByLabel('the consequence of accepting')).toContainText(/authorizes no action/);
    await expect(page.getByLabel('approvals and signatures')).toContainText('Not yet accepted. · not signed');
    await page.locator('#appr-note').fill('accepted as the basis for the Q4 review (e2e)');
    await page.getByRole('button', { name: 'Accept and sign' }).click();
    const line = page.getByLabel('approvals and signatures');
    await expect(line).toContainText(`accepted by ${short8(executive.principalId)} at`);
    await expect(line).toContainText('accepted as the basis for the Q4 review (e2e)');
    await expect(line).toContainText(new RegExp(`signed Ed25519 with key ed25519:[0-9a-f]{16} over [0-9a-f]{12}… by ${short8(executive.principalId)} \\(executive\\.health\\.snapshot\\.approve\\)`));
    await expect(page.getByText(/committed — POL/).first()).toBeVisible();
  });

  test('3. /graph/strategy/alignment: the gap matrix and the acts in force; the executive revokes the allocation from the page — REVOKED, the gap view sees it at once; the schedule\'s detections say their honest state', async ({ page }) => {
    await uiLogin(page, lead.username, PW);
    await openAlignment(page);
    await expect(gapRow(page)).toContainText(CAP_TITLE);
    await expect(gapRow(page).getByRole('cell', { name: 'none', exact: true })).toHaveCount(1); // no gap
    await expect(gapRow(page)).toContainText('1 active, 1 resourced');
    await expect(gapRow(page)).toContainText(`${MSR_TITLE}: approved`);
    const acts = section(page, 'acts-h');
    await expect(acts.getByRole('heading', { name: 'Authority acts and their revocation' })).toBeVisible();
    await expect(acts.getByRole('row').filter({ hasText: 'allocate_resource' })).toContainText(/● in force until/);
    await expect(acts.getByRole('row').filter({ hasText: 'set_objective' })).toContainText(/● in force until/);
    await expect(acts.getByRole('row').filter({ hasText: 'approve_measure' })).toContainText(/● in force until/);
    // the detections the SCHEDULE raises: none on this gate (no tick runs without the scheduler; on demand only in the test runtime) — said, not faked
    await expect(page.getByRole('heading', { name: 'Detections raised by the schedule' })).toBeVisible();
    await expect(page.getByText('The attention tick has raised no strategy detection yet.')).toBeVisible();
    await expect(page.getByRole('list', { name: 'detections raised by the schedule' })).toHaveCount(0);
    // THE REVOCATION (b): the issuer revokes the allocation from the page; the gap view sees it AT ONCE
    await uiLogin(page, executive.username, PW);
    await openAlignment(page);
    const allocation = section(page, 'acts-h').getByRole('row').filter({ hasText: 'allocate_resource' });
    await page.locator(`#rv-${RES_ACT}`).fill('the budget is withdrawn until the qualification run completes (e2e)');
    await allocation.getByRole('button', { name: 'Revoke allocate_resource' }).click();
    await expect(allocation).toContainText(`✕ REVOKED at`);
    await expect(allocation).toContainText(`by ${short8(executive.principalId)} — the budget is withdrawn until the qualification run completes (e2e)`);
    await expect(allocation.getByRole('button', { name: /^Revoke/ })).toHaveCount(0);
    await expect(gapRow(page)).toContainText('no allocation approved by a human authority resources an initiative');
    await expect(gapRow(page)).toContainText('1 active, 0 resourced');
    await expect(page.getByText(/committed — POL/).first()).toBeVisible();
  });
});
