/**
 * CP-6 B36 browser walk (part G; STAGES.csv B36 condition (m)) — THE GATE PANEL COMPLETED, through the real interface on the gate's fresh
 * database (the hosted form of e2e/phase6-b36-gates.demo.spec.ts, which reads the demonstration and is not run by this gate):
 *
 *   the APPROVER opens a proposed package: the AUTHORITY BANNER (the gate on version 1, no typed condition yet), the CONDITION BUILDER
 *   ("Approve only if…" — a typed date_before condition added and carried by the approval), the approval recorded → the gate's record: the
 *   approval "not signed", SIGNED by its approver → the server's "✓ VERIFIED — signed by … with ed25519:…", the ONE gate-state badge
 *   APPROVED, the condition evaluated (● HOLDS) on the banner, the DISTINCT ACTS offered →
 *   the EXECUTIVE, a member of the package's room, CHALLENGES from the page → the badge reads CHALLENGED — held, the challenge OPEN →
 *   the OWNER DISMISSES it with a note → CHALLENGE DISMISSED, the badge APPROVED again →
 *   the AUTHORITY PREVIEWS the consequences (● Would commit.) and COMMITS on the preview's digest → the decision committed → SIGNS the
 *   decision (✓ VERIFIED) → DISTRIBUTES the record in-app only (no local sink runs on this gate) → the distribution rows DELIVERED →
 *   RECUSED: on a second package the approver, who approved it, recuses with a reason → "RECUSED" beside the approval, the recusal line,
 *   the badge RECUSED — quorum re-evaluated →
 *   THE BOARD PAGE: a third package reserved for the board by the executive and proposed; the board member reads the card (reserved for
 *   the charter, quorum 2, no approval yet, the badge) and approves the digest through the board's own act → 1 live approval, the standing.
 *
 * The seeding is the API's, in the Phase 1 idiom (the B34 exposures walk's, the memory walk's): this suite makes its own tenant, ONE domain
 * and thirteen DOMAIN principals with a per-run password. A choice binds the TWIN its outcome is observed on (0049), and a twin's boundary
 * names a resolved graph entity — so the gate walks the product's own path to one: an upload contract, one CSV record uploaded, an
 * extraction method (replay) recording an ENTITY claim, the extraction, the resolver run by the domain administrator (an unmatched
 * mention creates the entity, proposed), the resolution ACCEPTED by a resolution manager, the twin declared on that entity by its owner.
 * The packages then rest on it (two UNSIMULATED options with their reason — this gate runs no simulation); the OBJ and the DEC are declared
 * on a synthetic entity reference; the room on the package is the owner's. The refusals, the
 * PDP denials, the board's refusals of a standard package, the fields and the uniform state across kinds are the harness's
 * (apps/api/test/int/phase6-gates-b36.test.ts). The signing key is EYE_EXECUTIVE_SIGNING_KEY_DEMO, generated by playwright.config.ts and
 * bound in the API's process; VERIFIED is the server's word, asserted as rendered. The SYNTHETIC channels (email / sms / teams) need the
 * local sinks, which the hosted job does not start: the distribution here is in_app only, said.
 *
 * The selectors are the pages' own (apps/web/app/decisions/page.tsx, gate-control.tsx, gate-completion.tsx, board/page.tsx): the package's
 * title button and its level-2 heading; the heading "The gate on version N"; the fieldset "Approve only if…" with "Condition kind",
 * "Condition expected", "Condition label", "Add condition"; "Approval rationale", "Approve this digest"; the heading "The gate's record",
 * data-testid="gate-state", the lists "approval signatures" / "challenges" / "distributions", the paragraph "decision signatures"; "Sign my
 * approval", "Sign the decision", "Reason", "Challenge this decision", "Recuse myself (voids my approval)", "Resolution note", "Dismiss the
 * challenge", "Preview the consequences", the section "Consequence preview", "Commit (decision.commit, C3)", "Distribute"; the board page's
 * card (its heading, the list "board approvals", #act-<pkg>, #why-<pkg>, "Approve this digest").
 */
import { createHash } from 'node:crypto';
import { expect, test, type Locator, type Page } from '@playwright/test';

const API = 'http://localhost:3401';

function required(name: string): string {
  const v = process.env[name];
  if (!v) throw new Error(`${name} must be provided (generated .eye-local/env or caller environment)`);
  return v;
}
const BOOTSTRAP_PW = required('EYE_TEST_BOOTSTRAP_PASSWORD');
const ADMIN_PW = required('EYE_TEST_ADMIN_PASSWORD');
/** One per-run password for the principals this suite creates; it lives in the worker's memory only. */
const PW = `Gt36!${crypto.randomUUID()}`;
const run = Date.now().toString(36);

function jcs(v: unknown): string {
  if (v === null) return 'null';
  if (typeof v === 'boolean' || typeof v === 'number') return JSON.stringify(v);
  if (typeof v === 'string') return JSON.stringify(v);
  if (Array.isArray(v)) return `[${v.map(jcs).join(',')}]`;
  const o = v as Record<string, unknown>;
  return `{${Object.keys(o).filter((k) => o[k] !== undefined).sort()
    .map((k) => `${JSON.stringify(k)}:${jcs(o[k])}`).join(',')}}`;
}
const digest = (v: unknown) => createHash('sha256').update(jcs(v ?? {}), 'utf8').digest('hex');

async function api(path: string, over: Record<string, unknown>, payload: unknown = {}, token?: string): Promise<{ status: number; body: Record<string, unknown> }> {
  const envelope = {
    message_id: crypto.randomUUID(),
    scope: 'PLATFORM', tenant_id: null, domain_id: null,
    principal_id: 'anonymous', purpose_id: 'decision',
    action: 'x', side_effect_class: 'reversible', consequence_class: 'C2',
    object_type: 'DPK', object_id: null, schema_version: 'v1',
    issued_at: new Date().toISOString(), clock_quality: 'trusted',
    correlation_id: crypto.randomUUID(), trace_id: 'e2e-b36g',
    ...over,
    payload_digest: digest(payload),
  };
  const res = await fetch(API + path, {
    method: 'POST',
    headers: { 'content-type': 'application/json', ...(token !== undefined ? { authorization: `Bearer ${token}` } : {}) },
    body: JSON.stringify({ envelope, payload }),
  });
  return { status: res.status, body: (await res.json()) as Record<string, unknown> };
}
async function loginApi(username: string, password: string) {
  return api('/v1/auth/login', { action: 'identity.session.create', object_type: 'SES', purpose_id: 'authentication' }, { username, password });
}
async function uiLogin(page: Page, username: string, password: string): Promise<void> {
  await page.goto('/login');
  await page.getByLabel('Username').fill(username);
  await page.getByLabel('Password').fill(password);
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.waitForURL(/\/admin/);
}

interface Ctx { token: string; principalId: string; username: string }
let admin: Ctx; let lead: Ctx; let owner: Ctx; let approver: Ctx; let approver2: Ctx; let authority: Ctx; let executive: Ctx; let board1: Ctx;
let collector: Ctx; let xmanager: Ctx; let reader: Ctx; let resolver: Ctx; let twinOwner: Ctx;
let T = ''; let D = ''; let OBJ = ''; let DEC = ''; let ENTITY = ''; let TWIN = '';
const sha256 = (s: string) => createHash('sha256').update(s, 'utf8').digest('hex');
const CSV = 'strait,transits\nBab el-Mandeb Strait,41\n';
const MENTION = 'Bab el-Mandeb Strait';
let P1 = ''; let P2 = ''; let P3 = '';
const TITLE1 = `Reroute SYN-SHIP-4472 around the Cape (e2e ${run})`;
const TITLE2 = `Second bearing source (recusal, e2e ${run})`;
const TITLE3 = `Second source above the premium cap (board, e2e ${run})`;
const CHARTER = `The supervisory board (SYNTHETIC e2e ${run})`;

async function person(login: string, roleCode: string): Promise<Ctx> {
  const p = await api(`/v1/tenants/${T}/principals`,
    { action: 'identity.principal.create', scope: 'TENANT', tenant_id: T, object_type: 'PRN', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
    { kind: 'human', displayName: login, loginName: login, password: PW, roleCode, domainId: D }, admin.token);
  expect(p.status, `${login} (${roleCode}) created`).toBe(201);
  const l = await loginApi(login, PW);
  expect(l.status, `${login} signed in`).toBe(201);
  return { token: (l.body as { tokens: { accessToken: string } }).tokens.accessToken, principalId: (l.body as { principalId: string }).principalId, username: login };
}
/** A governed act of this suite's seeding, in the domain, as one of its people. */
const as = (who: Ctx, path: string, action: string, objectType: string, objectId: string | null, payload: unknown, purpose = 'decision') =>
  api(`/v1/tenants/${T}/domains/${D}${path}`, { action, scope: 'DOMAIN', tenant_id: T, domain_id: D, object_type: objectType, object_id: objectId, principal_id: `principal:${who.principalId}`, purpose_id: purpose }, payload, who.token);
const ok = (r: { status: number; body: Record<string, unknown> }, what: string, status = 201) => { expect(r.status, `${what}: ${JSON.stringify(r.body).slice(0, 400)}`).toBe(status); return r.body; };
/** The platform administrator acting in the domain (copied from the memory walk). */
const DOMAIN_ADMIN = (over: Record<string, unknown>) => ({ scope: 'DOMAIN', tenant_id: T, domain_id: D, principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration', ...over });

/**
 * Copied from the memory walk (which copied the retention walk, which copied the B16 harness's uploadContract — the browser gate cannot
 * import a test helper of apps/api): an upload connector under replay, synthetic data, rights CONFIRMED, ceiling INTERNAL, CSV.
 */
function uploadContract(sourceKey: string): Record<string, unknown> {
  return {
    source_key: sourceKey,
    name: 'E2E uploaded records (SYNTHETIC)',
    publisher: 'E2E plant (synthetic)',
    authority_class: 'authoritative',
    connector_kind: 'upload',
    acquisition_mode: 'replay',
    data_origin: 'synthetic',
    identity: { source_identity: sourceKey, publisher_identity: 'e2e (synthetic entity; does not exist)', endpoints: [], scheme_allowlist: ['https'],
                cadence_seconds: 86_400, jitter_seconds: 0, collection_window: null },
    authority_and_rights: {
      owner: 'observation.operations', steward: 'e2e', authority: 'Internal records (synthetic)', legal_basis: 'Internal synthetic data created for the browser gate',
      rights_state: 'confirmed', licence: 'internal', permitted_use: ['internal analysis'], robots_policy: 'not applicable', purposes: ['observation'],
      classification_ceiling: 'internal', residency: 'EU', retention: '24 months', deletion_obligation: 'none',
    },
    security_and_operations: {
      credential_ref: null,
      authentication_method: 'operator upload under an authenticated session',
      authenticity_method: {
        transport_endpoint: 'not applicable — no transport was performed by this system',
        byte_integrity: 'SHA-256 digest verified pre-store, post-store and on every read',
        source_origin: 'operator attestation only',
        content_authenticity: 'not applicable — the records are synthetic and marked as such at object level',
      },
      budgets: { max_requests_per_run: 25, max_bytes_per_run: 33_554_432, max_concurrency: 1, timeout_ms: 60_000, max_retries: 0 },
      expected_schema: { media_types: ['text/csv'], required_fields: [], drift_tolerance: 0, max_bytes: 16_777_216 },
      freshness_expectation: { threshold_seconds: 604_800, expected_interval: 'weekly' },
      coverage_expectations: {
        universe_version: 'v1', denominator_derivation: 'one upload set per reporting period', expected_items_per_window: null,
        not_applicable_dimensions: ['latency', 'correction_lag', 'authenticity'],
        not_applicable_reason: 'the records are synthetic internal data supplied by an operator: there is no publisher to lag behind, no corrections channel, and no external origin to authenticate',
      },
      correction_channel: 'a corrected upload supplied by the operator',
      replay_set: 'e2e-uploads',
    },
    lifecycle: { contract_version: 1, effective_from: '2024-01-01T00:00:00Z', effective_to: null },
  };
}

/**
 * THE ENTITY AND THE TWIN a choice binds (0049: an outcome is observed on a twin the choice names; 0032: a twin's boundary names a
 * resolved graph entity) — the product's own path, every step a governed request: the upload contract registered by the administrator,
 * approved and activated by the collection manager; one CSV record uploaded; the extraction method (replay) registered by the reader,
 * approved and activated by the extraction manager; the ENTITY claim recorded and extracted from the record; the resolver run by the
 * domain administrator — the unmatched mention creates the entity, proposed; the resolution accepted by the resolution manager (never the
 * proposer); the twin declared on that entity by its owner.
 */
async function seedTwin(): Promise<void> {
  const X = `/v1/tenants/${T}/domains/${D}`;
  const IN = (who: Ctx, over: Record<string, unknown>) => ({ scope: 'DOMAIN', tenant_id: T, domain_id: D, principal_id: `principal:${who.principalId}`, ...over });
  const sourceKey = `e2e-b36-gates-uploads-${run}`;
  const reg = ok(await api(`${X}/observation/sources/register`, DOMAIN_ADMIN({ action: 'observation.source.register', object_type: 'SRC', purpose_id: 'observation' }), { contract: uploadContract(sourceKey) }, admin.token), 'the upload contract registered');
  const sourceId = (reg as { source: { sourceId: string } }).source.sourceId;
  ok(await api(`${X}/observation/sources/${sourceId}/approve`, IN(collector, { action: 'observation.source.approve', object_type: 'SRC', object_id: sourceId, purpose_id: 'observation' }),
    { contractVersion: 1, decision: 'approve', reason: 'the e2e upload contract reviewed' }, collector.token), 'the upload contract approved');
  ok(await api(`${X}/observation/sources/${sourceId}/transition`, IN(collector, { action: 'observation.source.transition', object_type: 'SRC', object_id: sourceId, purpose_id: 'observation' }),
    { contractVersion: 1, target: 'active', reason: 'the e2e upload contract: active' }, collector.token), 'the upload contract active');
  ok(await api(`${X}/observation/agents/register`, DOMAIN_ADMIN({ action: 'observation.agent.register', object_type: 'AGT', purpose_id: 'observation' }), { sourceId, connector: 'upload', ownerPrincipalId: collector.principalId }, admin.token), 'the upload agent registered');
  const up = ok(await api(`${X}/observation/upload`, IN(collector, { action: 'observation.run.trigger', object_type: 'RUN', purpose_id: 'observation' }),
    { sourceId, contractVersion: 1, files: [{ filename: 'e2e-b36-gates.csv', mediaType: 'text/csv', base64: Buffer.from(CSV, 'utf8').toString('base64'), documentTime: '2024-01-14T00:00:00Z' }] }, collector.token), 'the record uploaded');
  expect((up as { run: { state: string; admitted: number } }).run, 'the upload run').toMatchObject({ state: 'finished', admitted: 1 });
  const ev = ok(await api(`${X}/observation/evidence/list`, IN(collector, { action: 'observation.read.evidence', object_type: 'EVD', side_effect_class: 'none', purpose_id: 'observation' }), { sourceId, limit: 5 }, collector.token), 'the evidence listed');
  const evd = (ev as { evidence: Array<{ object_id: string; payload: { locator: string; content_digest: string } }> }).evidence[0];
  expect(evd, 'one admitted record').toBeDefined();
  // THE METHOD (replay) and the recorded ENTITY claim: the strait named in the record, a place
  const methodKey = `e2e-b36-gates-entities-${run}`;
  const weightsDigest = sha256('e2e-weights');
  const decoding = { temperature: 0, top_p: 1, seed: 1, num_predict: 128 };
  const mreg = ok(await api(`${X}/intelligence/methods/register`, IN(reader, { action: 'intelligence.method.register', object_type: 'MTH', purpose_id: 'intelligence' }),
    { methodKey, name: 'E2E B36 entity mentions', sourceId, targetTypes: ['ENT'], gatewayMode: 'replay', modelId: 'e2e-fixture-model', modelWeightsDigest: weightsDigest, runtimeVersion: 'fixture/1',
      promptRef: 'extract/e2e-b36-entities', promptVersion: 'v1', promptText: 'Return the entity mentions of the e2e record as JSON claims.', decoding, confidenceFloor: 0.35, reviewBelow: 0.75, budgetCalls: 5, budgetSeconds: 60 }, reader.token), 'the method registered');
  const method = (mreg as { method: { methodId: string; promptDigest: string; decodingDigest: string } }).method;
  ok(await api(`${X}/intelligence/methods/${method.methodId}/approve`, IN(xmanager, { action: 'intelligence.method.approve', object_type: 'MTH', object_id: method.methodId, purpose_id: 'intelligence' }), { reason: 'the e2e method reviewed for the B36 gates walk' }, xmanager.token), 'the method approved');
  ok(await api(`${X}/intelligence/methods/${method.methodId}/transition`, IN(xmanager, { action: 'intelligence.method.activate', object_type: 'MTH', object_id: method.methodId, purpose_id: 'intelligence' }), { target: 'active', reason: 'the e2e method: active for the B36 gates walk' }, xmanager.token), 'the method activated');
  const requestDigest = digest({
    prompt_ref: 'extract/e2e-b36-entities', prompt_version: 'v1', prompt_digest: method.promptDigest,
    model_id: 'e2e-fixture-model', weights_digest: weightsDigest, runtime_version: 'fixture/1', decoding_digest: method.decodingDigest,
    input: { instruction: 'extract/e2e-b36-entities', target_types: ['ENT'], source_key: methodKey, item_key: evd!.payload.locator, evidence_digest: evd!.payload.content_digest, evidence: CSV },
  });
  const start = CSV.indexOf(MENTION);
  ok(await api(`${X}/intelligence/gateway/record`, IN(xmanager, { action: 'intelligence.gateway.call', object_type: 'GWC', purpose_id: 'intelligence' }),
    { recordings: [{ requestDigest, response: { claims: [{ claim_kind: 'entity', subject: MENTION, predicate: 'is_a', object_value: 'strait', confidence: 0.9, byte_start: start, byte_end: start + MENTION.length, qualifiers: { entity_type: 'place' } }] },
      modelId: 'e2e-fixture-model', runtimeVersion: 'fixture/1' }] }, xmanager.token), 'the response recorded');
  const ex = ok(await api(`${X}/intelligence/extract`, IN(xmanager, { action: 'intelligence.claim.admit', object_type: 'CLM', purpose_id: 'intelligence' }), { methodId: method.methodId, limit: 5 }, xmanager.token), 'the extraction');
  expect((ex as { extraction: { state: string; claimsAdmitted: number } }).extraction, 'the entity claim admitted from the recording').toMatchObject({ state: 'completed', claimsAdmitted: 1 });
  // THE RESOLVER (the domain administrator proposes): the unmatched mention creates the entity; THE DECISION (the resolution manager accepts)
  const rs = ok(await api(`${X}/graph/entities/resolve`, IN(admin, { action: 'graph.resolution.propose', object_type: 'RES', purpose_id: 'graph' }), { limit: 50, methodId: null }, admin.token), 'the resolver run');
  expect((rs as { resolution: { entitiesCreated: number } }).resolution.entitiesCreated, 'the mention created an entity').toBe(1);
  const queue = ok(await api(`${X}/graph/resolutions/queue`, IN(resolver, { action: 'graph.read', object_type: 'RES', side_effect_class: 'none', consequence_class: 'C1', purpose_id: 'graph' }), { limit: 50 }, resolver.token), 'the resolution queue read');
  const pending = ((queue as { queue: Array<Record<string, unknown>> }).queue ?? []).find((r) => r['mention_text'] === MENTION);
  expect(pending, `the proposed resolution of "${MENTION}": ${JSON.stringify(queue).slice(0, 300)}`).toBeDefined();
  ENTITY = String(pending!['entity_id']);
  ok(await api(`${X}/graph/resolutions/${String(pending!['resolution_id'])}/decide`, IN(resolver, { action: 'graph.resolution.decide', object_type: 'RES', object_id: String(pending!['resolution_id']), purpose_id: 'graph' }),
    { decision: 'accept', reason: 'the strait named in the uploaded record is the entity proposed (e2e)' }, resolver.token), 'the resolution accepted');
  // THE TWIN on that entity (the outcome of every choice below is observed on it; no version is opened: this gate runs no simulation)
  const tw = ok(await api(`${X}/twins/declare`, IN(twinOwner, { action: 'twin.declare', object_type: 'TWN', purpose_id: 'twin' }),
    { kind: 'supply-chain', title: `NORDWERK — Ningbo → Regensburg chain (e2e ${run})`, statement: 'the magnet chain (e2e, SYNTHETIC)', boundary: [ENTITY], owner: twinOwner.principalId,
      behaviourModelRef: 'supply-flow@1', validation: { status: 'unvalidated (synthetic grounding)', limitations: ['calendar days'] } }, twinOwner.token), 'the twin declared');
  TWIN = (tw as { twin: { twinId: string } }).twin.twinId;
}

/** A full draft on a fresh package of the owner's: two UNSIMULATED options (the gate runs no simulation), the terms, the choice — then proposed. */
async function proposedPackage(title: string, approverPolicy: Record<string, unknown>, propose = true): Promise<{ pkg: string; v: number; digest: string | null }> {
  const d = ok(await as(owner, '/decisions/declare', 'decision.package.declare', 'DPK', null,
    { decisionObjectId: DEC, title, statement: 'whether to reroute the second magnet shipment now (e2e, SYNTHETIC)', owner: owner.principalId }), 'the package declared');
  const pkg = (d as { package: { packageId: string } }).package.packageId;
  const o = ok(await as(owner, `/decisions/${pkg}/versions/open`, 'decision.package.version', 'DPK', pkg, { knownAt: new Date().toISOString(), observedThrough: '2024-01-17' }), 'the version opened');
  const v = (o as { version: { version: number } }).version.version;
  ok(await as(owner, `/decisions/${pkg}/versions/${v}/options`, 'decision.package.option', 'DPK', pkg,
    { key: 'status-quo', title: 'Do nothing', kind: 'status_quo', consequences: [], unsimulatedReason: 'the browser gate seeds no twin and no run: doing nothing is not simulated here (e2e)', risks: [], opportunities: [] }), 'the status quo option');
  ok(await as(owner, `/decisions/${pkg}/versions/${v}/options`, 'decision.package.option', 'DPK', pkg,
    { key: 'reroute', title: 'Reroute via the Cape', kind: 'intervention', consequences: [], unsimulatedReason: 'the browser gate seeds no twin and no run: the reroute is not simulated here (e2e)', risks: ['+14 days of transit'], opportunities: [] }), 'the intervention option');
  ok(await as(owner, `/decisions/${pkg}/versions/${v}/terms`, 'decision.package.terms', 'DPK', pkg,
    { objectives: [OBJ], constraints: ['no air freight above 60 t/week'], approverPolicy, monitoringConditions: [{ kind: 'review', every_days: 7, owner: owner.principalId }],
      reversibility: 'reversible within one sailing', informationValue: 'a week of observation would not change the ranking' }), 'the terms');
  ok(await as(owner, `/decisions/${pkg}/versions/${v}/choice`, 'decision.package.choice', 'DPK', pkg,
    { option_key: 'reroute', rationale: 'The reroute is the only option that keeps the line running without the air-bridge premium (e2e).', decision_deadline: '2030-01-19',
      accepted_trade_offs: ['+14 days of transit', '+48,100 reroute cost'], action_owner: owner.principalId,
      outcome_criteria: [{ key: 'line_stop_days', quantity: 'line stop days over the horizon', unit: 'days', target: 0, comparator: '<=', by: '2030-04-10', observed_on: 'twin:outcome.line_stop_days:SYN-LINE-A1', twin_id: TWIN, period: { from: '2030-01-11', to: '2030-04-10' } }] }), 'the choice');
  if (!propose) return { pkg, v, digest: null };
  const pr = ok(await as(owner, `/decisions/${pkg}/versions/${v}/propose`, 'decision.package.propose', 'DPK', pkg, {}), 'the proposal');
  return { pkg, v, digest: (pr as { proposal: { versionDigest: string } }).proposal.versionDigest };
}

/* ───────────────────────── the page's own selectors ───────────────────────── */
async function openPackage(page: Page, title: string): Promise<void> {
  await page.goto('/decisions');
  await expect(page.getByRole('heading', { name: 'Decisions', level: 1 })).toBeVisible();
  await page.getByRole('button', { name: title, exact: true }).click();
  await expect(page.getByRole('heading', { name: title, level: 2 })).toBeVisible();
  await expect(page.getByRole('heading', { name: /^The gate's record/ })).toBeVisible();
}
const record = (page: Page): Locator => page.locator('div[aria-labelledby="gate-b36-h"]');
const banner = (page: Page): Locator => page.locator('div[aria-labelledby="gate-h"]');
const badge = (page: Page): Locator => record(page).getByTestId('gate-state');
const short8 = (id: string) => `${id.slice(0, 8)}…`;

test.describe.configure({ mode: 'serial' });

test.describe('CP-6 B36 — the gate panel completed: the condition builder, the banner, the acts, the signature, a challenge and its resolution, the preview, RECUSED, the board page', () => {
  test.beforeAll(async () => {
    // Rotation-aware admin sign-in (ADR-P0-17).
    let al = await loginApi('platform-admin', ADMIN_PW);
    if (al.status !== 201 || (al.body as { rotationRequired?: boolean }).rotationRequired === true) {
      const boot = await loginApi('platform-admin', BOOTSTRAP_PW);
      expect(boot.status).toBe(201);
      const bt = (boot.body as { tokens: { accessToken: string }; principalId: string });
      if ((boot.body as { rotationRequired?: boolean }).rotationRequired === true) {
        const rot = await api('/v1/auth/rotate', { action: 'identity.credential.rotate', object_type: 'CRD', principal_id: `principal:${bt.principalId}`, purpose_id: 'authentication' },
          { currentPassword: BOOTSTRAP_PW, newPassword: ADMIN_PW }, bt.tokens.accessToken);
        expect(rot.status).toBe(201);
      }
      al = await loginApi('platform-admin', ADMIN_PW);
    }
    expect(al.status).toBe(201);
    admin = { token: (al.body as { tokens: { accessToken: string } }).tokens.accessToken, principalId: (al.body as { principalId: string }).principalId, username: 'platform-admin' };
    const t = await api('/v1/platform/tenants', { action: 'tenancy.tenant.create', object_type: 'TEN', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
      { name: `E2E B36 Gates ${run}`, residencyProfile: 'EU' }, admin.token);
    expect(t.status).toBe(201);
    T = (t.body as { tenant: { id: string } }).tenant.id;
    const d = await api(`/v1/tenants/${T}/domains`, { action: 'tenancy.domain.create', scope: 'TENANT', tenant_id: T, object_type: 'CID', principal_id: `principal:${admin.principalId}`, purpose_id: 'platform.administration' },
      { name: `B36 Gates ${run}` }, admin.token);
    expect(d.status).toBe(201);
    D = (d.body as { domain: { id: string } }).domain.id;
    // THIRTEEN people: the planner who declares the objective and the decision, the package owner, two approvers, the committing authority,
    // the executive (a member of the room — the challenger), a board member (PER-01).
    lead = await person(`g36-lead-${run}`, 'strategy_owner');
    owner = await person(`g36-owner-${run}`, 'decision_owner');
    approver = await person(`g36-approver-${run}`, 'decision_approver');
    approver2 = await person(`g36-approver2-${run}`, 'decision_approver');
    authority = await person(`g36-authority-${run}`, 'decision_authority');
    executive = await person(`g36-exec-${run}`, 'executive');
    board1 = await person(`g36-board-${run}`, 'board_member');
    // ... and the five who walk the product's path to the twin a choice binds: the collection manager, the extraction manager, the reader,
    // the resolution manager, the twin's owner.
    collector = await person(`g36-collector-${run}`, 'collection_manager');
    xmanager = await person(`g36-xmanager-${run}`, 'extraction_manager');
    reader = await person(`g36-reader-${run}`, 'domain_analyst');
    resolver = await person(`g36-resolver-${run}`, 'resolution_manager');
    twinOwner = await person(`g36-twin-owner-${run}`, 'twin_owner');
    await seedTwin();
    // THE STRATEGY OBJECTS the packages rest on — on a SYNTHETIC entity reference (the browser gate seeds no graph; nothing asserts on it).
    const declare = async (objectType: string, title: string, restsOn: unknown[]) => {
      const r = ok(await as(lead, '/graph/strategy/declare', 'graph.strategy.declare', objectType, null,
        { objectType, title, statement: `${title} (e2e, SYNTHETIC)`, restsOn }, 'graph'), `${objectType} declared`);
      return (r as { strategy: { objectId: string } }).strategy.objectId;
    };
    OBJ = await declare('OBJ', `Keep the Regensburg line running through Q1 (e2e ${run})`, [{ kind: 'entity', id: crypto.randomUUID(), rationale: 'SYNTHETIC entity reference (the browser gate seeds no graph)' }]);
    DEC = await declare('DEC', `Routing of SYN-SHIP-4472 (e2e ${run})`, [{ kind: 'strategy', id: OBJ, rationale: 'the decision serves the objective' }]);
    // P1: proposed, the approver named by the policy; its ROOM with the executive as a member (the challenger's standing).
    const p1 = await proposedPackage(TITLE1, { quorum: 1, principals: [approver.principalId], expires_after_days: 14 });
    P1 = p1.pkg;
    const room = ok(await as(owner, '/rooms/open', 'room.open', 'DRM', null, { packageId: P1, title: `Reroute decision room (e2e ${run})`, reviewEveryDays: 7 }), 'the room opened');
    const roomId = (room as { room: { roomId: string } }).room.roomId;
    ok(await as(owner, `/rooms/${roomId}/membership`, 'room.membership', 'DRM', roomId, { principal: executive.principalId, role: 'observer', op: 'add' }), 'the executive a member');
    // P2: proposed and APPROVED by the API (the recusal is the page's act); the policy admits either approver.
    const p2 = await proposedPackage(TITLE2, { quorum: 1, principals: [approver.principalId, approver2.principalId], expires_after_days: 14 });
    P2 = p2.pkg;
    ok(await as(approver, `/decisions/${P2}/versions/${p2.v}/approve`, 'decision.approve', 'APR', null,
      { decision: 'approve', versionDigest: p2.digest, rationale: 'The second source removes the single point of failure (e2e).' }), 'P2 approved');
    // P3: a draft RESERVED for the board by the executive (0090 §G6), then proposed — the board page's card.
    const p3 = await proposedPackage(TITLE3, { quorum: 2, roles: ['board_member'], expires_after_days: 14 }, false);
    P3 = p3.pkg;
    ok(await as(executive, `/decisions/${P3}/board/reserve`, 'decision.board.reserve', 'DPK', P3,
      { board: { charter: CHARTER, quorum: 2 }, rationale: 'A second source above the premium cap is the board\'s (e2e).' }), 'P3 reserved for the board');
    ok(await as(owner, `/decisions/${P3}/versions/${p3.v}/propose`, 'decision.package.propose', 'DPK', P3, {}), 'P3 proposed');
  });

  test('1. the approver: the authority banner, the condition builder, the approval on the digest, the signature VERIFIED, the ONE gate-state badge, the distinct acts', async ({ page }) => {
    await uiLogin(page, approver.username, PW);
    await openPackage(page, TITLE1);
    // THE AUTHORITY BANNER (HX-09): the gate on version 1, no typed condition yet, the badge REVIEW REQUESTED on the record
    await expect(page.getByRole('heading', { name: /^The gate on version 1/ })).toBeVisible();
    await expect(banner(page)).toContainText('no typed approval condition');
    await expect(badge(page)).toContainText('REVIEW REQUESTED');
    await expect(record(page).getByRole('list', { name: 'approval signatures' })).toContainText('no approval on this version');
    // THE DISTINCT ACTS (HX-12): each its own recorded action
    await expect(page.getByLabel('Gate act (each is its own recorded action)')).toBeVisible();
    // THE CONDITION BUILDER: a typed date_before condition, carried by the approval
    await expect(page.getByText(/^Approve only if… \(0 condition\(s\)\)/)).toBeVisible();
    await page.getByLabel('Condition kind').selectOption('date_before');
    await page.getByLabel('Condition expected').fill('2030-01-01');
    await page.getByLabel('Condition label').fill('only if decided before 2030');
    await page.getByRole('button', { name: 'Add condition' }).click();
    await expect(page.getByText(/^Approve only if… \(1 condition\(s\)\)/)).toBeVisible();
    await page.getByLabel('Approval rationale').fill('The reroute keeps the line running; the premium is acceptable (e2e).');
    await page.getByRole('button', { name: 'Approve this digest' }).click();
    // THE RECORD after the approval: the approval by its approver, not signed; the badge APPROVED
    const approvals = record(page).getByRole('list', { name: 'approval signatures' });
    await expect(approvals).toContainText(`approval by ${short8(approver.principalId)} (approve)`);
    await expect(approvals).toContainText('not signed');
    await expect(badge(page)).toContainText('APPROVED');
    // the banner now evaluates the condition: it holds
    await expect(banner(page)).toContainText('1 approval condition(s), 0 failing now');
    await expect(banner(page)).toContainText(/“only if decided before 2030” \(before 2030-01-01T00:00:00(\.000)?Z\) — ● HOLDS/);
    // THE SIGNATURE beyond the audit chain (k1): the approver signs the approval's header digest; the server verifies it
    await approvals.getByRole('button', { name: 'Sign my approval' }).click();
    await expect(approvals).toContainText(new RegExp(`✓ VERIFIED — signed by ${short8(approver.principalId)} with ed25519:[0-9a-f]{16}`));
    await expect(approvals).not.toContainText('not signed');
    await expect(record(page)).toContainText(/this deployment signs with ed25519:[0-9a-f]{16}/);
    await expect(record(page).getByText(/committed — POL/)).toBeVisible();
  });

  test('2. a challenge as a transition: the executive (a room member) challenges from the page — CHALLENGED, held; the owner dismisses it — APPROVED again', async ({ page }) => {
    await uiLogin(page, executive.username, PW);
    await openPackage(page, TITLE1);
    await record(page).getByLabel('Reason').fill('The second source was never audited (e2e).');
    await record(page).getByRole('button', { name: 'Challenge this decision' }).click();
    const challenges = record(page).getByRole('list', { name: 'challenges' });
    await expect(challenges).toContainText('CHALLENGE OPEN — the commitment is held');
    await expect(challenges).toContainText(`by ${short8(executive.principalId)} (member)`);
    await expect(badge(page)).toContainText('CHALLENGED — held');
    // THE RESOLUTION: the owner, never the challenger, dismisses with a note
    await uiLogin(page, owner.username, PW);
    await openPackage(page, TITLE1);
    await expect(badge(page)).toContainText('CHALLENGED — held');
    await record(page).getByLabel('Resolution note').fill('The audit report is on file (e2e).');
    await record(page).getByRole('button', { name: 'Dismiss the challenge' }).click();
    await expect(record(page).getByRole('list', { name: 'challenges' })).toContainText('CHALLENGE DISMISSED');
    await expect(record(page).getByRole('list', { name: 'challenges' })).toContainText(`resolved by ${short8(owner.principalId)}`);
    await expect(badge(page)).toContainText('APPROVED');
  });

  test('3. the authority: the PREVIEW and the commit on its digest; the decision SIGNED (VERIFIED); the record DISTRIBUTED in-app (no sink on this gate)', async ({ page }) => {
    await uiLogin(page, authority.username, PW);
    await openPackage(page, TITLE1);
    await page.getByRole('button', { name: 'Preview the consequences' }).click();
    const preview = page.getByRole('region', { name: 'Consequence preview' });
    await expect(preview).toContainText('● Would commit.');
    await expect(preview).toContainText(/Residual risk: 0 failing condition\(s\)/);
    await preview.getByRole('button', { name: 'Commit (decision.commit, C3)' }).click();
    await expect(page.getByText(/^■ COMMITTED under/)).toBeVisible();
    // THE DECISION SIGNED after its commitment (k1): by the committing authority
    const decision = record(page).getByLabel('decision signatures');
    await expect(decision).toContainText(`committed`);
    await expect(decision).toContainText('not signed yet');
    await record(page).getByRole('button', { name: 'Sign the decision' }).click();
    await expect(decision).toContainText(new RegExp(`✓ VERIFIED — signed by ${short8(authority.principalId)} with ed25519:[0-9a-f]{16}`));
    await expect(record(page).getByRole('button', { name: 'Sign the decision' })).toHaveCount(0);
    // THE DISTRIBUTION (k2): to the room — the owner and the executive — in-app only (the SYNTHETIC channels need the local sinks the hosted job does not start)
    await expect(record(page)).toContainText('email / SMS / Teams are SYNTHETIC');
    await record(page).getByRole('button', { name: 'Distribute', exact: true }).click();
    await expect(page.getByRole('status').filter({ hasText: /^distributed — \d+ row\(s\): in_app delivered/ })).toBeVisible();
    // the room's two people (the owner, the executive member) each reached in-app with a receipt — nothing SYNTHETIC on this gate
    const dist = record(page).getByRole('list', { name: 'distributions' });
    await expect(dist.getByText(/via in_app: DELIVERED/)).toHaveCount(2);
    await expect(dist.getByText(/SYNTHETIC/)).toHaveCount(0);
  });

  test('4. RECUSED: the approver who approved the second package recuses with a reason — the approval voided, the recusal line, the badge RECUSED', async ({ page }) => {
    await uiLogin(page, approver.username, PW);
    await openPackage(page, TITLE2);
    await expect(badge(page)).toContainText('APPROVED');
    await record(page).getByLabel('Reason').fill('A family member works for the second source (e2e).');
    await record(page).getByRole('button', { name: 'Recuse myself (voids my approval)' }).click();
    const approvals = record(page).getByRole('list', { name: 'approval signatures' });
    await expect(approvals).toContainText('RECUSED');
    await expect(approvals).toContainText('voided: recused: A family member works for the second source (e2e).');
    await expect(record(page)).toContainText(new RegExp(`Recusals: ${short8(approver.principalId)} recused at .* \\(A family member works for the second source \\(e2e\\)\\.; quorum 1, live 1 → 0; approved → under_review\\)`));
    await expect(badge(page)).toContainText('RECUSED — quorum re-evaluated');
    await expect(record(page).getByRole('button', { name: /^Recuse myself/ })).toHaveCount(0);
  });

  test('5. the board page: the board-class package with its charter, quorum and badge; the board member approves the digest through the board\'s own act', async ({ page }) => {
    await uiLogin(page, board1.username, PW);
    await page.goto('/decisions/board');
    await expect(page.getByRole('heading', { name: 'Board', level: 1 })).toBeVisible();
    const card = page.locator(`section[aria-labelledby="board-${P3}"]`);
    await expect(card.getByRole('heading', { name: new RegExp(`^${TITLE3.replace(/[()]/g, '\\$&')}`), level: 2 })).toBeVisible();
    await expect(card).toContainText(`reserved for ${CHARTER} · quorum 2 · 0 live approval(s) · package proposed · version 1 proposed`);
    await expect(card.getByTestId('gate-state')).toContainText('REVIEW REQUESTED');
    await expect(card.getByRole('list', { name: 'board approvals' })).toContainText('no approval yet');
    await expect(card).toContainText('A board member never decides a standard package; the server refuses it.');
    // THE BOARD ACT (decision.board.approve): on the digest read, with the rationale
    await expect(page.locator(`#act-${P3}`)).toHaveValue('approve');
    await page.locator(`#why-${P3}`).fill('The board approves the second source (e2e).');
    await card.getByRole('button', { name: 'Approve this digest' }).click();
    await expect(card).toContainText('quorum 2 · 1 live approval(s)');
    await expect(card.getByRole('list', { name: 'board approvals' })).toContainText(`${short8(board1.principalId)}: approve (live)`);
    await expect(card).toContainText('Your standing decision: approve.');
    await expect(page.getByText(/committed — POL/)).toBeVisible();
  });
});
