#!/usr/bin/env node
/**
 * CP-6 batch B13 on the demonstration (NORDWERK; eye_demo — or the rehearsal copy that EYE_DB_NAME and EYE_API name): the governed
 * SCHEDULE RETIREMENT and the customer export's DELIVERY — the package download, the destination and its receipt, the key-based
 * signature (migration 0073) — exercised by the personas through the REAL HTTP path, each scene stating the effect it produced on the
 * host and in the ledgers, what is DEMONSTRATION and what is PRODUCTION, and where nothing happened, saying so.
 *
 * PREPARED BY THE RUNNER, NOT BY THIS ACT (the header of the output restates it): the demonstration signing key generated by
 * `node scripts/retention/generate-demo-signing-key.mjs --public-out .eye-local/export-signing-demo.pub.pem >> .eye-local/env` (the
 * ONE env line appended to the 0600 handoff; the public key PEM written beside it), the transfer station's directory
 * `.eye-local/transfer-station-demo` created (outside the four vault roots), then `scripts/ops/demo-restart.sh --build` so the API
 * process binds the reference. The act reads the PUBLIC key from .eye-local/export-signing-demo.pub.pem (or EYE_DEMO_SIGNING_PUBLIC_PEM)
 * and the station root from EYE_DEMO_TRANSFER_STATION (default <repo>/.eye-local/transfer-station-demo); it never reads, prints or
 * records the private value — the product resolves the reference in ITS process, and nothing here needs it.
 *
 *   1. THE SCHEDULE RETIRED: the platform administrator retires 01a0a62a-a23b-739a-baf7-d49936d68b39 — the archive schedule the B12 act
 *      declared for the restore-window demonstration — with a reason; the row keeps its last_evaluation, the three actions it opened
 *      (two withdrawn, one verified) and their events are untouched; schedule.retired on the schedule ledger; an evaluation now opens
 *      nothing from it; tier/state shows it retired with its instant.
 *   2. THE DEMONSTRATION KEY: the platform administrator declares the tenant's signing key from the reference EYE_EXPORT_SIGNING_KEY_DEMO
 *      with purpose DEMONSTRATION — the key id, the public key PEM (public: printed and compared with the file the runner wrote), the
 *      list without the reference's value. Stated: production activation = a production key under the owner's custody, declared with
 *      purpose production, this one retired.
 *   3. THE DESTINATIONS: the platform administrator declares the transfer station `nordwerk-transfer-station` (the isolated synthetic
 *      destination — the disconnected-transfer path of the specification, ES-53-004 / NZ-20) and the https destination `nordwerk-exports`
 *      (the PRODUCTION kind) whose credential reference EYE_DST_NORDWERK is UNBOUND on this host → readiness blocked-credential.
 *   4. THE SIGNED EXPORT: P. Novák opens a customer export of the two hot NORDWERK internal records (ceiling internal, expiresAfter
 *      7 days), H. Bergmann approves on the scope digest, P. Novák executes — the package carries scheme eye-customer-export/2 with the
 *      key id, its archive digest and its expiry recorded — and verifies; the read route shows the signature and the public key.
 *   5. THE DOWNLOAD: P. Novák downloads the package (one deterministic ustar tar; its sha256 the recorded archive digest; the event
 *      export.downloaded on the action); the customer's verifier on the tar with the public key: PACKAGE OK, signature verified; on a
 *      copy with one byte flipped inside a .bin entry: FAILED. A. Hoffmann's download refused (not among the holders).
 *   6. THE DELIVERY to the transfer station: H. Bergmann delivers → delivered, attempt 1; the host: package.tar, package.sig and
 *      delivery.json under the station's <tenant>/<domain>/<action>/; custody.delivered per record; THE DEMONSTRATION RECIPIENT (the
 *      labelled script, never the product) verifies the package on its side with the public key and writes receipt.json; H. Bergmann
 *      collects the receipt → ACKNOWLEDGED: the exchange closed with the recipient's acknowledgement (DP-47-005); the receipt as recorded.
 *   7. THE PRODUCTION PATH'S GATE: H. Bergmann attempts the delivery to `nordwerk-exports` → recorded FAILED credential_unbound BEFORE
 *      any egress (the row, the event); stated: the activation step.
 *   8. THE REVOCATION: H. Bergmann revokes the package → the download refused, a further delivery refused; the deliveries stay recorded;
 *      stated: no notice reaches the destination (remaining).
 *   9. THE STATE: tier/state's schedules (the retired one), the keys, the destinations, the deliveries of the action.
 *
 * What the demonstration shows and what the harness alone proves is stated at the end. Idempotence: the retirement is skipped with a
 * note when the schedule is already retired; the key declaration reuses a listed active key whose reference is EYE_EXPORT_SIGNING_KEY_DEMO;
 * the destinations are reused by key when already declared; every run opens a NEW export. The act cleans nothing on the demonstration
 * (the station directory and its receipt stay as the demonstration's record; the downloaded tar goes to a scratch directory). The script
 * is an act, not a seed. Nothing here prints a credential.
 */
import { basename, dirname, join, resolve as resolvePath } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
import { loadLocalEnv } from '../local-env.mjs';
import { call, login, adminSession, demoScope, as, ok, bad, note, failureCount } from '../phase4/governed.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const pg = createRequire(join(ROOT, 'apps', 'api', 'package.json'))('pg');
const env = loadLocalEnv(ROOT);
const admin = await adminSession(env);
const scope = await demoScope(admin);
const { tenantId: T, domainId: D } = scope;
const PW = env.EYE_TEST_ADMIN_PASSWORD;
const X = `/v1/tenants/${T}/domains/${D}`; const R = `${X}/retention`;
const short = (id) => `${String(id).slice(0, 8)}…`;
const iso = (t) => (t === null || t === undefined ? '—' : new Date(t).toISOString());
const who = async (l) => { const s = await login(l, PW); if (s === null) { bad(`${l} could not authenticate`); process.exit(1); } return s; };
const novak = await who('p.novak'); const bergmann = await who('h.bergmann'); const hoffmann = await who('a.hoffmann'); const dvorak = await who('m.dvorak');
const pn = (over) => as(novak, scope, { purposeId: 'retention', ...over });
const hb = (over) => ({ scope: 'DOMAIN', tenantId: T, domainId: D, principalId: `principal:${bergmann.principalId}`, purposeId: 'retention', ...over });
const ah = (over) => as(hoffmann, scope, { purposeId: 'observation', ...over });
const cm = (over) => as(dvorak, scope, { purposeId: 'retention', ...over });
const adm = (over) => as(admin, scope, { purposeId: 'platform.administration', ...over });
const fail = (label, r) => bad(`${label}: ${r.status} ${r.body?.message ?? JSON.stringify(r.body).slice(0, 300)}`);
const su = new pg.Client({ host: env.EYE_DB_HOST ?? 'localhost', port: Number(env.EYE_DB_PORT ?? 5432), database: env.EYE_DB_NAME ?? 'eye_demo', user: env.EYE_DB_MIGRATE_USER ?? 'eye', password: env.EYE_DB_MIGRATE_PASSWORD });
await su.connect();
const q = async (text, params = []) => (await su.query(text, params)).rows;
// The vault roots AS THE API RESOLVES THEM (a relative root against the workspace root; an absolute EYE_VAULT_*_ROOT as it is).
const vaultRoot = (name) => resolvePath(ROOT, env[`EYE_VAULT_${name.toUpperCase()}_ROOT`] ?? `.eye-local/vault/${name}`);
const rel = (p) => p.replace(ROOT + '/', '');
const sha256 = (bytes) => createHash('sha256').update(bytes).digest('hex');
const sha256File = (p) => sha256(readFileSync(p));
const HEX64 = /^[0-9a-f]{64}$/;
/** A field of a row as the port spells it (snake_case), or as a controller answer spells it (camelCase) — the answers mix the two. */
const field = (o, k) => (o === null || o === undefined ? null : (o[k] ?? o[k.replace(/_([a-z])/g, (_, c) => c.toUpperCase())] ?? null));
const readJson = (p) => { try { return JSON.parse(readFileSync(p, 'utf8')); } catch { return null; } };
const pemOf = (s) => (typeof s === 'string' ? s.replace(/\s+/g, '') : null);

/* ── what the runner prepared (read here, never written) ─────────────────── */
const SCHEDULE_ID = '01a0a62a-a23b-739a-baf7-d49936d68b39';
const KEY_REF = 'EYE_EXPORT_SIGNING_KEY_DEMO';
const PUB_PEM_PATH = resolvePath(ROOT, env.EYE_DEMO_SIGNING_PUBLIC_PEM ?? '.eye-local/export-signing-demo.pub.pem');
const STATION = resolvePath(ROOT, env.EYE_DEMO_TRANSFER_STATION ?? '.eye-local/transfer-station-demo');
const STATION_KEY = 'nordwerk-transfer-station'; const STATION_RECIPIENT = 'NORDWERK GmbH — demonstration transfer station';
const HTTPS_KEY = 'nordwerk-exports'; const HTTPS_ENDPOINT = 'https://exports.nordwerk.example/receive'; const HTTPS_REF = 'EYE_DST_NORDWERK';
const VERIFIER = join(ROOT, 'scripts', 'retention', 'verify-export.mjs');
const RECIPIENT = join(ROOT, 'scripts', 'retention', 'transfer-station-recipient.mjs');
const publicPem = existsSync(PUB_PEM_PATH) ? readFileSync(PUB_PEM_PATH, 'utf8') : null;
const stationIsDir = existsSync(STATION) && statSync(STATION).isDirectory();
const stationOutsideRoots = ['quarantine', 'evidence', 'archive', 'export'].every((n) => { const r = vaultRoot(n); return STATION !== r && !STATION.startsWith(r + '/') && !r.startsWith(STATION + '/'); });

/* ── the governed acts ───────────────────────────────────────────────────── */
const open = (payload) => call(`${R}/actions/open`, pn({ action: 'retention.action.open', objectType: 'RTA' }), payload, novak.token);
const resolve = (id) => call(`${R}/actions/${id}/resolve`, pn({ action: 'retention.action.resolve', objectType: 'RTA', objectId: id }), {}, novak.token);
const approve = (id, digest, rationale) => call(`${R}/actions/${id}/approve`, hb({ action: 'retention.action.approve', objectType: 'RTA', objectId: id, consequence: 'C2' }), { scopeDigest: digest, rationale }, bergmann.token);
const execute = (id) => call(`${R}/actions/${id}/execute`, pn({ action: 'retention.action.execute', objectType: 'RTA', objectId: id, consequence: 'C2' }), {}, novak.token);
const verify = (id) => call(`${R}/actions/${id}/verify`, pn({ action: 'retention.action.verify', objectType: 'RTA', objectId: id }), {}, novak.token);
const withdraw = (id, reason) => call(`${R}/actions/${id}/withdraw`, pn({ action: 'retention.action.withdraw', objectType: 'RTA', objectId: id }), { reason }, novak.token);
const evaluate = () => call(`${R}/schedules/evaluate`, pn({ action: 'retention.schedule.evaluate', objectType: 'RTS' }), {}, novak.token);
/** The schedule's retirement (0073 §1; D1): the declare rule's holders — the platform administrator here — with a reason, C2. */
const retireSchedule = (id, reason) => call(`${R}/schedules/${id}/retire`, adm({ action: 'retention.schedule.retire', objectType: 'RTS', objectId: id, consequence: 'C2' }), { reason }, admin.token);
/** The signing key (0073 §2; D3, C1): a TENANT row declared under the domain route by the platform administrator; the reference's NAME travels, never its value. */
const declareKey = (credentialRef, purpose) => call(`${R}/signing-keys/declare`, adm({ action: 'retention.signing_key.declare', objectType: 'RSK', consequence: 'C2' }), { credentialRef, purpose }, admin.token);
const listKeysAs = (build, session) => call(`${R}/signing-keys/list`, build({ action: 'retention.read', objectType: 'RSK', sideEffect: 'none' }), {}, session.token);
/** A destination (0073 §3; D5): declared by the domain's administrator — the platform administrator here — by kind. */
const declareDestination = (payload) => call(`${R}/destinations/declare`, adm({ action: 'retention.destination.declare', objectType: 'RDS', consequence: 'C2' }), payload, admin.token);
const listDestinationsAs = (build, session) => call(`${R}/destinations/list`, build({ action: 'retention.read', objectType: 'RDS', sideEffect: 'none' }), {}, session.token);
/** The export's reads and acts on the action (object type RTA): the read, the governed download (D7), the delivery (D6), the collect act, the revocation (B11). */
const exportGet = (id) => call(`${R}/actions/${id}/export/get`, pn({ action: 'retention.read', objectType: 'RTA', objectId: id, sideEffect: 'none' }), {}, novak.token);
const downloadAs = (build, session, id) => call(`${R}/actions/${id}/export/download`, build({ action: 'retention.export.download', objectType: 'RTA', objectId: id }), {}, session.token);
const deliver = (id, destinationKey) => call(`${R}/actions/${id}/export/deliver`, hb({ action: 'retention.export.deliver', objectType: 'RTA', objectId: id, consequence: 'C2' }), { destinationKey }, bergmann.token);
const deliveriesList = (id) => call(`${R}/actions/${id}/export/deliveries/list`, pn({ action: 'retention.read', objectType: 'RTA', objectId: id, sideEffect: 'none' }), {}, novak.token);
const collectReceipt = (id, deliveryId) => call(`${R}/actions/${id}/export/deliveries/${deliveryId}/collect-receipt`, hb({ action: 'retention.export.acknowledge', objectType: 'RTA', objectId: id, consequence: 'C2' }), {}, bergmann.token);
const revoke = (id, reason) => call(`${R}/actions/${id}/export/revoke`, hb({ action: 'retention.export.revoke', objectType: 'RTA', objectId: id, consequence: 'C2' }), { reason }, bergmann.token);
const tierStateAs = (build, session) => call(`${R}/tier/state`, build({ action: 'retention.read', objectType: 'RTP', sideEffect: 'none' }), {}, session.token);

/* ── the ledgers ─────────────────────────────────────────────────────────── */
const lastEvent = async (id, event) => (await q(`select details, occurred_at, actor_principal_id::text actor from retention.action_events where action_id = $1 and event = $2 order by occurred_at desc limit 1`, [id, event]))[0] ?? null;
const checksOf = (id) => q(`select check_name, passed from retention.verifications where action_id = $1 order by verified_at, check_name`, [id]);
const packageRow = async (id) => (await q(`select action_id::text, object_count::int, excluded_count::int, byte_total::int, manifest_digest, package_digest, archive_digest, signing_key_id, built_at, expires_at, revoked_at, signature ->> 'scheme' scheme, signature ->> 'key_id' key_id, signature ->> 'algorithm' algorithm, length(signature ->> 'signature')::int signature_length from retention.export_packages where action_id = $1`, [id]))[0] ?? null;
const deliveryRows = (id) => q(`select d.delivery_id::text, d.attempt::int, d.state, d.failure_class, d.archive_digest, d.package_digest, d.signing_key_id, d.receipt, d.receipt_digest, d.delivered_at, d.acknowledged_at, x.destination_key, x.kind from retention.export_deliveries d join retention.export_destinations x on x.destination_id = d.destination_id where d.action_id = $1 order by d.delivered_at`, [id]);
const custodyDelivered = (deliveryId) => q(`select manifest_id::text, details from observation.custody_events where event = 'custody.delivered' and details ->> 'delivery_id' = $1 order by occurred_at`, [deliveryId]);
/** The current admitted internal evidence records of nordwerk-internal with confirmed rights in the given tier (any tier when null), most recent first. */
const targetsIn = (tier, limit) => q(`select o.object_id::text id, o.object_version::int version, (o.payload ->> 'manifest_id') manifest_id, m.locator, m.content_digest, m.byte_length::int, s.source_key, observation.manifest_tier(m.manifest_id) tier
    from objects.canonical_objects o join observation.blob_manifests m on m.manifest_id = (o.payload ->> 'manifest_id')::uuid
    join observation.source_contracts_current s on s.source_id = m.source_id and s.contract_version = m.contract_version
    where o.object_type = 'EVD' and o.tenant_id = $1 and o.domain_id = $2 and o.lifecycle_state = 'admitted' and o.classification = 'internal' and s.rights_state = 'confirmed' and s.source_key = 'nordwerk-internal'
      and not exists (select 1 from observation.blob_tombstones x where x.manifest_id = m.manifest_id) and ($3::text is null or observation.manifest_tier(m.manifest_id) = $3)
      and o.object_version = (select max(x.object_version) from objects.canonical_objects x where x.object_id = o.object_id)
    order by o.recorded_at desc limit $4`, [T, D, tier, limit]);
/** OPEN → RESOLVE → APPROVE, printing each; null when a step failed. */
const approved = async (label, payload, rationale) => {
  const o = await open(payload);
  if (!o.ok) { fail(`open ${label} (p.novak)`, o); return null; }
  const id = o.body.action.actionId;
  const rs = await resolve(id);
  if (!rs.ok) { fail(`resolve ${label}`, rs); return null; }
  const sc = rs.body.scope;
  const ap = await approve(id, sc.scope_digest, rationale);
  if (!ap.ok) { fail(`approve ${label} (h.bergmann)`, ap); return null; }
  ok(`${label}: P. Novák opened ${short(id)}; scope resolved (${sc.items} item(s), ${sc.execute} to execute, ${sc.held} held, ${sc.excluded ?? 0} excluded; digest ${String(sc.scope_digest).slice(0, 12)}…); H. Bergmann approved`);
  return { id, digest: sc.scope_digest };
};
/** The customer's verifier on a tar (D2): the JSON answer and the text verdict line, each from its own run. */
const runVerifierOnTar = (tarPath, ...extra) => {
  const j = spawnSync(process.execPath, [VERIFIER, '--tar', tarPath, '--json', ...extra], { encoding: 'utf8' });
  let parsed = null; try { parsed = JSON.parse(j.stdout); } catch { parsed = null; }
  const t = spawnSync(process.execPath, [VERIFIER, '--tar', tarPath, ...extra], { encoding: 'utf8' });
  const lines = t.stdout.trim().split('\n');
  return { exit: j.status, ok: parsed?.ok ?? null, complete: parsed?.complete ?? '(no field)', failed: parsed?.failed ?? null, signature: parsed?.signature ?? null, verdictLine: lines.at(-1) ?? '', failLines: lines.filter((l) => /^\s*FAIL\b/.test(l)), stderr: (j.stderr ?? '').slice(0, 300) };
};
/** The ustar entries of a tar (D2: 512-byte headers, the name NUL-terminated at 100, the size octal at 124..136; two zero blocks end it). */
const tarEntries = (buf) => {
  const entries = []; let off = 0;
  while (off + 512 <= buf.length) {
    const header = buf.subarray(off, off + 512);
    if (header.every((b) => b === 0)) break;
    const name = header.subarray(0, 100).toString('utf8').replace(/\0[\s\S]*$/, '');
    const size = parseInt(header.subarray(124, 136).toString('utf8').replace(/\0[\s\S]*$/, '').trim() || '0', 8);
    entries.push({ name, offset: off + 512, size });
    off += 512 + Math.ceil(size / 512) * 512;
  }
  return entries;
};
const listLine = (xs, f) => (xs.length === 0 ? 'none' : xs.map(f).join('; '));
const keyLine = (k) => `${field(k, 'key_id')} (${field(k, 'algorithm') ?? 'Ed25519'}; purpose ${field(k, 'purpose')}; reference ${field(k, 'credential_ref')}${field(k, 'readiness') !== null ? `, readiness ${field(k, 'readiness')}` : ''}; ${field(k, 'retired_at') !== null ? `RETIRED at ${iso(field(k, 'retired_at'))}` : 'active'}; declared ${iso(field(k, 'declared_at'))})`;
const destinationLine = (x) => `${field(x, 'destination_key')} — ${field(x, 'kind')} at ${field(x, 'endpoint')}${field(x, 'credential_ref') !== null ? ` (credential reference ${field(x, 'credential_ref')})` : ''}; recipient "${field(x, 'recipient')}"; readiness ${field(x, 'readiness') ?? (field(x, 'retired_at') !== null ? 'retired' : 'active')}`;
const deliveryLine = (d) => `${short(field(d, 'delivery_id'))} attempt ${field(d, 'attempt')} to ${field(d, 'destination_key') ?? short(field(d, 'destination_id'))}: ${field(d, 'state')}${field(d, 'failure_class') !== null ? ` (${field(d, 'failure_class')})` : ''}, delivered ${iso(field(d, 'delivered_at'))}${field(d, 'acknowledged_at') !== null ? `, acknowledged ${iso(field(d, 'acknowledged_at'))}` : ''}`;

console.log(`\n=== CP-6 batch B13 on the demonstration (${env.EYE_DB_NAME ?? 'eye_demo'} at ${process.env.EYE_API ?? 'http://localhost:3401'}) — the schedule retirement and the customer export's delivery ===\n`);
console.log(`prepared by the runner (not by this act): the demonstration signing key generated by scripts/retention/generate-demo-signing-key.mjs, its one env line appended to .eye-local/env and its public key at ${rel(PUB_PEM_PATH)} (${publicPem === null ? 'ABSENT — the signature cannot be verified here' : `${publicPem.split('\n').filter((l) => l.length > 0).length} PEM lines, sha256 ${sha256(publicPem).slice(0, 16)}…`}); the transfer station's directory ${rel(STATION)} (${stationIsDir ? `present, a directory, ${stationOutsideRoots ? 'outside' : 'NOT OUTSIDE'} the four vault roots` : 'ABSENT'}); the API restarted by scripts/ops/demo-restart.sh --build so its process binds ${KEY_REF}\n`);
if (publicPem === null) bad(`the public key PEM is not at ${rel(PUB_PEM_PATH)} (EYE_DEMO_SIGNING_PUBLIC_PEM names another path): run node scripts/retention/generate-demo-signing-key.mjs --public-out ${rel(PUB_PEM_PATH)} >> .eye-local/env and restart the API`);
if (!stationIsDir) bad(`the transfer station's directory ${rel(STATION)} is not an existing directory (EYE_DEMO_TRANSFER_STATION names another root): create it before the act — the product refuses a destination whose directory does not exist`);

/* ── 1. THE SCHEDULE RETIRED ─────────────────────────────────────────────── */
console.log('1. THE SCHEDULE RETIRED — the platform administrator retires the archive schedule the B12 act declared; its history kept; an evaluation opens nothing from it');
let scheduleId = SCHEDULE_ID;
{
  const readSchedule = async (id) => (await q(`select schedule_id::text, state, action_kind, retention_profile, due_after::text, selector, last_evaluation, last_evaluated_at, retired_at, retired_by::text, retire_reason from retention.schedules where schedule_id = $1`, [id]))[0] ?? null;
  let before = null; let migrated = true;
  try { before = await readSchedule(scheduleId); } catch (e) { migrated = false; bad(`the schedules table has no retirement columns (${e.message.slice(0, 120)}): migration 0073 is not applied on ${env.EYE_DB_NAME ?? 'eye_demo'}; the scene is skipped`); }
  if (migrated && before === null) {
    // The rehearsal copy is a restore of eye_demo and holds the row; a database without it takes the B12 act's schedule by its selector.
    const alt = (await q(`select s.schedule_id::text from retention.schedules s join observation.source_contracts_current c on c.source_id = (s.selector ->> 'source_id')::uuid where s.tenant_id = $1 and s.domain_id = $2 and s.action_kind = 'archive' and s.target_kind = 'evidence' and c.source_key = 'nordwerk-internal' order by s.declared_at limit 1`, [T, D]))[0] ?? null;
    if (alt !== null) { note(`schedule ${short(SCHEDULE_ID)} is not on this database: the archive schedule of nordwerk-internal ${short(alt.schedule_id)} stands in for it`); scheduleId = alt.schedule_id; before = await readSchedule(scheduleId); }
  }
  if (!migrated) { /* said above */ }
  else if (before === null) bad(`no archive schedule of nordwerk-internal on ${env.EYE_DB_NAME ?? 'eye_demo'} (the B12 act declares it)`);
  else {
    const actionsOf = () => q(`select a.action_id::text, a.kind, a.state, (select count(*)::int from retention.action_events e where e.action_id = a.action_id) events from retention.actions_current a where a.schedule_id = $1 order by a.opened_at`, [scheduleId]);
    const actionsBefore = await actionsOf();
    note(`the schedule ${short(scheduleId)}: ${before.action_kind} of profile "${before.retention_profile}" after ${before.due_after}, selector ${JSON.stringify(before.selector)}; state ${before.state}; last evaluation ${JSON.stringify(before.last_evaluation ?? {})} at ${iso(before.last_evaluated_at)}`);
    note(`the actions it opened (${actionsBefore.length}): ${listLine(actionsBefore, (a) => `${short(a.action_id)} ${a.kind} ${a.state} (${a.events} event(s))`)}`);
    const REASON = 'declared by the B12 act for the restore-window demonstration; retired, its history kept';
    if (before.state === 'retired') note(`already retired at ${iso(before.retired_at)} by ${before.retired_by === null ? 'a raw update of an earlier harness' : `principal ${short(before.retired_by)}`} — "${before.retire_reason ?? ''}" (an earlier run of this act): the retirement is skipped; the checks below read the row as it is`);
    else {
      const r = await retireSchedule(scheduleId, REASON);
      if (!r.ok) fail('schedules/:id/retire (platform-admin)', r);
      else ok(`the platform administrator retired it: HTTP ${r.status} — ${JSON.stringify(r.body.schedule ?? r.body).slice(0, 240)}`);
    }
    const after = await readSchedule(scheduleId);
    if (after.state === 'retired' && after.retired_at !== null && String(after.retire_reason ?? '').length >= 8) ok(`the row: state ${after.state}, retired_at ${iso(after.retired_at)}, retired_by ${after.retired_by === null ? 'null' : `principal ${short(after.retired_by)}${after.retired_by === admin.principalId ? ' (the platform administrator)' : ''}`}, reason "${after.retire_reason}"`);
    else if (after.state === 'retired' && after.retired_at === null) note('the row is retired by a raw update of state alone (a harness\'s way; no instant, no reason — C10 keeps such rows valid): the governed retirement records the instant, the actor and the reason');
    else bad(`expected the row retired with its instant and reason; got state ${after.state}, retired_at ${iso(after.retired_at)}, reason ${JSON.stringify(after.retire_reason)}`);
    if (JSON.stringify(after.last_evaluation) === JSON.stringify(before.last_evaluation) && iso(after.last_evaluated_at) === iso(before.last_evaluated_at)) ok(`its last_evaluation kept: ${JSON.stringify(after.last_evaluation ?? {})} at ${iso(after.last_evaluated_at)}`); else bad(`its last_evaluation changed: ${JSON.stringify(after.last_evaluation)} (was ${JSON.stringify(before.last_evaluation)})`);
    const actionsAfter = await actionsOf();
    if (JSON.stringify(actionsAfter) === JSON.stringify(actionsBefore)) ok(`the ${actionsAfter.length} action(s) it opened and their events untouched: ${listLine(actionsAfter, (a) => `${short(a.action_id)} ${a.state} (${a.events})`)}`); else bad(`an action it opened changed: ${JSON.stringify(actionsAfter)} (was ${JSON.stringify(actionsBefore)})`);
    const ledger = await q(`select event, details, occurred_at, actor_principal_id::text actor from retention.schedule_events where schedule_id = $1 order by occurred_at`, [scheduleId]);
    const retiredEvent = ledger.filter((e) => e.event === 'schedule.retired').at(-1) ?? null;
    if (retiredEvent !== null) ok(`the schedule ledger (retention.schedule_events): ${ledger.map((e) => `${e.event} at ${iso(e.occurred_at)}`).join(', ')} — schedule.retired by principal ${short(retiredEvent.actor)} with ${JSON.stringify(retiredEvent.details).slice(0, 200)}${ledger.some((e) => e.event === 'schedule.declared') ? '' : ' (no schedule.declared row: the schedule was declared before the ledger existed — 0073 writes it for every declaration from now on)'}`);
    else if (after.state === 'retired' && after.retired_at === null) note('no schedule.retired row: the raw update that retired it wrote no event (the governed act does)');
    else bad(`no schedule.retired row on the schedule ledger (${ledger.length} row(s): ${ledger.map((e) => e.event).join(', ') || 'none'})`);
    const ev = await evaluate();
    if (!ev.ok) fail('schedules/evaluate (p.novak)', ev);
    else {
      const opened = ev.body.evaluation.opened ?? []; const mine = opened.filter((o) => o.schedule_id === scheduleId);
      if (mine.length === 0) ok(`P. Novák's evaluation opened nothing from the retired schedule (a retired schedule is not read: evaluate_schedules takes state = 'active'); deferred ${ev.body.evaluation.deferred}${opened.length > 0 ? `; ${opened.length} opened by other schedules` : '; nothing opened by any schedule'}`);
      else bad(`the evaluation opened ${mine.length} action(s) from the retired schedule`);
      for (const o of opened) { const wd = await withdraw(o.action_id, 'opened by another schedule during the B13 act; the demonstration is left as found'); if (wd.ok) note(`  withdrew ${short(o.action_id)} (${o.kind} by schedule ${short(o.schedule_id)})`); else fail(`withdraw ${short(o.action_id)}`, wd); }
      const stillOpen = await q(`select count(*)::int n from retention.actions_current where schedule_id = $1 and state not in ('withdrawn', 'rejected', 'failed', 'verified', 'verified_with_residuals')`, [scheduleId]);
      note(`live actions of the retired schedule: ${stillOpen[0].n} (its closed history stays: ${actionsAfter.length} action(s))`);
    }
    const st = await tierStateAs(pn, novak);
    if (!st.ok) fail('tier/state (p.novak)', st);
    else {
      const entry = (st.body.state.schedules ?? []).find((s) => s.schedule_id === scheduleId) ?? null;
      if (entry !== null && entry.state === 'retired' && entry.retired_at !== null && entry.retired_at !== undefined) ok(`tier/state shows it retired: ${entry.action_kind} of profile "${entry.retention_profile}" (${entry.state}, retired_at ${iso(entry.retired_at)}; last evaluation ${JSON.stringify(entry.last_evaluation ?? {})})`);
      else bad(`tier/state's entry for the schedule: ${JSON.stringify(entry)}`);
    }
  }
}

/* ── 2. THE DEMONSTRATION KEY ────────────────────────────────────────────── */
console.log('\n2. THE DEMONSTRATION KEY — the tenant\'s export signing key declared from the reference EYE_EXPORT_SIGNING_KEY_DEMO with purpose DEMONSTRATION; the public key recorded; the value never leaves the API process');
let key = null;
{
  const listed = await listKeysAs(adm, admin);
  if (!listed.ok) fail('signing-keys/list (platform-admin)', listed);
  else {
    const keys = listed.body.keys ?? [];
    note(`the tenant's keys before: ${listLine(keys, keyLine)}`);
    const existing = keys.find((k) => field(k, 'credential_ref') === KEY_REF && field(k, 'retired_at') === null) ?? null;
    if (existing !== null) { key = existing; note(`an active key from ${KEY_REF} is already declared (an earlier run): reused — a second declaration of the same key is refused as already declared`); }
    else {
      const r = await declareKey(KEY_REF, 'demonstration');
      if (!r.ok) {
        fail('signing-keys/declare (platform-admin)', r);
        if (r.status === 422 && /binds no|not bound/i.test(String(r.body?.message ?? ''))) note(`the API process does not bind ${KEY_REF}: the runner appends the generator's env line to .eye-local/env and restarts with scripts/ops/demo-restart.sh --build`);
      } else { key = r.body.key ?? r.body; ok(`the platform administrator declared the key: HTTP ${r.status} — ${keyLine(key)}`); }
    }
  }
  if (key !== null) {
    const pem = field(key, 'public_key_pem');
    console.log(String(pem ?? '(no public_key_pem in the answer)').trim().split('\n').map((l) => `      ${l}`).join('\n'));
    if (publicPem !== null && pem !== null && pemOf(pem) === pemOf(publicPem)) ok(`the recorded public key is the one the runner wrote to ${rel(PUB_PEM_PATH)} (the same SPKI PEM): the customer's verifier below uses that file`);
    else if (publicPem === null) note('the public key file is absent: the recorded PEM above is the one to verify against');
    else bad(`the recorded public key differs from ${rel(PUB_PEM_PATH)}: the API process binds another value under ${KEY_REF} than the one the runner generated (restart the API after the env line, or regenerate)`);
    const rows = await q(`select key_id, algorithm, credential_ref, purpose, declared_at, retired_at from retention.export_signing_keys where tenant_id = $1 order by declared_at`, [T]);
    const cols = (await q(`select column_name from information_schema.columns where table_schema = 'retention' and table_name = 'export_signing_keys' order by ordinal_position`)).map((c) => c.column_name);
    note(`retention.export_signing_keys of the tenant: ${listLine(rows, (k) => `${k.key_id} ${k.purpose} (${k.credential_ref}; ${k.retired_at === null ? 'active' : 'retired'})`)}; the columns ${cols.join(', ')} — the reference's NAME and the PUBLIC key are recorded; the private value lives in the API process's environment only`);
    const again = await listKeysAs(pn, novak);
    // An Ed25519 PKCS8 DER in base64 begins MC4CAQAwBQYDK2Vw (the SPKI of the public key begins MCowBQYDK2VwAyEA): the answer must carry neither that prefix nor a PEM private block.
    if (again.ok) { const mine = (again.body.keys ?? []).find((k) => field(k, 'key_id') === field(key, 'key_id')) ?? null; if (mine !== null && !/BEGIN PRIVATE KEY|MC4CAQAwBQYDK2Vw/.test(JSON.stringify(mine))) ok(`P. Novák lists it (retention.read): ${keyLine(mine)} — no value of the reference in the answer`); else bad(`the list as P. Novák: ${mine === null ? 'the key is not listed' : 'the answer carries private key material'}`); } else fail('signing-keys/list (p.novak)', again);
    note('DEMONSTRATION vs PRODUCTION: this key was generated by scripts/retention/generate-demo-signing-key.mjs on this host and is declared with purpose demonstration (the purpose is shown wherever the signature is shown). Production activation = a production key generated and held under the owner\'s key custody, bound by its own reference EYE_EXPORT_SIGNING_KEY_<NAME>, declared with purpose production, and this key retired (…/signing-keys/:keyId/retire) — a named remaining step; a package signed by the retired key still verifies against its recorded public key');
  }
}

/* ── 3. THE DESTINATIONS ─────────────────────────────────────────────────── */
console.log('\n3. THE DESTINATIONS — the transfer station (the isolated synthetic destination: the disconnected-transfer path) and the https destination (the production kind; its credential unbound on this host)');
let station = null; let httpsDest = null;
{
  const listed = await listDestinationsAs(adm, admin);
  if (!listed.ok) fail('destinations/list (platform-admin)', listed);
  else {
    const ds = listed.body.destinations ?? [];
    note(`the domain's destinations before: ${listLine(ds, destinationLine)}`);
    const active = (k) => ds.find((x) => field(x, 'destination_key') === k && field(x, 'retired_at') === null) ?? null;
    station = active(STATION_KEY); httpsDest = active(HTTPS_KEY);
    if (station !== null) note(`${STATION_KEY} is already declared (an earlier run): reused${field(station, 'endpoint') === STATION ? '' : ` — at ${field(station, 'endpoint')}, not ${STATION}: the files of this run go there`}`);
    else if (!stationIsDir) bad(`${STATION_KEY} cannot be declared: ${rel(STATION)} is not an existing directory`);
    else {
      const r = await declareDestination({ destinationKey: STATION_KEY, kind: 'transfer_station', endpoint: STATION, recipient: STATION_RECIPIENT, purpose: 'the customer\'s periodic export of its internal records' });
      if (!r.ok) fail('destinations/declare transfer_station (platform-admin)', r);
      else { station = r.body.destination ?? r.body; ok(`the platform administrator declared the transfer station: HTTP ${r.status} — ${destinationLine(station)} (an absolute directory that exists and lies outside the four vault roots, re-checked by realpath at every write)`); }
    }
    if (httpsDest !== null) note(`${HTTPS_KEY} is already declared (an earlier run): reused`);
    else {
      const r = await declareDestination({ destinationKey: HTTPS_KEY, kind: 'https', endpoint: HTTPS_ENDPOINT, credentialRef: HTTPS_REF, recipient: 'NORDWERK GmbH — export endpoint (production; not bound on this host)', purpose: 'the customer\'s production export endpoint' });
      if (!r.ok) fail('destinations/declare https (platform-admin)', r);
      else { httpsDest = r.body.destination ?? r.body; ok(`the platform administrator declared the https destination: HTTP ${r.status} — ${destinationLine(httpsDest)}`); }
    }
    const after = await listDestinationsAs(pn, novak);
    if (!after.ok) fail('destinations/list (p.novak)', after);
    else {
      const rows = after.body.destinations ?? [];
      const s = rows.find((x) => field(x, 'destination_key') === STATION_KEY && field(x, 'retired_at') === null) ?? null; const h = rows.find((x) => field(x, 'destination_key') === HTTPS_KEY && field(x, 'retired_at') === null) ?? null;
      if (s !== null && field(s, 'kind') === 'transfer_station' && (field(s, 'readiness') ?? 'active') === 'active') ok(`the list: ${destinationLine(s)}`); else bad(`the list's transfer station: ${JSON.stringify(s)}`);
      if (h !== null && field(h, 'kind') === 'https' && field(h, 'readiness') === 'blocked-credential') ok(`the list: ${destinationLine(h)} — the reference ${HTTPS_REF} is NOT bound in the API process, so the destination is blocked before any egress`); else bad(`the list's https destination: ${JSON.stringify(h)} (expected readiness blocked-credential)`);
      if (rows.some((x) => /Bearer |EYE_DST_[A-Z0-9_]+=/.test(JSON.stringify(x)))) bad('a destination row carries a credential value'); else note('no credential VALUE in any listed destination (the reference name and its readiness only)');
    }
    note(`DEMONSTRATION vs PRODUCTION: the transfer station is a directory on this host the product writes packages into and reads receipts from (ES-53-004, NZ-20: the signed-package transfer path for a disconnected recipient) — the isolated synthetic destination of this demonstration; the https destination is the production kind, delivered by the delivery egress (POST, TLS verified, resolve-then-connect, the credential as a bearer on the first hop, no redirect followed) — its activation needs the customer's reachable endpoint and one line ${HTTPS_REF}=<the token> in the API process's environment (never in a row), a named step`);
  }
}

/* ── 4. THE SIGNED EXPORT ────────────────────────────────────────────────── */
console.log('\n4. THE SIGNED EXPORT — P. Novák opens a customer export of the two hot NORDWERK internal records (ceiling internal, expiry 7 days); approved; executed with the active key: scheme eye-customer-export/2, the archive digest and the expiry recorded; verified');
let exp = null; let pkg = null; let manifest = null;
{
  let targets = await targetsIn('hot', 2);
  if (targets.length < 2) { note(`fewer than two hot NORDWERK internal records with confirmed rights (${targets.length}): the two most recent in any tier are taken (the export reads the bytes from the tier they are in)`); targets = await targetsIn(null, 2); }
  if (targets.length === 0) bad('no current NORDWERK internal evidence with confirmed rights to export');
  else {
    note(`the targets: ${targets.map((t) => `evidence ${short(t.id)}@${t.version} (${t.byte_length} bytes, manifest ${short(t.manifest_id)}, tier ${t.tier})`).join(', ')}`);
    exp = await approved('customer export', { kind: 'customer_export', targetKind: 'evidence', selector: { manifestIds: targets.map((t) => t.manifest_id), classificationCeiling: 'internal', destination: 'export', expiresAfter: '7 days' }, retentionProfile: null, reason: 'the customer asks for its internal records as a signed open package, delivered to its transfer station' }, 'internal records only, under the ceiling; the customer\'s own tenant; the package expires in 7 days');
    if (exp !== null) {
      const ex = await execute(exp.id);
      if (!ex.ok) { fail('execute export (p.novak)', ex); exp = null; }
      else {
        const e = ex.body.execution; const p = e.package ?? null;
        if (p === null) { bad('no package recorded'); exp = null; }
        else {
          ok(`P. Novák executed: HTTP ${ex.status} — ${e.executed} exported, ${e.refused} refused; package ${p.locator_prefix} — ${p.objects} object(s), ${p.bytes} bytes, package digest ${String(p.package_digest).slice(0, 16)}…, manifest digest ${String(p.manifest_digest).slice(0, 16)}…${field(p, 'archive_digest') !== null ? `, archive digest ${String(field(p, 'archive_digest')).slice(0, 16)}…` : ''}${field(p, 'signing_key_id') !== null ? `, signed by ${field(p, 'signing_key_id')}` : ''}`);
          pkg = await packageRow(exp.id);
          const days = pkg === null || pkg.expires_at === null ? null : (new Date(pkg.expires_at).getTime() - new Date(pkg.built_at).getTime()) / 86_400_000;
          const keyId = key === null ? null : field(key, 'key_id');
          if (pkg !== null && pkg.scheme === 'eye-customer-export/2' && pkg.signing_key_id !== null && (keyId === null || pkg.signing_key_id === keyId) && pkg.key_id === pkg.signing_key_id && pkg.algorithm === 'Ed25519' && pkg.signature_length === 88 && HEX64.test(String(pkg.archive_digest)) && days !== null && Math.abs(days - 7) < 0.001) ok(`the record (retention.export_packages): scheme ${pkg.scheme}, key ${pkg.signing_key_id} (${pkg.algorithm}; the signature the base64 of 64 bytes), archive digest ${pkg.archive_digest}, built ${iso(pkg.built_at)}, expires ${iso(pkg.expires_at)} (${days} days: the selector's expires_after)`);
          else bad(`the record: ${JSON.stringify(pkg)} — expected scheme /2 signed by ${keyId ?? 'the active key'}, a 64-byte signature, an archive digest and an expiry 7 days after the build`);
          const rec = (await q(`select evidence from retention.executions where action_id = $1 and port = 'retention.record_export_package' order by executed_at desc limit 1`, [exp.id]))[0] ?? null;
          note(`the record_export_package execution row's evidence carries archive_digest ${rec?.evidence?.archive_digest === undefined ? 'ABSENT' : String(rec.evidence.archive_digest).slice(0, 16) + '…'}, signing_key_id ${rec?.evidence?.signing_key_id ?? 'ABSENT'}, expires_at ${iso(rec?.evidence?.expires_at ?? null)} (the digest and the key travel in the execution ledger; no extra execution row)`);
          const vf = await verify(exp.id);
          if (vf.ok && vf.body.verification.verified === true) { const cs = await checksOf(exp.id); ok(`verified by the product: ${cs.filter((c) => c.passed).length}/${cs.length} checks — state ${vf.body.verification.state}`); }
          else if (vf.ok) bad(`the export's verification did not pass: ${JSON.stringify(vf.body.verification).slice(0, 200)}`); else fail('verify export', vf);
          const rd = await exportGet(exp.id);
          if (!rd.ok) fail('export/get (p.novak)', rd);
          else {
            manifest = rd.body.manifest ?? null;
            const sig = manifest?.signature ?? null;
            const k = rd.body.signing_key ?? rd.body.key ?? rd.body.package?.signing_key ?? null;
            const pem = k === null ? null : field(k, 'public_key_pem');
            if (sig !== null && sig.scheme === 'eye-customer-export/2' && sig.key_id === pkg?.signing_key_id && typeof sig.signature === 'string' && sig.signature.length === 88) ok(`the read route: ${rd.body.files?.length ?? '?'} file(s); the manifest's signature block — scheme ${sig.scheme}, key ${sig.key_id}, ${sig.algorithm}, signature ${sig.signature.slice(0, 16)}… over the package digest ${String(sig.package_digest).slice(0, 16)}…; expires_at ${iso(field(rd.body, 'expires_at') ?? pkg?.expires_at)}, expired ${field(rd.body, 'expired') ?? false}`);
            else bad(`the read route's signature block: ${JSON.stringify(sig).slice(0, 300)}`);
            if (k !== null && pem !== null) { if (publicPem === null || pemOf(pem) === pemOf(publicPem)) ok(`the read route carries the signing key for the customer to fetch: ${field(k, 'key_id')} (purpose ${field(k, 'purpose')}, ${field(k, 'state') ?? (field(k, 'retired_at') === null ? 'active' : 'retired')}), its public key PEM the one on file`); else bad('the read route\'s public key PEM differs from the file'); }
            else note(`the read route's answer names no signing key object (its keys: ${Object.keys(rd.body).join(', ')}); the key's public PEM is served by …/signing-keys/list`);
          }
        }
      }
    }
  }
}

/* ── 5. THE DOWNLOAD ─────────────────────────────────────────────────────── */
console.log('\n5. THE DOWNLOAD — P. Novák downloads the package as one tar (its digest the record\'s; the event on the action); the customer\'s verifier on the tar with the public key; a copy with one byte flipped inside a .bin entry fails');
const scratch = mkdtempSync(join(tmpdir(), 'eye-b13-act-'));
let tarPath = null;
if (exp === null || pkg === null) bad('no export to download (scene 4 built none)');
else {
  const dl = await downloadAs(pn, novak, exp.id);
  if (!dl.ok) fail('export/download (p.novak)', dl);
  else {
    const d = dl.body.download ?? {};
    const bytes = Buffer.from(String(d.base64 ?? ''), 'base64');
    const digest = sha256(bytes);
    tarPath = join(scratch, String(d.filename ?? `${exp.id}.tar`));
    writeFileSync(tarPath, bytes);
    if (bytes.byteLength === Number(d.byteLength) && digest === d.archiveDigest && digest === pkg.archive_digest && d.filename === `${exp.id}.tar` && d.packageDigest === pkg.package_digest) ok(`P. Novák downloaded ${d.filename}: HTTP ${dl.status}, ${bytes.byteLength} bytes, sha256 ${digest} = the recorded archive digest (the tar rebuilt from the package files and compared before it was served); package digest ${String(d.packageDigest).slice(0, 16)}…, manifest digest ${String(d.manifestDigest).slice(0, 16)}…, expires ${iso(d.expiresAt)}; written to ${tarPath}`);
    else bad(`the download: filename ${d.filename}, ${bytes.byteLength} bytes (declared ${d.byteLength}), sha256 ${digest}, archiveDigest ${d.archiveDigest}, the record's ${pkg.archive_digest}`);
    const entries = tarEntries(bytes);
    const expected = manifest === null ? null : ['manifest.json', ...manifest.objects.map((o) => o.bytes.file).sort()];
    if (expected !== null && JSON.stringify(entries.map((x) => x.name)) === JSON.stringify(expected)) ok(`the tar's entries in the fixed order: ${entries.map((x) => `${x.name} (${x.size} bytes)`).join(', ')} — manifest.json first, then the listed .bin files by name (D2: a deterministic ustar, so the digest is a function of the files and built_at)`);
    else note(`the tar's entries: ${entries.map((x) => `${x.name} (${x.size} bytes)`).join(', ')}`);
    const sigBlock = d.signature ?? null;
    if (sigBlock !== null) note(`the answer's signature block: scheme ${sigBlock.scheme}, key ${sigBlock.key_id}${field(sigBlock, 'purpose') !== null ? `, purpose ${field(sigBlock, 'purpose')}` : ''}${field(sigBlock, 'public_key_pem') !== null ? ', the public key PEM beside it' : ''}`);
    const evd = await lastEvent(exp.id, 'export.downloaded');
    if (evd !== null && evd.actor === novak.principalId && (evd.details?.archive_digest === digest || JSON.stringify(evd.details).includes(digest))) ok(`the event export.downloaded on the action: by P. Novák at ${iso(evd.occurred_at)}, ${JSON.stringify(evd.details).slice(0, 200)}`);
    else bad(`the event export.downloaded: ${evd === null ? 'NONE' : JSON.stringify(evd).slice(0, 200)}`);
    // The customer's verifier on the tar: the entries parsed in memory, the same checks as over a directory, the key-based signature verified with the public key.
    const args = ['--expect-package-digest', pkg.package_digest, ...(publicPem === null ? [] : ['--public-key', PUB_PEM_PATH])];
    const good = runVerifierOnTar(tarPath, ...args);
    if (good.exit === 0 && good.ok === true && good.complete === true && (publicPem === null ? good.signature?.verified === null : good.signature?.verified === true)) ok(`the customer's verifier (node scripts/retention/verify-export.mjs --tar ${basename(tarPath)}${publicPem === null ? '' : ' --public-key …'}): exit 0, ok true, complete true, signature ${JSON.stringify(good.signature)} — "${good.verdictLine}"`);
    else bad(`the verifier on the downloaded tar: exit ${good.exit}, ok ${good.ok}, complete ${good.complete}, failed ${good.failed}, signature ${JSON.stringify(good.signature)} — ${good.verdictLine} ${good.failLines.join(' | ')} ${good.stderr}`);
    const bin = entries.find((x) => x.name.endsWith('.bin') && x.size > 0) ?? null;
    if (bin === null) bad('no .bin entry in the tar to flip');
    else {
      const flipped = Buffer.from(bytes); flipped[bin.offset] ^= 0x01;
      const flippedPath = join(scratch, `${exp.id}.flipped.tar`); writeFileSync(flippedPath, flipped);
      const badRun = runVerifierOnTar(flippedPath, ...args);
      if (badRun.exit === 1 && badRun.ok === false && badRun.failLines.length > 0) ok(`a copy with one byte flipped inside ${bin.name}: exit 1, ok false, failed ${badRun.failed} — "${badRun.verdictLine}"; ${badRun.failLines.map((l) => l.trim().slice(0, 160)).join(' | ')}${badRun.failLines.some((l) => /integrity/.test(l) && l.includes(bin.name)) ? '' : ' (the failing check does not name the flipped entry)'}`);
      else bad(`the verifier on the flipped copy: exit ${badRun.exit}, ok ${badRun.ok}, failed ${badRun.failed} — ${badRun.verdictLine} ${badRun.failLines.join(' | ')}`);
    }
    const denied = await downloadAs(ah, hoffmann, exp.id);
    if (denied.status === 403) ok(`A. Hoffmann's download refused: 403 (retention.export.download is the steward's, the authority's, the administrators' and the auditor's; the analyst is not among the holders)`); else bad(`A. Hoffmann's download answered ${denied.status} ${denied.body?.message ?? ''}`);
  }
}

/* ── 6. THE DELIVERY to the transfer station ─────────────────────────────── */
console.log('\n6. THE DELIVERY to the transfer station — H. Bergmann delivers; the host\'s files; custody.delivered; the DEMONSTRATION RECIPIENT verifies on its side and writes its receipt; H. Bergmann collects it: ACKNOWLEDGED');
if (exp === null || pkg === null || station === null) bad('no export or no transfer station to deliver to');
else {
  const dv = await deliver(exp.id, STATION_KEY);
  if (!dv.ok) fail(`export/deliver to ${STATION_KEY} (h.bergmann)`, dv);
  else {
    const dl = dv.body.delivery ?? {};
    if (field(dl, 'state') === 'delivered' && Number(field(dl, 'attempt')) === 1 && field(dl, 'failure_class') === null) ok(`H. Bergmann delivered: HTTP ${dv.status} — delivery ${short(field(dl, 'delivery_id'))}, state ${field(dl, 'state')}, attempt ${field(dl, 'attempt')} (the first delivery of this package to this station), receipt ${JSON.stringify(field(dl, 'receipt'))} (a transfer station answers later)${field(dl, 'key_state') !== null ? `; the key ${JSON.stringify(field(dl, 'key_state'))}` : ''}`);
    else bad(`the delivery: ${JSON.stringify(dl).slice(0, 300)} — expected delivered, attempt 1`);
    const endpoint = String(field(station, 'endpoint') ?? STATION);
    const dir = join(endpoint, T, D, exp.id);
    const tar = join(dir, 'package.tar'); const sigFile = join(dir, 'package.sig'); const deliveryFile = join(dir, 'delivery.json');
    const present = [tar, sigFile, deliveryFile].filter((p) => existsSync(p));
    if (present.length === 3 && sha256File(tar) === pkg.archive_digest) ok(`the host: ${rel(dir)}/ holds package.tar (${statSync(tar).size} bytes, sha256 the archive digest), package.sig and delivery.json`);
    else bad(`the host: ${present.length}/3 files under ${rel(dir)}${existsSync(tar) ? `; package.tar sha256 ${sha256File(tar)} (the record's ${pkg.archive_digest})` : ''}`);
    const sig = readJson(sigFile); const dj = readJson(deliveryFile);
    if (sig !== null) {
      const sigPem = field(sig, 'public_key_pem') ?? field(field(sig, 'key') ?? field(sig, 'signing_key'), 'public_key_pem');
      const inner = sig.signature ?? sig;
      note(`package.sig: scheme ${field(inner, 'scheme')}, key ${field(inner, 'key_id')}, purpose ${field(sig, 'purpose') ?? field(field(sig, 'key') ?? field(sig, 'signing_key'), 'purpose')}, key state ${JSON.stringify(field(sig, 'key_state') ?? field(field(sig, 'key') ?? field(sig, 'signing_key'), 'state'))}; public key PEM ${sigPem === null ? 'ABSENT' : publicPem !== null && pemOf(sigPem) === pemOf(publicPem) ? 'the one on file' : 'present'}`);
    } else bad('package.sig is not JSON');
    if (dj !== null && dj.delivery_id === field(dl, 'delivery_id') && dj.action_id === exp.id && dj.archive_digest === pkg.archive_digest && dj.package_digest === pkg.package_digest && dj.destination_key === STATION_KEY) ok(`delivery.json — the exchange identity: delivery ${short(dj.delivery_id)} attempt ${dj.attempt ?? '?'}, action ${short(dj.action_id)}, destination ${dj.destination_key}, recipient "${dj.recipient}", purpose "${dj.purpose}", digests package ${String(dj.package_digest).slice(0, 12)}… archive ${String(dj.archive_digest).slice(0, 12)}… manifest ${String(dj.manifest_digest).slice(0, 12)}…, signature ${JSON.stringify(dj.signature ?? { scheme: dj.signature_scheme, key_id: dj.key_id })}, delivered ${iso(dj.delivered_at)}, expires ${iso(dj.expires_at)}; "${String(dj.statement ?? '').slice(0, 160)}"`);
    else bad(`delivery.json: ${JSON.stringify(dj).slice(0, 300)}`);
    const rows = await deliveryRows(exp.id);
    const row = rows.find((r) => r.delivery_id === field(dl, 'delivery_id')) ?? null;
    const evd = await lastEvent(exp.id, 'export.delivered');
    if (row !== null && row.state === 'delivered' && row.archive_digest === pkg.archive_digest && row.signing_key_id === pkg.signing_key_id && evd !== null && (evd.details?.delivery_id === row.delivery_id || JSON.stringify(evd.details).includes(row.delivery_id))) ok(`the ledger (retention.export_deliveries): ${deliveryLine(row)}, archive digest the record's, signed by ${row.signing_key_id}; the event export.delivered at ${iso(evd.occurred_at)} ${JSON.stringify(evd.details).slice(0, 160)}`);
    else bad(`the delivery row ${JSON.stringify(row).slice(0, 200)}; event export.delivered ${evd === null ? 'NONE' : 'present'}`);
    const custody = await custodyDelivered(String(field(dl, 'delivery_id')));
    if (custody.length === Number(pkg.object_count)) ok(`custody.delivered per exported record: ${custody.length} row(s) — ${custody.map((c) => `manifest ${short(c.manifest_id)} (${c.details?.destination_key ?? '?'}, ${c.details?.state ?? '?'})`).join(', ')}`); else bad(`custody.delivered rows: ${custody.length}, the package holds ${pkg.object_count} object(s)`);
    // THE DEMONSTRATION RECIPIENT: a script on this host standing in for the customer's side of the station — it reads delivery.json, runs the
    // customer's verifier on package.tar with the public key, and writes receipt.json beside it. It never talks to the product.
    const rc = spawnSync(process.execPath, [RECIPIENT, endpoint, T, D, exp.id, ...(publicPem === null ? [] : ['--public-key', PUB_PEM_PATH]), '--recipient', STATION_RECIPIENT], { encoding: 'utf8' });
    console.log(String(rc.stdout ?? '').trim().split('\n').map((l) => `      [demonstration recipient] ${l}`).join('\n'));
    const receiptFile = join(dir, 'receipt.json'); const receipt = readJson(receiptFile);
    if (rc.status === 0 && receipt !== null && receipt.verified === true && receipt.archive_digest === pkg.archive_digest && receipt.package_digest === pkg.package_digest && receipt.delivery_id === field(dl, 'delivery_id')) ok(`the demonstration recipient (scripts/retention/transfer-station-recipient.mjs — NOT the product, NOT a production recipient): exit 0; receipt.json written — receipt ${short(receipt.receipt_id)}, recipient "${receipt.recipient}", received ${iso(receipt.received_at)}, verified ${receipt.verified} by "${receipt.verifier}", naming delivery ${short(receipt.delivery_id)} attempt ${receipt.attempt} and both digests`);
    else bad(`the demonstration recipient: exit ${rc.status} ${String(rc.stderr ?? '').slice(0, 200)}; receipt.json ${receipt === null ? 'ABSENT or not JSON' : JSON.stringify(receipt).slice(0, 300)}`);
    const col = await collectReceipt(exp.id, String(field(dl, 'delivery_id')));
    if (!col.ok) fail('collect-receipt (h.bergmann)', col);
    else {
      const ack = col.body.delivery ?? {};
      const row2 = (await deliveryRows(exp.id)).find((r) => r.delivery_id === field(dl, 'delivery_id')) ?? null;
      const eva = await lastEvent(exp.id, 'export.acknowledged');
      if (field(ack, 'state') === 'acknowledged' && row2 !== null && row2.state === 'acknowledged' && row2.acknowledged_at !== null && HEX64.test(String(row2.receipt_digest)) && row2.receipt?.receipt_id === receipt?.receipt_id && eva !== null) ok(`H. Bergmann collected the receipt: HTTP ${col.status} — ACKNOWLEDGED at ${iso(row2.acknowledged_at)}; the receipt recorded as received (digest ${row2.receipt_digest}); the event export.acknowledged at ${iso(eva.occurred_at)}`);
      else bad(`the collect act: ${JSON.stringify(ack).slice(0, 200)}; the row ${JSON.stringify(row2).slice(0, 200)}; event export.acknowledged ${eva === null ? 'NONE' : 'present'}`);
      if (row2 !== null) note(`the receipt as recorded: ${JSON.stringify(row2.receipt)}`);
      note('the exchange is CLOSED with the recipient\'s acknowledgement (DP-47-005: recipient acknowledgement before closure): the product wrote the package and its identity, the recipient verified on its side and answered, the product recorded the answer and moved the delivery to acknowledged — a receipt naming other digests would have moved it to mismatched (the exchange denied, the evidence kept; the harness T1)');
    }
  }
}

/* ── 7. THE PRODUCTION PATH'S GATE ───────────────────────────────────────── */
console.log('\n7. THE PRODUCTION PATH\'S GATE — H. Bergmann attempts the delivery to the https destination: recorded FAILED credential_unbound before any egress');
if (exp === null || pkg === null || httpsDest === null) bad('no export or no https destination for the gate');
else {
  const dv = await deliver(exp.id, HTTPS_KEY);
  const rows = await deliveryRows(exp.id);
  const row = rows.filter((r) => r.destination_key === HTTPS_KEY).at(-1) ?? null;
  const dl = dv.body?.delivery ?? null;
  if (dv.ok && field(dl, 'state') === 'failed' && field(dl, 'failure_class') === 'credential_unbound') ok(`the delivery answered HTTP ${dv.status}: delivery ${short(field(dl, 'delivery_id'))} state ${field(dl, 'state')}, class ${field(dl, 'failure_class')}, attempt ${field(dl, 'attempt')} — a FAILED delivery is a recorded fact (the request and evidence preserved), not a rolled-back one`);
  else if (row !== null && row.state === 'failed' && row.failure_class === 'credential_unbound') ok(`the delivery answered HTTP ${dv.status} (${dv.body?.message ?? ''}); the ledger holds the failed row: ${deliveryLine(row)}`);
  else bad(`expected a failed delivery of class credential_unbound; the route answered ${dv.status} ${dv.body?.message ?? JSON.stringify(dl).slice(0, 200)}; the ledger's row ${JSON.stringify(row).slice(0, 200)}`);
  const evf = await lastEvent(exp.id, 'export.delivery_failed');
  if (row !== null && evf !== null && (evf.details?.delivery_id === row.delivery_id || JSON.stringify(evf.details).includes(row.delivery_id))) ok(`the ledger: ${deliveryLine(row)}; the receipt column holds the failure ${JSON.stringify(row.receipt).slice(0, 200)}; the event export.delivery_failed at ${iso(evf.occurred_at)}`);
  else bad(`the failed delivery's row or event: row ${row === null ? 'NONE' : row.state}, event ${evf === null ? 'NONE' : 'present'}`);
  if (row !== null && !/Bearer |EYE_DST_[A-Z0-9_]+=/.test(JSON.stringify(row))) note(`nothing left this process: the reference ${HTTPS_REF} is not bound in the API's environment, so the gate refused before the egress was built — no DNS lookup, no connection; the row names the reference, never a value`);
  note(`DEMONSTRATION vs PRODUCTION: this is the production kind's gate shown without a network. The activation step: the customer's reachable https endpoint declared, one line ${HTTPS_REF}=<the bearer token> in the API process's environment, then the same delivery act — the egress POSTs the tar with the digests, the scheme, the key id and the signature in its headers, verifies TLS, follows no redirect, and records the endpoint's JSON answer as the receipt (acknowledged when it verifies both digests). The egress path itself — an unresolvable host → transport, a loopback address → egress_refused — is proven by the harness H1`);
}

/* ── 8. THE REVOCATION ───────────────────────────────────────────────────── */
console.log('\n8. THE REVOCATION — H. Bergmann revokes the package: the download refused, a further delivery refused; the deliveries stay recorded; no notice reaches the destination');
if (exp === null || pkg === null) bad('no export to revoke');
else {
  const rv = await revoke(exp.id, 'the package was delivered and acknowledged; it is not to be served again');
  if (rv.ok) ok(`H. Bergmann revoked the package: ${JSON.stringify(rv.body.revocation).slice(0, 200)}; bytes removed ${rv.body.bytes?.removed}; the package directory is ${existsSync(join(vaultRoot('export'), T, D, exp.id)) ? 'PRESENT' : 'GONE'}`); else fail('revoke (h.bergmann)', rv);
  const dl = await downloadAs(pn, novak, exp.id);
  if (dl.status === 409 && /revoked/i.test(String(dl.body?.message ?? ''))) ok(`the download refused: 409 ${dl.body.message}`); else bad(`the download after the revocation answered ${dl.status} ${dl.body?.message ?? ''}`);
  const dv = await deliver(exp.id, STATION_KEY);
  if (dv.status === 409 && /revoked/i.test(String(dv.body?.message ?? ''))) ok(`a further delivery refused: 409 ${dv.body.message}`); else bad(`a delivery after the revocation answered ${dv.status} ${dv.body?.message ?? JSON.stringify(dv.body?.delivery ?? null).slice(0, 200)}`);
  const rd = await exportGet(exp.id);
  if (rd.status === 409) ok(`the read refused: 409 ${rd.body?.message ?? ''}`); else note(`the read after the revocation answered ${rd.status}`);
  const rows = await deliveryRows(exp.id);
  const ls = await deliveriesList(exp.id);
  const listed = ls.ok ? (ls.body.deliveries ?? []) : [];
  if (rows.length >= 2 && rows.some((r) => r.state === 'acknowledged') && rows.some((r) => r.state === 'failed') && (!ls.ok || listed.length === rows.length)) ok(`the deliveries stay recorded (${rows.length}): ${rows.map(deliveryLine).join('; ')}${ls.ok ? ` — the list route (retention.read) serves the same ${listed.length}` : ` — the list route answered ${ls.status}`}`);
  else bad(`the deliveries after the revocation: ${rows.map(deliveryLine).join('; ') || 'none'}; the list route ${ls.status} ${listed.length}`);
  const stationTar = station === null ? null : join(String(field(station, 'endpoint') ?? STATION), T, D, exp.id, 'package.tar');
  note(`no notice reaches the destination: the recipient's copy is out of the product's custody (${stationTar !== null && existsSync(stationTar) ? `the station still holds package.tar and its receipt — the demonstration's record, left in place` : 'the station\'s files as the recipient left them'}); the revocation is recorded and the read route says so — a revocation notice to the destination is recorded honestly as REMAINING`);
}

/* ── 9. THE STATE ────────────────────────────────────────────────────────── */
console.log('\n9. THE STATE — tier/state\'s schedules (the retired one), the tenant\'s keys, the domain\'s destinations, the deliveries of the action');
{
  const st = await tierStateAs(cm, dvorak);
  if (!st.ok) fail('tier/state (m.dvorak)', st);
  else {
    const s = st.body.state;
    ok(`M. Dvořák reads the cold tier's state: HTTP ${st.status}`);
    note(`schedules: ${listLine(s.schedules ?? [], (x) => `${short(x.schedule_id)} ${x.action_kind} of profile "${x.retention_profile}" after ${x.due_after} (${x.state}${x.retired_at ? `, retired ${iso(x.retired_at)}` : ''}; last evaluation ${JSON.stringify(x.last_evaluation ?? {})})`)}`);
    note(`tiers: hot ${s.tiers.hot.manifests} manifest(s) / ${s.tiers.hot.bytes} bytes, archive ${s.tiers.archive.manifests} / ${s.tiers.archive.bytes}; policy ${s.policy.declared ? `declared (version ${s.policy.version})` : 'undeclared'}`);
  }
  const ks = await listKeysAs(pn, novak);
  if (ks.ok) note(`the tenant's signing keys: ${listLine(ks.body.keys ?? [], keyLine)}`); else fail('signing-keys/list (p.novak)', ks);
  const ds = await listDestinationsAs(pn, novak);
  if (ds.ok) note(`the domain's destinations: ${listLine(ds.body.destinations ?? [], destinationLine)}`); else fail('destinations/list (p.novak)', ds);
  if (exp !== null) {
    const ls = await deliveriesList(exp.id);
    if (ls.ok) note(`the deliveries of export ${short(exp.id)}: ${listLine(ls.body.deliveries ?? [], deliveryLine)}`); else fail('deliveries/list (p.novak)', ls);
  }
  note(`the scratch directory ${scratch} holds the downloaded tar and its flipped copy; the station directory keeps this run's package, delivery.json and receipt.json as the demonstration's record`);
}

console.log('\nSHOWN ON THE DEMONSTRATION: the governed SCHEDULE RETIREMENT (the row keeps its evaluation and the actions it opened keep their events; the ledger\'s schedule.retired; an evaluation reads it no more), the DEMONSTRATION KEY declared by reference (the public key recorded and served, the private value never leaving the API process), the two DESTINATION kinds (the transfer station of the disconnected path; the https production kind blocked by its unbound credential), the SIGNED EXPORT (scheme eye-customer-export/2 over the package digest, the archive digest and the expiry recorded at the build), the governed DOWNLOAD of one deterministic tar (verified offline with the public key; a flipped byte detected), the DELIVERY to the transfer station with the product\'s files, the recipient\'s receipt collected and the exchange ACKNOWLEDGED, the production path\'s gate recorded as a FAILED delivery before any egress, and the REVOCATION that refuses the download and further deliveries while the deliveries stay recorded.');
console.log('PROVEN BY THE HARNESS ALONE (apps/api/test/int/phase6-retention-b13.test.ts): the https egress path — an unresolvable host recorded transport, a loopback address egress_refused, no credential value in any row (H1); a receipt naming other digests → mismatched, a receipt that is not JSON → refused with the row kept, a stale receipt of another delivery refused by its delivery_id, a second delivery of the same package accepted with the identical tar (T1); a package file tampered on disk → the download refused 409 and the verifier failing; the expiry refusals of the download and the delivery (A1); an export refused at execution when the active key\'s reference is unbound in the process (E1); a schedule retired twice, an under-length reason, the steward\'s retirement (S1); the declaration refusals of keys and destinations (K1, D1); the holders of every new action (P1).');

await su.end();
console.log(`\n=== ${failureCount() === 0 ? 'the act completed with every scene producing its effect' : `${failureCount()} scene step(s) did not produce the effect claimed`} ===`);
process.exit(failureCount() === 0 ? 0 : 1);
