/**
 * Tenancy — CP-TEN-01 (ADR-P0-04; ES-08; Gate-2.1 C2).
 *
 * Gate-2.2 C8: every method takes an ACTION-SPECIFIC capability, never a
 * transaction. A read method takes TenancyReads (no creation ports at all); a
 * write method takes TenancyWrites. The relation is never a parameter, so this
 * service cannot express a query against another module's tables.
 */
import { Injectable } from '@nestjs/common';
import type { TenancyReads, TenancyWrites } from '../shared/capabilities.js';

export interface TenantRecord {
  id: string;
  name: string;
  status: string;
  residency_profile: string;
  retention_profile: string;
  created_at: Date;
  activated_at: Date | null;
}

@Injectable()
export class TenancyService {
  /**
   * Gate-2.2 C6: the id is generated by the ROUTE before the capability is minted,
   * so the capability is bound to this exact target and the port can enforce it.
   */
  async createTenant(cap: TenancyWrites, id: string, name: string, residency: string): Promise<TenantRecord> {
    await cap.createTenant(id, name, residency);
    return (await cap.readTenants().selectAll().where('id', '=', id as never)
      .executeTakeFirstOrThrow()) as unknown as TenantRecord;
  }

  async createDomain(
    cap: TenancyWrites, id: string, tenantId: string, name: string,
  ): Promise<{ id: string; name: string; status: string }> {
    await cap.createDomain(id, tenantId, name);
    return { id, name, status: 'active' };
  }

  async listTenants(cap: TenancyReads): Promise<TenantRecord[]> {
    return (await cap.readTenants().selectAll().orderBy('created_at' as never).execute()) as unknown as TenantRecord[];
  }

  async listDomains(cap: TenancyReads, tenantId: string): Promise<unknown[]> {
    return cap.readDomains().selectAll()
      .where('tenant_id', '=', tenantId as never).orderBy('created_at' as never).execute();
  }

  /** Explicitly authorized read model for a DOMAIN principal's own tenant. */
  async myTenant(cap: TenancyReads): Promise<{ id: string; name: string; status: string } | undefined> {
    return cap.myTenant();
  }
}
