/**
 * CP-6 B35 part `explanation` (migration 0101 §E) — THE GOVERNED EXPLANATION, ITS FAITHFULNESS, CONTEST AND APPEAL (F-P6-03: App. L,
 * V00-T-027, AI-04-001..004, AI-63-005, AI-64-002..004, AI-ADR-014, AI-C046, AI-C047, AG-040, AR-019, V05-T-005, V05-T-022, V10-T-007/-008),
 * through the real database and controllers (POST …/decisions/explanations/… and …/decisions/appeals/…, the decision routes of the fixtures),
 * on the world of `bootDecisionWorld` and this file's own humans with sessions (the ports compare the acting principal):
 *
 *   e1 THE EXPLANATION OBJECT: generated by the SERVER from a package version's preserved state — items separated into the five categories
 *      (source evidence, deterministic transformation, model inference, agent judgment — the decision agent's drafted option —, human
 *      assessment), counter-evidence (the dissent), competing hypotheses (the options not chosen), likelihood vs impact and confidence vs
 *      evidence quality kept apart, the App. L contract field by field, the integrity digest; generated again on the same state it is
 *      UNCHANGED; a forecast's (its source, its method, its baseline as the competing hypothesis, its validation as a material limitation, a
 *      forecast probability), a run's and an option's; refusals (unknown subject, a version missing, a malformed kind, §R/§A not installed,
 *      the PDP); RECOVERY — a dissent recorded after generation makes it STALE (said so, both digests), a rendering of it refused, generated
 *      again it supersedes v1.
 *   e2 THE FAITHFULNESS CHECK v1: a rendering citing every material item stands (a human's, the decision agent's — renders only); an
 *      uncited sentence, a figure no cited item states, hidden cognition, false certainty and an omitted material item each refused
 *      (`explanation rejected (unfaithful)`, nothing written); the dry check; a superseded explanation is not rendered; the agent never
 *      opens nor adjudicates a case; RECOVERY — a faithful rendering after the refusal; a rendering contested and upheld is WITHDRAWN as
 *      unfaithful (the structured explanation stands; the explanation reads corrected).
 *   e3 CONTEST AND APPEAL: J. Weber's part (a strategy owner) contests the corridor forecast's SOURCE — standing v1, scope (the source item
 *      of the forecast's explanation), grounds, a deadline; the bench and the owners notified (decision.appeal); the bench assigns an
 *      adjudicator who is neither the appellant nor an owner; partly upheld with the correction through the observation layer and the
 *      impact (the forecast resting on the source, the options citing it); the appellant notified; closed; the forecast's explanation
 *      generated again shows the contested source and the outcome. The appeal of a DECIDED package records reopen_required (the commitment
 *      stands; no package event written). Refusals (standing, the PDP, separation, an agent adjudicator, out of step, duplicate, deadline,
 *      a draft package, unknown); RECOVERY — the appellant withdraws and opens again; an OVERDUE case (a stated superuser insert of a case
 *      opened past its deadline — the port refuses a deadline under an hour) flagged once by the tick step `appeal-deadlines` (71), then
 *      adjudicated and closed.
 *   e4 THE UNIFIED SURFACE: a subject's current explanation with its renderings and faithfulness, every version, and every case — for the
 *      forecast also the case on its source.
 *
 * Per clause a POSITIVE, a REFUSAL and a RECOVERY case. Every figure is SYNTHETIC (the fixture world's; NORDWERK's data is the
 * demonstration's). The attention agent's timer is unscheduled (the ticks are the harness's own). No real external integration is exercised:
 * the decision.appeal notifications are attention items (in-app), nothing is delivered outside.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { sql } from 'kysely';
import { uuidv7 } from 'uuidv7';
import { mkdtempSync, realpathSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { HttpException } from '@nestjs/common';
import type { AuthenticatedPrincipal } from '../../src/shared/auth-types.js';
import type { ExplanationController, AppealController } from '../../src/decision/explanation/explanation.controller.js';
import { APPEAL_DEADLINES_ORDER, APPEAL_DEADLINES_STEP } from '../../src/decision/explanation/explanation.service.js';
import { SchedulerService } from '../../src/observation/scheduling/scheduler.service.js';
import { AttentionTimerService } from '../../src/executive/attention/attention-timer.service.js';
import { ATTENTION_TIMER_DIGEST, ATTENTION_TIMER_VERSION } from '../../src/executive/attention/timer-identity.js';
import { AttentionTickRegistry } from '../../src/executive/attention/tick.js';
import { asObservationRefusal } from '../../src/observation/observation-errors.js';
import { Phase4Harness } from './phase4-helpers.js';
import { bootDecisionWorld, decisionCalls, type DecisionWorld } from './phase6-fixtures.js';
import type { AnyDb } from './helpers.js';

const VAULT_DIR = realpathSync(mkdtempSync(join(tmpdir(), 'eye-b35-explanation-vault-')));
process.env['EYE_VAULT_QUARANTINE_ROOT'] = join(VAULT_DIR, 'quarantine');
process.env['EYE_VAULT_EVIDENCE_ROOT'] = join(VAULT_DIR, 'evidence');
process.env['EYE_VAULT_ARCHIVE_ROOT'] = join(VAULT_DIR, 'archive');
process.env['EYE_VAULT_EXPORT_ROOT'] = join(VAULT_DIR, 'export');

type Row = Record<string, unknown>;
type Item = { id: string; category: string; role: string; ref: Row; field: string | null; statement: string; material: boolean };
type Xpl = Row & { explanation_id: string; explanation_version: number; items: Item[]; counter_evidence: string[]; competing_hypotheses: string[]; limitations: string[]; uncertainty: Row;
  contract: Row; integrity_digest: string; subject_digest: string; status: Row & { state: string; faithfulness_state: string; stale: boolean; stale_reason: string | null; superseded_by: string | null };
  renderings?: Array<Row & { rendering_id: string; state: string; faithfulness: string; renderer_kind: string }>; cases?: Row[]; unchanged?: boolean; by_category?: Row };
type Case = Row & { case_id: string; state: string; outcome: string | null; effect: (Row & { kind: string }) | null; impact: Row | null; standing: Row; overdue: boolean; deadline_at: string; adjudicator_principal_id: string | null };

let h: Phase4Harness; let su: AnyDb; let w: DecisionWorld; let c: ReturnType<typeof decisionCalls>;
let xc: ExplanationController; let ac: AppealController; let scheduler: SchedulerService; let timer: AttentionTimerService; let agentId = '';
let weber: AuthenticatedPrincipal; let analyst: AuthenticatedPrincipal; let forecaster: AuthenticatedPrincipal; let outsider: AuthenticatedPrincipal; let agentBench: AuthenticatedPrincipal;
let dadmin: AuthenticatedPrincipal; let tenantAdmin: AuthenticatedPrincipal;
/** What the cases leave one another. */
let PKG = { pkg: '', v: 0, digest: '' }; let XPKG = ''; let XFCT = ''; let XFCT_SOURCE_ITEM = ''; let SOURCE = ''; let STALE = { pkg: '', v: 0 }; let XSTALE1 = ''; let XSTALE2 = '';
let RENDERING = ''; let SOURCE_CASE = '';
const T = () => h.fx.tenantId; const D = () => h.fx.domainId;

/* ───────────── refusals (the B21/B27/B31 idiom) ───────────── */
const refusal = async (p: Promise<unknown>): Promise<{ status: number | null; message: string }> => {
  const e = await p.then(() => { throw new Error('the call should have been refused'); }, (err: unknown) => err);
  const mapped = e instanceof HttpException ? e : asObservationRefusal(e, 'harness');
  if (mapped === null) return { status: null, message: e instanceof Error ? e.message : String(e) };
  const r = mapped.getResponse() as { message?: string };
  return { status: mapped.getStatus(), message: String(r.message ?? (e instanceof Error ? e.message : '')) };
};
const refused = async (p: Promise<unknown>, re: RegExp, status: number): Promise<string> => {
  const r = await refusal(p);
  expect(r.message).toMatch(re);
  expect(r.status, r.message).toBe(status);
  return r.message;
};
const evidence = (caseName: string, e: Row): void => console.log(`B35 EXPLANATION EVIDENCE ${caseName}: ${JSON.stringify(e)}`);
const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const obj = (v: unknown): Row => (v !== null && typeof v === 'object' ? (v as Row) : {});

/* ───────────── the rows ───────────── */
const rows = async (q: ReturnType<typeof sql>) => (await q.execute(su)).rows as Row[];
const itemsOf = async (caseId: string) => rows(sql`select item_id::text, state, owner_principal_id::text as owner, route_roles, subject_kind, cause_event_type, details from executive.attention_items
  where signal_class = 'decision.appeal' and subject_id = ${caseId}::uuid order by created_at`);
const caseEvents = async (caseId: string) => (await rows(sql`select event from decision.appeal_events where case_id = ${caseId}::uuid order by occurred_at, event_id`)).map((r) => String(r['event']));
const packageEvents = async (pkg: string) => (await rows(sql`select event from decision.package_events where package_id = ${pkg}::uuid order by occurred_at, event_id`)).map((r) => String(r['event']));
const renderingCount = async () => Number((await rows(sql`select count(*)::int as n from decision.explanation_renderings`))[0]?.['n'] ?? 0);

/* ───────────── the routes ───────────── */
const req = (as: AuthenticatedPrincipal, action: string, type: string, id: string | null) => h.req(as, action, type, id, 'decision');
const generate = async (as: AuthenticatedPrincipal, subjectKind: string, subjectId: string, subjectVersion: number | null = null) =>
  ((await xc.generate(req(as, 'decision.explanation.generate', 'XPL', null), T(), D(), { payload: { subjectKind, subjectId, subjectVersion } })) as unknown as { explanation: Xpl }).explanation;
const readX = async (id: string, as: AuthenticatedPrincipal = analyst) => ((await xc.read(req(as, 'decision.explanation.read', 'XPL', id), T(), D(), id)) as unknown as { explanation: Xpl }).explanation;
const surface = async (subjectKind: string, subjectId: string, subjectVersion: number | null = null, as: AuthenticatedPrincipal = analyst) =>
  ((await xc.surface(req(as, 'decision.explanation.read', 'XPL', subjectId), T(), D(), { payload: { subjectKind, subjectId, subjectVersion } })) as unknown as { surface: Row & { explanation: Xpl | null; versions: Row[]; cases: Case[]; subject: Row } }).surface;
const check = async (id: string, sentences: Row[]) => ((await xc.check(req(analyst, 'decision.explanation.read', 'XPL', id), T(), D(), id, { payload: { sentences } })) as unknown as { check: Row & { faithful: boolean; findings: Row[] } }).check;
const render = (as: AuthenticatedPrincipal, id: string, sentences: Row[], audience: Row = { role: 'executive', language: 'en' }) =>
  xc.render(req(as, 'decision.explanation.render', 'XPL', id), T(), D(), id, { payload: { audience, sentences } }) as unknown as Promise<{ rendering: Row & { rendering_id: string; renderer_kind: string; faithfulness: string; check_result: Row } }>;
const open = (as: AuthenticatedPrincipal, payload: Row) => ac.open(req(as, 'decision.appeal.open', 'APL', null), T(), D(), { payload }) as unknown as Promise<{ case: Case }>;
const readCase = async (id: string, as: AuthenticatedPrincipal = analyst) => ((await ac.read(req(as, 'decision.appeal.read', 'APL', id), T(), D(), id)) as unknown as { case: Case & { events: Row[]; subject_now: Row } }).case;
const assign = (as: AuthenticatedPrincipal, id: string, adjudicator: string) => ac.assign(req(as, 'decision.appeal.adjudicate', 'APL', id), T(), D(), id, { payload: { adjudicator } }) as unknown as Promise<{ case: Case }>;
const adjudicate = (as: AuthenticatedPrincipal, id: string, payload: Row) => ac.adjudicate(req(as, 'decision.appeal.adjudicate', 'APL', id), T(), D(), id, { payload }) as unknown as Promise<{ case: Case }>;
const close = (as: AuthenticatedPrincipal, id: string, note: string) => ac.close(req(as, 'decision.appeal.close', 'APL', id), T(), D(), id, { payload: { note } }) as unknown as Promise<{ case: Case }>;
const list = async (payload: Row = {}) => ((await ac.list(req(analyst, 'decision.appeal.read', 'APL', null), T(), D(), { payload })) as unknown as { cases: Case[] }).cases;
const tick = async (day: number) => {
  const t = await timer.tickNow({ tenantId: T(), domainId: D(), agentId, scheduledAt: new Date(Date.UTC(2036, 5, day)) });
  expect(t.outcome, JSON.stringify(t.stopReason)).toBe('finished');
  const outputs = obj(t.run?.outputs);
  return obj(obj(outputs['steps'] ?? outputs)[APPEAL_DEADLINES_STEP]);
};
/** A rendering that cites every MATERIAL item and the conclusion, with no figure (faithful under v1). */
const faithfulSentences = (x: Xpl): Row[] => {
  const material = x.items.filter((i) => i.material).map((i) => i.id);
  const conclusion = x.items.filter((i) => i.role === 'conclusion').map((i) => i.id);
  const out: Row[] = [{ text: 'The conclusion rests on the cited items of this explanation.', cites: conclusion }];
  if (material.length > 0) out.push({ text: 'Its material limitations, risks, constraints and dissent remain in force.', cites: material });
  return out;
};

beforeAll(async () => {
  h = await Phase4Harness.boot();
  su = h.su;
  const { ExplanationController: Xc, AppealController: Ac } = await import('../../src/decision/explanation/explanation.controller.js');
  xc = h.app.get(Xc); ac = h.app.get(Ac);
  scheduler = h.app.get(SchedulerService); timer = h.app.get(AttentionTimerService);
  weber = await h.humanWithSession(['strategy_owner'], 'b35e-weber');
  analyst = await h.humanWithSession(['domain_analyst'], 'b35e-analyst');
  forecaster = await h.humanWithSession(['forecast_owner'], 'b35e-forecaster');
  outsider = await h.humanWithSession(['collection_manager'], 'b35e-outsider');
  agentBench = await h.humanWithSession(['decision_agent', 'decision_authority'], 'b35e-agent-bench');
  dadmin = await h.humanWithSession(['domain_admin'], 'b35e-dadmin');
  tenantAdmin = await h.humanWithSession(['tenant_admin'], 'b35e-tenant-admin', 'TENANT');
  w = await bootDecisionWorld(h); c = decisionCalls(h, w);
  // THE PACKAGE (SYNTHETIC): the fixture draft (status quo vs reroute, citing runs and an evidence version), the decision agent's drafted
  // air-bridge card beside them, proposed, a dissent recorded, approved and committed — a DECIDED package
  const d = await c.fullDraft({ as: w.owner });
  await c.option(d.pkg, d.v, { key: 'air-bridge', title: 'Air-bridge the magnets (drafted by the agent)', kind: 'intervention', consequences: [{ kind: 'run', id: w.airId }] }, w.agent);
  const pr = await c.propose(d.pkg, d.v, w.owner);
  await c.dissent(d.pkg, d.v, { position: 'prefer the air bridge', rationale: 'The Cape adds two weeks the line cannot absorb (B35 harness, synthetic).' }, w.approver);
  await c.approve(d.pkg, d.v, { decision: 'approve', versionDigest: pr.proposal.versionDigest, rationale: 'The reroute keeps the line running; the premium is acceptable.' }, w.approver);
  await c.commit(d.pkg, d.v, pr.proposal.versionDigest, w.authority);
  PKG = { pkg: d.pkg, v: d.v, digest: pr.proposal.versionDigest };
  // THE ATTENTION AGENT: the tick's host (its timer unscheduled; the ticks below are the harness's own)
  const r = await w.exec.registerAgent(h.req(tenantAdmin, 'agent.register', 'AGT', null, 'platform.administration'), T(), D(), { payload: { kind: 'attention', version: ATTENTION_TIMER_VERSION,
    codeDigest: ATTENTION_TIMER_DIGEST, ownerPrincipalId: w.executive.principalId, escalationPrincipalId: dadmin.principalId, budgets: { max_reads: 50, max_gateway_calls: 0, max_elapsed_ms: 120_000, tick_every_seconds: 86_400 } } } as never) as unknown as { agent: { agentId: string } };
  agentId = r.agent.agentId;
  await sleep(1500);
  await scheduler.unscheduleAttentionTick(T(), D());
}, 600_000);

afterAll(async () => {
  try { await scheduler.unscheduleAttentionTick(T(), D()); } catch { /* none */ }
  try { await scheduler.obliterateAttentionTicksForTests(T(), D()); } catch { /* the queue may not exist */ }
  await h?.close();
}, 120_000);

describe('B35 explanation · e1 · the governed explanation object (App. L, AI-04-001..003, AI-63-005, AI-ADR-014, V05-T-022)', () => {
  it('e1 · POSITIVE: the server generates the decided package version\'s explanation — five categories, counter-evidence, competing hypotheses, the uncertainty questions apart, the App. L contract, digest-bound; again: unchanged', async () => {
    const before = await packageEvents(PKG.pkg);
    const x = await generate(analyst, 'package_version', PKG.pkg, PKG.v);
    XPKG = x.explanation_id;
    expect(x).toMatchObject({ explanation_version: 1, subject_kind: 'package_version', subject_version: PKG.v, generator: 'dse-explain@1', unchanged: false, status: { state: 'current', stale: false } });
    expect(new Set(x.items.map((i) => i.category))).toEqual(new Set(['source_evidence', 'deterministic_transformation', 'model_inference', 'agent_judgment', 'human_assessment']));
    expect(x.items.map((i) => i.id)).toEqual(x.items.map((_, k) => `I${k + 1}`));
    // the agent's drafted card is an AGENT JUDGMENT and a competing hypothesis; the chosen option's card supports the conclusion
    const agentCard = x.items.find((i) => i.ref['kind'] === 'option' && i.ref['key'] === 'air-bridge')!;
    expect(agentCard).toMatchObject({ category: 'agent_judgment', role: 'competing_hypothesis' });
    expect(x.items.find((i) => i.ref['kind'] === 'option' && i.ref['key'] === 'reroute')).toMatchObject({ category: 'human_assessment', role: 'support' });
    expect(x.items.find((i) => i.role === 'conclusion')!.statement).toMatch(/^The owner chose option "reroute"/);
    expect(x.items.find((i) => i.ref['kind'] === 'run' && i.ref['id'] === w.rerouteId)).toMatchObject({ category: 'model_inference' });
    expect(x.items.find((i) => i.ref['kind'] === 'evidence')).toMatchObject({ category: 'source_evidence' });
    // the dissent is counter-evidence (material); the options not chosen are the competing hypotheses
    const dissent = x.items.find((i) => i.role === 'dissent')!;
    expect(dissent).toMatchObject({ category: 'human_assessment', material: true });
    expect(dissent.statement).toMatch(/^Dissent — prefer the air bridge/);
    expect(x.counter_evidence).toContain(dissent.id);
    expect(x.competing_hypotheses).toContain(agentCard.id);
    expect(x.competing_hypotheses).toContain(x.items.find((i) => i.ref['key'] === 'status-quo')!.id);
    // AI-63-005: likelihood, impact, confidence and evidence quality are separate answers (no governed probability is cited: not stated)
    expect(Object.keys(x.uncertainty).sort()).toEqual(['confidence', 'disagreement', 'evidence_quality', 'impact', 'likelihood']);
    expect(obj(x.uncertainty['likelihood'])['kind']).toBe('not_stated');
    expect(obj(x.uncertainty['impact'])['kind']).toBe('stated_consequence');
    expect(obj(x.uncertainty['evidence_quality'])['grade']).toBe('synthetic (demonstration grade)');
    expect(obj(x.uncertainty['disagreement'])['dissent']).toBe(1);
    // App. L: every field present, inapplicable or missing with its reason; the digest binds it
    for (const k of ['explanation_id', 'product_and_version', 'decision_use', 'audience_profile', 'conclusion', 'claim_map', 'evidence_map', 'counter_evidence', 'method', 'model_and_agent_roles',
      'assumptions', 'alternatives', 'uncertainty', 'calibration_basis', 'sensitivity', 'counterfactuals', 'limitations', 'dissent', 'policy_and_authority', 'expected_effects', 'provenance_ref',
      'information_boundary', 'contest_path', 'withheld_scope', 'faithfulness_state', 'integrity_digest']) expect(x.contract, k).toHaveProperty(k);
    expect(x.contract['integrity_digest']).toBe(x.integrity_digest);
    expect(x.integrity_digest).toMatch(/^[0-9a-f]{64}$/);
    expect(x.by_category).toMatchObject({ agent_judgment: 1 });
    // the same state, generated again: the standing explanation, unchanged
    const again = await generate(w.owner, 'package_version', PKG.pkg, PKG.v);
    expect(again).toMatchObject({ explanation_id: XPKG, explanation_version: 1, unchanged: true });
    // this part writes no package event (the drafting/propose/commit lists stay pinned)
    expect(await packageEvents(PKG.pkg)).toEqual(before);
    evidence('e1', { items: x.items.length, categories: x.by_category, counter: x.counter_evidence, competing: x.competing_hypotheses, faithfulness: x.faithfulness_state });
  });

  it('e1 · POSITIVE: a forecast\'s explanation names its SOURCE, its method, the baseline as competing hypothesis, its validation as a material limitation and a forecast probability; a run\'s and an option\'s too', async () => {
    const f = await generate(weber, 'forecast', w.forecastId);
    XFCT = f.explanation_id;
    const src = f.items.find((i) => i.ref['kind'] === 'source')!;
    expect(src).toMatchObject({ category: 'source_evidence', role: 'support' });
    SOURCE = String(src.ref['id']); XFCT_SOURCE_ITEM = src.id;
    expect(SOURCE).toBe(h.fx.sourceId);
    expect(f.items.find((i) => i.field === 'method')).toMatchObject({ category: 'model_inference' });
    expect(f.items.find((i) => i.field === 'baseline_method')).toMatchObject({ category: 'model_inference', role: 'competing_hypothesis' });
    expect(f.items.find((i) => i.field === 'validation')).toMatchObject({ category: 'deterministic_transformation', role: 'limitation', material: true });
    expect(f.items.find((i) => i.field === 'series')).toMatchObject({ category: 'deterministic_transformation' });
    expect(obj(f.uncertainty['likelihood'])['kind']).toBe('forecast_probability');
    expect(obj(f.uncertainty['impact'])['kind']).toBe('not_stated');
    const run = await generate(analyst, 'run', w.controlId);
    expect(run.items.find((i) => i.field === 'decision_use')).toMatchObject({ category: 'deterministic_transformation' });
    expect(run.items[0]).toMatchObject({ category: 'model_inference', role: 'conclusion' });
    const optionId = String((await rows(sql`select option_id::text from decision.options where package_id = ${PKG.pkg}::uuid and version = ${PKG.v} and key = 'reroute'`))[0]!['option_id']);
    const opt = await generate(analyst, 'option', optionId);
    expect(opt.items[0]!.statement).toMatch(/is the chosen option$/);
    evidence('e1-forecast', { source: SOURCE, likelihood: f.uncertainty['likelihood'], run_items: run.items.length, option_items: opt.items.length });
  });

  it('e1 · REFUSAL: an unknown subject 404, a package version without its version 422, a malformed kind 422, §R/§A not installed (or unknown), the PDP', async () => {
    await refused(generate(analyst, 'forecast', uuidv7()), /^explanation rejected \(unknown_subject\)/, 404);
    await refused(generate(analyst, 'package_version', PKG.pkg), /^explanation rejected \(version\)/, 422);
    await refused(generate(analyst, 'scenario', PKG.pkg), /^explanation rejected \(subject_kind\)/, 422);
    // the seam: alone, §R and §A are not installed (unavailable, 409); combined, a random id is unknown (404)
    const r1 = await refusal(generate(analyst, 'recommendation', uuidv7()));
    expect(r1.message).toMatch(/^explanation rejected \((unavailable|unknown_subject)\)/);
    expect([404, 409]).toContain(r1.status);
    const absent = (await rows(sql`select to_regprocedure('decision.package_analysis(uuid,integer)') is null as absent`))[0]!['absent'] === true;
    const r2 = absent ? await refused(generate(analyst, 'analysis', PKG.pkg, PKG.v), /^explanation rejected \(unavailable\): the analysis part/, 409) : 'installed: the integrator asserts the seam';
    await refused(generate(outsider, 'forecast', w.forecastId), /./, 403);
    await refused(readX(uuidv7()), /^explanation rejected \(unknown_explanation\)/, 404);
    evidence('e1-refusal', { recommendation: r1, analysis: r2.slice(0, 80) });
  });

  it('e1 · RECOVERY: a dissent recorded after generation makes the explanation STALE (said so, with both digests); its rendering is refused; generated again, v2 supersedes v1', async () => {
    const p = await c.proposed({ as: w.owner });
    STALE = { pkg: p.pkg, v: p.v };
    const x1 = await generate(analyst, 'package_version', p.pkg, p.v);
    XSTALE1 = x1.explanation_id;
    expect(x1.status.state).toBe('current');
    await c.dissent(p.pkg, p.v, { position: 'wait one more sailing', rationale: 'A week of observation could change the ranking (B35 harness, synthetic).' }, w.approver);
    const stale = await readX(XSTALE1);
    expect(stale.status).toMatchObject({ state: 'stale', stale: true });
    expect(stale.status.stale_reason).toMatch(/^the subject's state moved since generation: digest [0-9a-f]{64} then, [0-9a-f]{64} now/);
    await refused(render(analyst, XSTALE1, faithfulSentences(x1)), /^explanation rejected \(stale\)/, 409);
    const x2 = await generate(analyst, 'package_version', p.pkg, p.v);
    XSTALE2 = x2.explanation_id;
    expect(x2).toMatchObject({ explanation_version: 2, supersedes: XSTALE1, unchanged: false, status: { state: 'current' } });
    expect(x2.items.filter((i) => i.role === 'dissent').map((i) => i.statement)).toEqual([expect.stringMatching(/^Dissent — wait one more sailing/)]);
    expect((await readX(XSTALE1)).status).toMatchObject({ state: 'superseded', superseded_by: XSTALE2, faithfulness_state: 'superseded' });
    evidence('e1-recovery', { v1: XSTALE1, v2: XSTALE2, reason: stale.status.stale_reason?.slice(0, 60) });
  });
});

describe('B35 explanation · e2 · the faithfulness check v1 (AI-04-004, AI-64-004, AG-040, AR-019)', () => {
  it('e2 · REFUSAL: an uncited sentence, a figure no cited item states, hidden cognition, false certainty and an omitted material item are refused — nothing written; the dry check names them; a superseded explanation is not rendered', async () => {
    const x = await readX(XPKG);
    const n0 = await renderingCount();
    const conclusion = x.items.find((i) => i.role === 'conclusion')!.id;
    await refused(render(analyst, XPKG, [{ text: 'The reroute is the right call for the line.', cites: [] }]), /^explanation rejected \(unfaithful\): .*sentence 1 unsupported/, 422);
    await refused(render(analyst, XPKG, [...faithfulSentences(x), { text: 'It saves 999999 units of cost over the quarter.', cites: [conclusion] }]), /unsupported_figure: the figure 999999 is stated by no cited item/, 422);
    await refused(render(analyst, XPKG, [...faithfulSentences(x), { text: 'The model believes the corridor reopens soon.', cites: [conclusion] }]), /hidden_cognition/, 422);
    await refused(render(analyst, XPKG, [...faithfulSentences(x), { text: 'The reroute is guaranteed to keep the line running.', cites: [conclusion] }]), /false_certainty/, 422);
    await refused(render(analyst, XPKG, [faithfulSentences(x)[0]!]), /omits_material: material item\(s\)/, 422);
    await refused(render(analyst, XPKG, [{ text: 'An item that does not exist.', cites: ['I999'] }]), /unknown_item/, 422);
    expect(await renderingCount()).toBe(n0);
    const dry = await check(XPKG, [{ text: 'The model knows best here.', cites: [] }]);
    expect(dry.faithful).toBe(false);
    expect(dry.findings.map((f) => f['rule'])).toEqual(['unsupported', 'hidden_cognition', 'omits_material']);
    await refused(render(analyst, XSTALE1, faithfulSentences(await readX(XSTALE1))), /^explanation rejected \(state\): .*superseded by v2/, 409);
    await refused(render(analyst, XPKG, faithfulSentences(x), { role: 'x', language: 'en' }), /^explanation rejected \(audience\)/, 422);
    await refused(render(outsider, XPKG, faithfulSentences(x)), /./, 403);
    expect(await renderingCount()).toBe(n0);
  });

  it('e2 · POSITIVE: a rendering citing every material item stands (a human\'s); the decision agent renders too (renders only) — never opens nor adjudicates a case', async () => {
    const x = await readX(XPKG);
    const r = (await render(w.owner, XPKG, faithfulSentences(x), { role: 'executive', language: 'en', accessibility: 'screen reader' })).rendering;
    expect(r).toMatchObject({ renderer_kind: 'human', faithfulness: 'faithful', state: 'standing', check_result: { rule: 'faithfulness v1', faithful: true, findings: [] } });
    const a = (await render(w.agent, XPKG, faithfulSentences(x), { role: 'board', language: 'en' })).rendering;
    expect(a).toMatchObject({ renderer_kind: 'agent', faithfulness: 'faithful' });
    RENDERING = a.rendering_id;
    await refused(open(w.agent, { subjectKind: 'explanation', subjectId: XPKG, scope: { statement: 'the agent contests its own rendering' }, grounds: 'an agent may not open a contest of anything' }), /./, 403);
    await refused(open(agentBench, { subjectKind: 'explanation', subjectId: XPKG, scope: { statement: 'an agent with a bench role' }, grounds: 'an agent never opens a case, whatever its roles' }),
      /^appeal rejected \(actor\): .*an agent never opens one/, 403);
    const back = await readX(XPKG);
    expect(back.renderings!.map((x0) => [x0.renderer_kind, x0.faithfulness])).toEqual([['human', 'faithful'], ['agent', 'faithful']]);
    evidence('e2', { renderings: back.renderings!.length });
  });

  it('e2 · RECOVERY: a rendering contested as changing the meaning is upheld — WITHDRAWN as unfaithful; the structured explanation stands and reads corrected', async () => {
    const k = (await open(weber, { subjectKind: 'explanation', subjectId: XPKG, explanationId: XPKG, scope: { statement: 'the board rendering drops the decision\'s caveats', rendering_id: RENDERING },
      grounds: 'The board rendering compresses the caveats into one line the board will not read as binding.' })).case;
    await assign(w.authority, k.case_id, w.authority2.principalId);
    // the agent never adjudicates (a principal passing the PDP: the port refuses it)
    await refused(assign(w.authority, k.case_id, agentBench.principalId), /^appeal rejected \(adjudicator\)/, 422);
    const adj = (await adjudicate(w.authority2, k.case_id, { outcome: 'upheld', rationale: 'The rendering reads as a recommendation without its caveats; it is withdrawn.', correction: 'Render again citing each caveat in its own sentence (decision layer).' })).case;
    expect(adj.effect).toMatchObject({ kind: 'rendering_withdrawn', rendering_id: RENDERING });
    const x = await readX(XPKG);
    expect(x.renderings!.find((r) => r.rendering_id === RENDERING)).toMatchObject({ state: 'withdrawn', faithfulness: 'unfaithful' });
    expect(x.renderings!.filter((r) => r.state === 'standing')).toHaveLength(1);
    expect(x.status).toMatchObject({ state: 'current', faithfulness_state: 'corrected' });
    // a rendering's withdrawal is its only change, once
    await expect(sql`update decision.explanation_renderings set state = 'standing' where rendering_id = ${RENDERING}::uuid`.execute(su)).rejects.toThrow(/changes only by its withdrawal, once/);
    await close(w.authority2, k.case_id, 'The rendering is withdrawn; the owner is told.');
    evidence('e2-recovery', { case: k.case_id, effect: adj.effect });
  });
});

describe('B35 explanation · e3 · contest and appeal cases (AI-64-002/-003, AI-C047, V10-T-007)', () => {
  it('e3 · POSITIVE (the demonstration scene): Weber contests the corridor forecast\'s SOURCE — a case with a deadline, the bench and owners notified, assigned, partly upheld with the correction and the impact, closed; the forecast\'s explanation then shows the contested source and the outcome', async () => {
    const due = new Date(Date.parse(String((await rows(sql`select clock_timestamp() + interval '10 days' as t`))[0]!['t']))).toISOString();
    const k = (await open(weber, { subjectKind: 'source', subjectId: SOURCE, explanationId: XFCT, scope: { statement: 'the source behind the corridor forecast', items: [XFCT_SOURCE_ITEM], fields: ['source'] },
      grounds: 'The source counts transits at the strait, not at the corridor\'s chokepoint; the forecast rests on the wrong place (synthetic).', evidence: [{ kind: 'note', statement: 'the publisher\'s own coverage note (synthetic)' }], deadlineAt: due })).case;
    SOURCE_CASE = k.case_id;
    expect(k).toMatchObject({ state: 'opened', subject_kind: 'source', subject_id: SOURCE, standing: { rule: 'standing v1', basis: 'role:strategy_owner' }, adjudicator_principal_id: null, overdue: false });
    expect(Math.abs(Date.parse(k.deadline_at) - Date.parse(due))).toBeLessThan(1000);
    const opened = await itemsOf(k.case_id);
    expect(opened.find((i) => i['owner'] === null)).toMatchObject({ subject_kind: 'appeal_case', cause_event_type: 'appeal.notified', details: expect.objectContaining({ reason: 'adjudicator_needed' }) });
    expect(opened.find((i) => i['owner'] === null)!['route_roles']).toEqual(['decision_authority', 'executive', 'domain_admin', 'auditor']);
    const assigned = (await assign(w.authority, k.case_id, w.authority2.principalId)).case;
    expect(assigned).toMatchObject({ state: 'under_review', adjudicator_principal_id: w.authority2.principalId });
    expect((await itemsOf(k.case_id)).find((i) => i['owner'] === w.authority2.principalId)).toMatchObject({ state: 'open', details: expect.objectContaining({ reason: 'adjudication_assigned' }) });
    const adj = (await adjudicate(w.authority2, k.case_id, { outcome: 'partly_upheld', rationale: 'The source is right about the strait but the forecast states the corridor; the scope is corrected, not the counts.',
      correction: 'The source owner restates the source\'s coverage as the strait only (observation layer); the forecast owner re-issues with the scope named.' })).case;
    expect(adj).toMatchObject({ state: 'adjudicated', outcome: 'partly_upheld', effect: { kind: 'correction_required', owning_layer: 'observation' } });
    expect(obj(adj.impact)['forecasts']).toContain(w.forecastId);
    expect((await itemsOf(k.case_id)).find((i) => i['owner'] === weber.principalId)).toMatchObject({ details: expect.objectContaining({ reason: 'adjudicated' }) });
    const closed = (await close(w.authority2, k.case_id, 'The outcome is notified to the appellant and the source owner.')).case;
    expect(closed).toMatchObject({ state: 'closed', closure: 'resolved' });
    const ev = await caseEvents(k.case_id);
    expect(ev.filter((e) => e !== 'appeal.notified')).toEqual(['appeal.opened', 'appeal.assigned', 'appeal.adjudicated', 'appeal.closed']);
    expect(ev.filter((e) => e === 'appeal.notified')).toHaveLength((await itemsOf(k.case_id)).length);
    // the forecast's explanation, generated again, shows the contested source and the outcome (a new version; the old one reads superseded)
    const f2 = await generate(weber, 'forecast', w.forecastId);
    expect(f2.explanation_version).toBe(2);
    const contested = f2.items.find((i) => i.ref['kind'] === 'appeal_case' && i.ref['id'] === k.case_id)!;
    expect(contested).toMatchObject({ category: 'human_assessment', role: 'counter_evidence', material: true });
    expect(contested.statement).toMatch(/^Appeal on the forecast's source \(source\): .* — partly_upheld: The source is right about the strait/);
    expect(contested.statement).toMatch(/correction: The source owner restates/);
    expect(f2.counter_evidence).toContain(contested.id);
    XFCT = f2.explanation_id;
    evidence('e3', { case: k.case_id, standing: k.standing, effect: adj.effect, impact: adj.impact, explanation: f2.explanation_version });
  });

  it('e3 · POSITIVE: the appeal of a DECIDED package, upheld, records reopen_required — the commitment stands, the original record untouched, no package event written', async () => {
    const before = await packageEvents(PKG.pkg);
    const k = (await open(weber, { subjectKind: 'package', subjectId: PKG.pkg, explanationId: XPKG, scope: { statement: 'the committed routing decision', items: [(await readX(XPKG)).items.find((i) => i.role === 'conclusion')!.id] },
      grounds: 'The corridor reopened after the commitment; the routing rests on a closure that no longer holds (synthetic).' })).case;
    expect(k).toMatchObject({ decided: true, package_id: PKG.pkg, subject_version: PKG.v, standing: { basis: 'role:strategy_owner' } });
    await assign(w.authority, k.case_id, w.authority2.principalId);
    const adj = (await adjudicate(w.authority2, k.case_id, { outcome: 'upheld', rationale: 'The decided routing rests on a closure that no longer holds; it is reopened by its owner.', correction: 'The owner reopens the package on the cause appeal_upheld (decision layer).' })).case;
    expect(adj.effect).toMatchObject({ kind: 'reopen_required', package_id: PKG.pkg, committed_version: PKG.v, case_id: k.case_id, cause: 'appeal_upheld' });
    expect(obj(adj.impact)['commitments']).toEqual([expect.objectContaining({ version: PKG.v })]);
    expect((await rows(sql`select state, committed_version from decision.packages_current where package_id = ${PKG.pkg}::uuid`))[0]).toMatchObject({ state: 'committed', committed_version: PKG.v });
    expect(await packageEvents(PKG.pkg)).toEqual(before);
    // the package owner is notified of the reopening it owes
    expect((await itemsOf(k.case_id)).find((i) => i['owner'] === w.owner.principalId && obj(i['details'])['reason'] === 'reopen_required')).toBeDefined();
    evidence('e3-decided', { case: k.case_id, effect: adj.effect });
  });

  it('e3 · REFUSAL: no standing, the PDP, the separation, an agent adjudicator, out of step, a duplicate, the deadline, a draft package, unknown — each refused', async () => {
    const base = { subjectKind: 'package', subjectId: PKG.pkg, scope: { statement: 'the committed routing decision' }, grounds: 'The routing rests on a closure that no longer holds (synthetic).' };
    await refused(open(forecaster, base), /^appeal rejected \(standing\): .* under standing v1/, 403);
    await refused(open(outsider, base), /./, 403);
    await refused(open(weber, { ...base, grounds: 'too short' }), /^appeal rejected \(grounds\)/, 422);
    await refused(open(weber, { ...base, subjectKind: 'scenario' }), /^appeal rejected \(subject_kind\)/, 422);
    await refused(open(weber, { ...base, deadlineAt: new Date(Date.now() + 200 * 86_400_000).toISOString() }), /^appeal rejected \(deadline\)/, 422);
    await refused(open(weber, { ...base, subjectId: uuidv7() }), /^appeal rejected \(unknown_subject\)/, 404);
    await refused(open(weber, { ...base, scope: { statement: 'items without their explanation', items: ['I1'] } }), /^appeal rejected \(scope\)/, 422);
    await refused(open(weber, { ...base, explanationId: XFCT }), /^appeal rejected \(explanation\)/, 422);
    const draft = await c.fullDraft({ as: w.owner });
    await refused(open(weber, { ...base, subjectId: draft.pkg }), /^appeal rejected \(state\): .*a draft is not contested/, 409);
    const k = (await open(weber, base)).case;
    await refused(open(weber, base), /^appeal rejected \(duplicate\)/, 409);
    await refused(adjudicate(w.authority2, k.case_id, { outcome: 'dismissed', rationale: 'Nothing has changed since the commitment.' }), /^appeal rejected \(state\): .*no adjudicator yet/, 409);
    await refused(assign(w.authority, k.case_id, weber.principalId), /^appeal rejected \(adjudicator\)/, 422);
    await refused(assign(weber, k.case_id, w.authority2.principalId), /./, 403);
    const exec = (await open(w.executive, { ...base, grounds: 'The executive contests the decided routing as well (synthetic).' })).case;
    await refused(assign(w.authority, exec.case_id, w.executive.principalId), /^appeal rejected \(separation\)/, 403);
    await refused(assign(w.executive, exec.case_id, w.authority2.principalId), /^appeal rejected \(separation\): the appellant and the subject's owners never choose/, 403);
    await assign(w.authority, k.case_id, w.authority2.principalId);
    await refused(adjudicate(w.authority, k.case_id, { outcome: 'dismissed', rationale: 'Nothing has changed since the commitment.' }), /^appeal rejected \(authority\): only the assigned adjudicator/, 403);
    await refused(adjudicate(w.authority2, k.case_id, { outcome: 'upheld', rationale: 'The routing no longer holds; it is reopened.' }), /^appeal rejected \(correction\)/, 422);
    await refused(close(weber, k.case_id, 'withdrawn by mistake?').then(() => close(weber, k.case_id, 'withdrawn once more')), /^appeal rejected \(state\)/, 409);
    await refused(readCase(uuidv7()), /^appeal rejected \(unknown_case\)/, 404);
    // the guard: the subject, standing, scope, grounds and deadline never change
    await expect(sql`update decision.appeal_cases set grounds = 'rewritten grounds of the case' where case_id = ${exec.case_id}::uuid`.execute(su)).rejects.toThrow(/only its lifecycle changes/);
    await close(w.executive, exec.case_id, 'The executive withdraws: the appellant\'s case covers it.');
    evidence('e3-refusal', { case: k.case_id });
  });

  it('e3 · RECOVERY: the appellant withdraws and opens again; an OVERDUE case is flagged once by the tick step appeal-deadlines (71), then adjudicated and closed', async () => {
    const reg = h.app.get(AttentionTickRegistry);
    expect(reg.steps().map((s) => [s.name, s.order])).toContainEqual([APPEAL_DEADLINES_STEP, APPEAL_DEADLINES_ORDER]);
    const k = (await open(weber, { subjectKind: 'forecast', subjectId: w.forecastId, explanationId: XFCT, scope: { statement: 'the corridor forecast\'s horizon' }, grounds: 'The thirty-day horizon is shorter than the decision\'s window (synthetic).' })).case;
    const wd = (await close(weber, k.case_id, 'Withdrawn: the grounds are restated in a new case.')).case;
    expect(wd).toMatchObject({ state: 'closed', closure: 'withdrawn' });
    const again = (await open(weber, { subjectKind: 'forecast', subjectId: w.forecastId, explanationId: XFCT, scope: { statement: 'the corridor forecast\'s horizon against the decision window' },
      grounds: 'The thirty-day horizon is shorter than the decision\'s ninety-day window (synthetic).' })).case;
    expect(again.state).toBe('opened');
    // the OVERDUE case: a stated superuser insert of a case opened fifteen days ago with a deadline a day past (the port refuses a deadline under an hour)
    const late = uuidv7();
    await sql`insert into decision.appeal_cases (case_id, scope, tenant_id, domain_id, subject_kind, subject_id, subject_title, subject_owners, subject_state_at_open, subject_digest_at_open, decided,
        appellant_principal_id, standing, contest_scope, grounds, evidence, deadline_at, state, opened_at, correlation_id)
      values (${late}::uuid, 'DOMAIN', ${T()}::uuid, ${D()}::uuid, 'forecast', ${w.forecastId}::uuid, 'The corridor forecast (B35 harness, synthetic)', '{}', 'issued', ${'a'.repeat(64)}, false,
        ${weber.principalId}::uuid, '{"rule": "standing v1", "basis": "role:strategy_owner"}'::jsonb, '{"statement": "the forecast\\u0027s band"}'::jsonb,
        'The band is too narrow for the corridor (synthetic, overdue fixture).', '[]'::jsonb, clock_timestamp() - interval '1 day', 'opened', clock_timestamp() - interval '15 days', ${uuidv7()}::uuid)`.execute(su);
    expect((await readCase(late)).overdue).toBe(true);
    const t1 = await tick(1);
    expect(t1['flagged']).toBe(1);
    expect((t1['cases'] as Row[]).map((x) => x['case_id'])).toEqual([late]);
    expect(await caseEvents(late)).toEqual(['appeal.overdue', 'appeal.notified']);
    expect((await itemsOf(late))[0]).toMatchObject({ owner: null, route_roles: ['decision_authority', 'executive', 'domain_admin', 'auditor'], details: expect.objectContaining({ reason: 'overdue' }) });
    const t2 = await tick(2);
    expect(t2['flagged']).toBe(0);
    await assign(w.authority, late, w.authority2.principalId);
    const adj = (await adjudicate(w.authority2, late, { outcome: 'dismissed', rationale: 'The band is the method\'s own; the overdue case is answered and dismissed.' })).case;
    expect(adj.effect).toMatchObject({ kind: 'none' });
    expect((await close(w.authority2, late, 'Answered after its deadline; the delay is on the record.')).case).toMatchObject({ state: 'closed', closure: 'resolved', overdue: false });
    expect((await readCase(late)).events.map((e) => e['event'])).toContain('appeal.overdue');
    evidence('e3-recovery', { withdrawn: k.case_id, reopened: again.case_id, overdue: late, ticks: [t1['flagged'], t2['flagged']] });
  });
});

describe('B35 explanation · e4 · the unified explanation surface (V10-T-008, App. L)', () => {
  it('e4 · POSITIVE: the forecast\'s surface — its current explanation with the contested source and outcome, both versions, the cases on it and on its source', async () => {
    const s = await surface('forecast', w.forecastId);
    expect(s.subject).toMatchObject({ kind: 'forecast', id: w.forecastId });
    expect(s.explanation).toMatchObject({ explanation_id: XFCT, explanation_version: 2, status: { state: 'current' } });
    expect(s.versions.map((v) => v['explanation_version'])).toEqual([2, 1]);
    expect(s.cases.map((k) => k.subject_kind)).toContain('source');
    expect(s.cases.find((k) => k.case_id === SOURCE_CASE)).toMatchObject({ outcome: 'partly_upheld', state: 'closed' });
    const p = await surface('package_version', PKG.pkg, PKG.v);
    expect(p.explanation!.renderings!.length).toBe(2);
    expect(p.cases.map((k) => k.subject_kind).sort()).toEqual(['explanation', 'package', 'package', 'package']);
    expect((await list({ state: 'closed' })).length).toBeGreaterThanOrEqual(4);
  });

  it('e4 · REFUSAL: a subject nothing explains and nobody sees is 404; the PDP refuses a reader without a reading role', async () => {
    await refused(surface('forecast', uuidv7()), /^explanation rejected \(unknown_subject\)/, 404);
    await refused(surface('forecast', w.forecastId, null, outsider), /./, 403);
  });

  it('e4 · RECOVERY: a subject with no explanation yet reads its subject and no explanation; generated, the surface carries it', async () => {
    const before = await surface('run', w.rerouteId);
    expect(before.explanation).toBeNull();
    expect(before.subject).toMatchObject({ kind: 'run', id: w.rerouteId });
    await generate(analyst, 'run', w.rerouteId);
    expect((await surface('run', w.rerouteId)).explanation).toMatchObject({ explanation_version: 1, status: { state: 'current' } });
  });
});
